services:
  redis:
    image: redis:7-alpine
    container_name: redis-persistent
    command:
      - redis-server
      - --appendonly yes # 启用 AOF 持久化
      - --appendfsync everysec # 每秒同步一次
    ports:
      - '6379:6379'
    volumes:
      - ./redis-data:/data
    restart: unless-stopped

volumes:
  redis_data:
    driver: local
