import './AuctionofficialTask.js';
import './BackUptask.js';
import './BOSS2.js';
import './ExchangeTask.js';
import './BOSS.js';
import './ForumTask.js';
import './mojietask.js';
import './PlayerControlTask.js';
import './SecretPlaceplusTask.js';
import './OccupationTask.js';
import './msgTask.js';
import './shenjietask.js';
import './Shoptask.js';
import './ShopGradetask.js';
import './Taopaotask.js';
import './SecretPlaceTask.js';
import './Tiandibang.js';
import './Xijietask.js';

logger.info('定时任务启动');
