import { AuctionofficialTask } from './AuctionofficialTask.js';
import { BOSS2 } from './BOSS2.js';
import { ExchangeTask } from './ExchangeTask.js';
import { BOSS } from './BOSS.js';
import { ForumTask } from './ForumTask.js';
import { MojiTask } from './mojietask.js';
import { PlayerControlTask } from './PlayerControlTask.js';
import { SecretPlaceplusTask } from './SecretPlaceplusTask.js';
import { OccupationTask } from './OccupationTask.js';
import { MsgTask } from './msgTask.js';
import { ShenjieTask } from './shenjietask.js';
import { Shoptask } from './Shoptask.js';
import { ShopGradetask } from './ShopGradetask.js';
import { Taopaotask } from './Taopaotask.js';
import { SecretPlaceTask } from './SecretPlaceTask.js';
import { TiandibangTask } from './Tiandibang.js';
import { Xijietask } from './Xijietask.js';
import { ActionTask } from './ActionTask.js';
import { ActionPlusTask } from './ActionPlusTask.js';
import { GamesTask } from './GamesTask.js';
import { SaijiTask } from './SaijiTask.js';
import { TempTask } from './TempTask.js';
import { scheduleJob } from 'node-schedule';

const startTask = () => {
    scheduleJob('0 0/1 * * * ?', ActionTask);
    scheduleJob('0 0/5 * * * ?', ActionPlusTask);
    scheduleJob('0 */5 * * * ?', GamesTask);
    scheduleJob('0 0 0 ? * 1', SaijiTask);
    scheduleJob('0 0 21 ? * 1,5', Shoptask);
    scheduleJob('0 59 20 * * ?', ExchangeTask);
    scheduleJob('20 0/5 * * * ?', TempTask);
    scheduleJob('0 0 21 * * ?', BOSS);
    scheduleJob('0 0 20 * * ?', BOSS2);
    scheduleJob('0 0/1 * * * ?', AuctionofficialTask);
    scheduleJob('0 0/1 * * * ?', ForumTask);
    scheduleJob('0 0/5 * * * ?', MojiTask);
    scheduleJob('0 0/1 * * * ?', PlayerControlTask);
    scheduleJob('0 0/5 * * * ?', SecretPlaceplusTask);
    scheduleJob('0 0/1 * * * ?', OccupationTask);
    scheduleJob('20 0/5 * * * ?', MsgTask);
    scheduleJob('0 0/5 * * * ?', ShenjieTask);
    scheduleJob('0 59 20 * * ?', ShopGradetask);
    scheduleJob('0 0/5 * * * ?', Taopaotask);
    scheduleJob('0 0/1 * * * ?', SecretPlaceTask);
    scheduleJob('0 0 0 ? * 1', TiandibangTask);
    scheduleJob('0 0/1 * * * ?', Xijietask);
};
logger.info('定时任务启动');

export { startTask };
