import React from 'react';
import fileUrl from '../img/player.jpg.js';
import fileUrl$1 from '../img/player_footer.png.js';
import HTML from './HTML.js';
import { Avatar } from './Avatar.js';
import { getAvatar } from '../../model/utils/utilsx.js';

const BadgeList = ({ title, items }) => (React.createElement("div", { className: 'bg-[hsla(42,71%,91%,.502)] backdrop-blur-sm rounded-lg p-3 border border-white/20 shadow-lg' },
    React.createElement("div", { className: 'flex items-center gap-2 mb-3' },
        React.createElement("div", { className: 'w-6 h-6 bg-white/40 backdrop-blur-sm rounded-lg flex items-center justify-center' },
            React.createElement("span", { className: 'text-sm' }, "\uD83D\uDC65")),
        React.createElement("h3", { className: 'text-xl font-bold text-gray-900 drop-shadow-sm' }, title)),
    React.createElement("div", { className: 'flex flex-wrap gap-2' }, items?.length ? (items.map((it, i) => (React.createElement("span", { key: i, className: 'px-3 py-1.5 rounded-lg bg-white/30 text-sm font-semibold text-gray-900 drop-shadow-sm border border-white/20' }, it)))) : (React.createElement("span", { className: 'text-sm font-medium text-gray-700' }, "\u6682\u65E0")))));
const Association = ({ user_id, ass, mainname, mainqq, weizhi, state, xiulian, level, fuzong, zhanglao, neimen, waimen }) => {
    return (React.createElement(HTML, { className: 'p-0 m-0 w-full text-center', dangerouslySetInnerHTML: {
            __html: `
          body {
            background-image: url(${fileUrl}), url(${fileUrl$1});
            background-repeat: no-repeat, repeat;
            background-size: 100%, auto;
          }
        `
        } },
        React.createElement("div", { className: 'h-3' }),
        React.createElement("div", null,
            React.createElement("div", { className: 'm-3 mx-auto flex flex-nowrap rounded-3xl z-999 bg-[radial-gradient(at_top_left,#ffffff10,#d7edea10)] border-t border-[#ffcc80] border-l border-[#ffcc80] border-r border-[#bb8020] border-b border-[#bb8020] backdrop-blur-sm w-[780px] pb-4' },
                React.createElement("div", { className: 'text-center mt-5 ml-4 w-80' },
                    React.createElement("div", { className: 'flex justify-center' },
                        React.createElement(Avatar, { src: getAvatar(user_id), rootClassName: 'w-64 h-64', className: 'w-44 h-44' })),
                    React.createElement("div", { className: 'mt-3 mx-2 relative' },
                        React.createElement("div", { className: 'bg-gradient-to-r from-blue-400 to-blue-600 rounded-xl px-3 py-2 shadow-xl border-2 border-blue-300 backdrop-blur-sm' },
                            React.createElement("div", { className: 'flex items-center gap-2' },
                                React.createElement("div", { className: 'w-6 h-6 bg-white/20 rounded-full flex items-center justify-center' },
                                    React.createElement("span", { className: 'text-white text-sm' }, "\uD83D\uDC64")),
                                React.createElement("div", { className: 'text-center' },
                                    React.createElement("div", { className: 'text-white text-xs font-semibold opacity-90 drop-shadow-sm' }, "\u8D26\u53F7"),
                                    React.createElement("div", { className: 'text-white text-lg font-bold drop-shadow-lg' }, user_id))),
                            React.createElement("div", { className: 'absolute -top-1 -right-1 w-3 h-3 bg-blue-300 rounded-full opacity-60 animate-pulse' }),
                            React.createElement("div", { className: 'absolute -bottom-1 -left-1 w-2 h-2 bg-blue-400 rounded-full opacity-40' })))),
                React.createElement("div", { className: 'float-right text-left mr-4 mt-4 rounded-3xl flex-1 text-slate-600' },
                    React.createElement("div", { className: 'space-y-2' },
                        React.createElement("div", { className: 'flex items-center gap-2 bg-[hsla(42,71%,91%,.502)] backdrop-blur-sm rounded-lg p-2 border border-white/20' },
                            React.createElement("span", { className: 'text-base' }, "\uD83C\uDFDB\uFE0F"),
                            React.createElement("span", { className: 'text-base font-semibold text-gray-900 drop-shadow-sm' },
                                "\u5B97\u95E8\uFF1A",
                                ass?.宗门名称 || '-')),
                        React.createElement("div", { className: 'flex items-center gap-2 bg-[hsla(42,71%,91%,.502)] backdrop-blur-sm rounded-lg p-2 border border-white/20' },
                            React.createElement("span", { className: 'text-base' }, "\uD83D\uDC51"),
                            React.createElement("span", { className: 'text-base font-semibold text-gray-900 drop-shadow-sm' },
                                "\u5B97\u4E3B\uFF1A",
                                mainname)),
                        React.createElement("div", { className: 'flex items-center gap-2 bg-[hsla(42,71%,91%,.502)] backdrop-blur-sm rounded-lg p-2 border border-white/20' },
                            React.createElement("span", { className: 'text-base' }, "\uD83D\uDCAC"),
                            React.createElement("span", { className: 'text-base font-semibold text-gray-900 drop-shadow-sm' },
                                "QQ\uFF1A",
                                mainqq)),
                        React.createElement("div", { className: 'flex items-center gap-2 bg-[hsla(42,71%,91%,.502)] backdrop-blur-sm rounded-lg p-2 border border-white/20' },
                            React.createElement("span", { className: 'text-base' }, "\u2B50"),
                            React.createElement("span", { className: 'text-base font-semibold text-gray-900 drop-shadow-sm' },
                                "\u7B49\u7EA7\uFF1A",
                                ass?.宗门等级 ?? '-')),
                        React.createElement("div", { className: 'flex items-center gap-2 bg-[hsla(42,71%,91%,.502)] backdrop-blur-sm rounded-lg p-2 border border-white/20' },
                            React.createElement("span", { className: 'text-base' }, "\uD83D\uDCB0"),
                            React.createElement("span", { className: 'text-base font-semibold text-gray-900 drop-shadow-sm' },
                                "\u7075\u77F3\u6C60\uFF1A",
                                ass?.灵石池 ?? 0)),
                        React.createElement("div", { className: 'flex items-center gap-2 bg-[hsla(42,71%,91%,.502)] backdrop-blur-sm rounded-lg p-2 border border-white/20' },
                            React.createElement("span", { className: 'text-base' }, "\uD83D\uDCCD"),
                            React.createElement("span", { className: 'text-base font-semibold text-gray-900 drop-shadow-sm' },
                                "\u4F4D\u7F6E\uFF1A",
                                weizhi || '-'))))),
            React.createElement("div", { className: 'm-3 mx-auto flex flex-nowrap rounded-3xl z-999 bg-[radial-gradient(at_top_left,#ffffff10,#d7edea10)] border-t border-[#ffcc80] border-l border-[#ffcc80] border-r border-[#bb8020] border-b border-[#bb8020] backdrop-blur-sm w-[780px]' },
                React.createElement("div", { className: 'm-4 w-[780px]' },
                    React.createElement("div", { className: 'flex items-center gap-3 mb-3' },
                        React.createElement("div", { className: 'w-6 h-6 bg-white/40 backdrop-blur-sm rounded-lg flex items-center justify-center' },
                            React.createElement("span", { className: 'text-sm' }, "\uD83D\uDCCA")),
                        React.createElement("h2", { className: 'text-xl font-bold text-gray-900 drop-shadow-sm' }, "\u3010\u5B97\u95E8\u4FE1\u606F\u3011")),
                    React.createElement("div", { className: 'space-y-3' },
                        React.createElement("div", { className: 'grid grid-cols-1 md:grid-cols-3 gap-3' },
                            React.createElement("div", { className: 'bg-[hsla(42,71%,91%,.502)] backdrop-blur-sm rounded-lg p-3 border border-white/20 shadow-lg' },
                                React.createElement("div", { className: 'space-y-2' },
                                    React.createElement("div", { className: 'flex items-center justify-between' },
                                        React.createElement("span", { className: 'text-base font-semibold text-gray-800' }, "\u95E8\u6D3E\u72B6\u6001"),
                                        React.createElement("span", { className: 'font-bold text-gray-900 text-lg' }, state)),
                                    React.createElement("div", { className: 'flex items-center justify-between' },
                                        React.createElement("span", { className: 'text-base font-semibold text-gray-800' }, "\u5929\u8D4B\u52A0\u5F3A"),
                                        React.createElement("span", { className: 'font-bold text-gray-900 text-lg' },
                                            xiulian,
                                            "%")),
                                    React.createElement("div", { className: 'flex items-center justify-between' },
                                        React.createElement("span", { className: 'text-base font-semibold text-gray-800' }, "\u5165\u5B97\u95E8\u69DB"),
                                        React.createElement("span", { className: 'font-bold text-gray-900 text-lg' }, level)))),
                            React.createElement("div", { className: 'bg-[hsla(42,71%,91%,.502)] backdrop-blur-sm rounded-lg p-3 border border-white/20 shadow-lg' },
                                React.createElement("div", { className: 'space-y-2' },
                                    React.createElement("div", { className: 'flex items-center justify-between' },
                                        React.createElement("span", { className: 'text-base font-semibold text-gray-800' }, "\u5927\u9635\u5F3A\u5EA6"),
                                        React.createElement("span", { className: 'font-bold text-gray-900 text-lg' }, ass?.大阵血量 ?? 0)),
                                    React.createElement("div", { className: 'flex items-center justify-between' },
                                        React.createElement("span", { className: 'text-base font-semibold text-gray-800' }, "\u5EFA\u8BBE\u7B49\u7EA7"),
                                        React.createElement("span", { className: 'font-bold text-gray-900 text-lg' }, ass?.宗门建设等级 ?? '-')),
                                    React.createElement("div", { className: 'flex items-center justify-between' },
                                        React.createElement("span", { className: 'text-base font-semibold text-gray-800' }, "\u6210\u5458\u6570\u91CF"),
                                        React.createElement("span", { className: 'font-bold text-gray-900 text-lg' }, ass?.所有成员?.length ?? 0)))),
                            React.createElement("div", { className: 'bg-[hsla(42,71%,91%,.502)] backdrop-blur-sm rounded-lg p-3 border border-white/20 shadow-lg' },
                                React.createElement("div", { className: 'space-y-2' },
                                    React.createElement("div", { className: 'flex items-center justify-between' },
                                        React.createElement("span", { className: 'text-base font-semibold text-gray-800' }, "\u9547\u5B97\u795E\u517D"),
                                        React.createElement("span", { className: 'font-bold text-gray-900 text-lg' }, ass?.宗门神兽 ?? '-')),
                                    React.createElement("div", { className: 'flex items-center justify-between' },
                                        React.createElement("span", { className: 'text-base font-semibold text-gray-800' }, "\u521B\u7ACB\u65F6\u95F4"),
                                        React.createElement("span", { className: 'font-bold text-gray-900 text-lg' }, ass?.创立时间?.[0] || '-')))))))),
            React.createElement("div", { className: 'm-3 mx-auto flex flex-nowrap rounded-3xl z-999 bg-[radial-gradient(at_top_left,#ffffff10,#d7edea10)] border-t border-[#ffcc80] border-l border-[#ffcc80] border-r border-[#bb8020] border-b border-[#bb8020] backdrop-blur-sm w-[780px]' },
                React.createElement("div", { className: 'm-4 w-[780px]' },
                    React.createElement("div", { className: 'space-y-3' },
                        React.createElement("div", { className: 'grid grid-cols-1 md:grid-cols-2 gap-3' },
                            React.createElement(BadgeList, { title: '\u526F\u5B97\u4E3B', items: fuzong }),
                            React.createElement(BadgeList, { title: '\u957F\u8001', items: zhanglao })),
                        React.createElement("div", { className: 'grid grid-cols-1 md:grid-cols-2 gap-3' },
                            React.createElement(BadgeList, { title: '\u5185\u95E8\u5F1F\u5B50', items: neimen }),
                            React.createElement(BadgeList, { title: '\u5916\u95E8\u5F1F\u5B50', items: waimen })))))),
        React.createElement("div", { className: 'h-3' })));
};

export { Association as default };
