import React from 'react';
import classNames from 'classnames';
import HTML from './HTML.js';

const CombatResult = ({ msg, playerA, playerB, result }) => {
    return (React.createElement(HTML, { className: 'w-full text-center p-4 md:p-8 bg-gradient-to-br from-slate-900 via-purple-900 to-slate-900 relative min-h-screen' },
        React.createElement("div", { className: 'absolute inset-0 opacity-30', style: {
                backgroundImage: "url(\"data:image/svg+xml,%3Csvg width='60' height='60' viewBox='0 0 60 60' xmlns='http://www.w3.org/2000/svg'%3E%3Cg fill='none' fill-rule='evenodd'%3E%3Cg fill='%23ffffff' fill-opacity='0.03'%3E%3Cpath d='M30 30c0-11.046-8.954-20-20-20s-20 8.954-20 20 8.954 20 20 20 20-8.954 20-20zm0 0c0 11.046 8.954 20 20 20s20-8.954 20-20-8.954-20-20-20-20 8.954-20 20z'/%3E%3C/g%3E%3C/g%3E%3C/svg%3E\")"
            } }),
        React.createElement("div", { className: 'relative z-10 max-w-5xl mx-auto' },
            React.createElement("div", { className: 'mb-6' },
                React.createElement("div", { className: 'gap-2 inline-flex items-center justify-center px-8 py-4 bg-gradient-to-r from-amber-500/20 to-orange-500/20 backdrop-blur-sm border border-amber-400/30 rounded-full shadow-2xl' },
                    React.createElement("div", { className: 'w-6 h-6 bg-gradient-to-br from-amber-400 to-orange-500 rounded-full flex items-center justify-center' },
                        React.createElement("span", { className: 'text-white text-sm font-bold' }, "\u2694")),
                    React.createElement("h1", { className: 'text-2xl md:text-3xl font-bold bg-gradient-to-r from-amber-400 via-orange-400 to-red-400 bg-clip-text text-transparent' }, "\u4FEE\u4ED9\u5BF9\u51B3"),
                    React.createElement("div", null,
                        result === 'A' && (React.createElement("div", { className: 'inline-flex items-center px-6 py-2 bg-gradient-to-r from-green-500/20 to-emerald-500/20 backdrop-blur-sm border border-green-400/30 rounded-full' },
                            React.createElement("span", { className: 'text-green-400 text-lg mr-2' }, "\uD83C\uDFC6"),
                            React.createElement("span", { className: 'text-green-300 font-semibold' },
                                playerA.name,
                                " \u83B7\u80DC\uFF01"))),
                        result === 'B' && (React.createElement("div", { className: 'inline-flex items-center px-6 py-2 bg-gradient-to-r from-green-500/20 to-emerald-500/20 backdrop-blur-sm border border-green-400/30 rounded-full' },
                            React.createElement("span", { className: 'text-green-400 text-lg mr-2' }, "\uD83C\uDFC6"),
                            React.createElement("span", { className: 'text-green-300 font-semibold' },
                                playerB.name,
                                " \u83B7\u80DC\uFF01"))),
                        result === 'draw' && (React.createElement("div", { className: 'inline-flex items-center px-6 py-2 bg-gradient-to-r from-yellow-500/20 to-orange-500/20 backdrop-blur-sm border border-yellow-400/30 rounded-full' },
                            React.createElement("span", { className: 'text-yellow-400 text-lg mr-2' }, "\uD83E\uDD1D"),
                            React.createElement("span", { className: 'text-yellow-300 font-semibold' }, "\u52BF\u5747\u529B\u654C\uFF0C\u5E73\u5C40\uFF01")))))),
            React.createElement("div", { className: 'bg-gradient-to-br from-slate-800/80 via-purple-800/60 to-slate-800/80 backdrop-blur-md border border-purple-400/30 rounded-2xl shadow-2xl p-4' },
                React.createElement("div", { className: 'relative' },
                    React.createElement("div", { className: 'absolute top-0 left-1/2 transform -translate-x-1/2 w-32 h-1 bg-gradient-to-r from-transparent via-purple-400 to-transparent' }),
                    React.createElement("div", { className: 'relative z-10' },
                        React.createElement("div", { className: 'flex gap-4 mb-6' },
                            React.createElement("div", { className: 'flex-1 bg-gradient-to-br from-blue-900/60 to-cyan-800/40 backdrop-blur-sm border border-blue-400/30 rounded-xl p-6 shadow-lg relative overflow-hidden' },
                                React.createElement("div", { className: 'absolute top-0 right-0 w-20 h-20 bg-blue-400/10 rounded-full blur-xl' }),
                                React.createElement("div", { className: 'flex flex-col items-center' },
                                    React.createElement("div", { className: 'relative mb-4' },
                                        React.createElement("div", { className: 'w-20 h-20 bg-gradient-to-br from-blue-400 to-cyan-400 rounded-full p-1 shadow-lg' },
                                            React.createElement("div", { className: 'w-full h-full rounded-full overflow-hidden bg-slate-800 flex items-center justify-center' }, playerA.avatar ? (React.createElement("img", { src: playerA.avatar, alt: playerA.name, className: 'w-full h-full object-cover' })) : (React.createElement("span", { className: 'text-white text-2xl' }, "\uD83D\uDC64")))),
                                        React.createElement("div", { className: 'absolute -bottom-2 -right-2 w-8 h-8 bg-gradient-to-br from-blue-500 to-cyan-500 rounded-full flex items-center justify-center border-2 border-slate-800' },
                                            React.createElement("span", { className: 'text-white text-xs font-bold' }, "A"))),
                                    React.createElement("h3", { className: 'text-lg font-semibold text-blue-200 mb-2' }, playerA.name),
                                    React.createElement("div", { className: 'bg-slate-800/50 rounded-lg p-3 border border-blue-400/20 w-full mb-3' },
                                        React.createElement("div", { className: 'flex items-center justify-between' },
                                            React.createElement("span", { className: 'text-blue-100 text-sm' }, "\u6218\u529B"),
                                            React.createElement("span", { className: 'text-amber-300 font-bold text-lg' }, playerA.power))),
                                    React.createElement("div", { className: 'bg-slate-800/50 rounded-lg p-3 border border-blue-400/20 w-full' },
                                        React.createElement("div", { className: 'flex items-center justify-between mb-2' },
                                            React.createElement("span", { className: 'text-blue-100 text-sm' }, "\u8840\u91CF"),
                                            React.createElement("span", { className: 'text-red-300 font-bold text-sm' },
                                                playerA.hp,
                                                "/",
                                                playerA.maxHp)),
                                        React.createElement("div", { className: 'w-full bg-slate-700 rounded-full h-2' },
                                            React.createElement("div", { className: 'bg-gradient-to-r from-red-500 to-red-400 h-2 rounded-full transition-all duration-300', style: {
                                                    width: `${Math.max(0, (playerA.hp / playerA.maxHp) * 100)}%`
                                                } }))))),
                            React.createElement("div", { className: 'hidden md:flex items-center justify-center' },
                                React.createElement("div", { className: 'relative' },
                                    React.createElement("div", { className: classNames('w-16 h-16 rounded-full flex items-center justify-center shadow-2xl', {
                                            'bg-gradient-to-br from-blue-500 to-cyan-500': result === 'A',
                                            'bg-gradient-to-br from-red-500 to-pink-500': result === 'B',
                                            'bg-gradient-to-br from-purple-500 to-pink-500': result === 'draw'
                                        }) },
                                        React.createElement("span", { className: 'text-white text-2xl font-bold' }, result === 'A' ? '战胜' : result === 'B' ? '战败' : 'VS')),
                                    React.createElement("div", { className: classNames('absolute inset-0 rounded-full blur-lg opacity-50', {
                                            'bg-gradient-to-br from-blue-500 to-cyan-500': result === 'A',
                                            'bg-gradient-to-br from-red-500 to-pink-500': result === 'B',
                                            'bg-gradient-to-br from-purple-500 to-pink-500': result === 'draw'
                                        }) }))),
                            React.createElement("div", { className: 'flex-1 bg-gradient-to-br from-red-900/60 to-pink-800/40 backdrop-blur-sm border border-red-400/30 rounded-xl p-6 shadow-lg relative overflow-hidden' },
                                React.createElement("div", { className: 'absolute top-0 left-0 w-20 h-20 bg-red-400/10 rounded-full blur-xl' }),
                                React.createElement("div", { className: 'flex flex-col items-center' },
                                    React.createElement("div", { className: 'relative mb-4' },
                                        React.createElement("div", { className: 'w-20 h-20 bg-gradient-to-br from-red-400 to-pink-400 rounded-full p-1 shadow-lg' },
                                            React.createElement("div", { className: 'w-full h-full rounded-full overflow-hidden bg-slate-800 flex items-center justify-center' }, playerB.avatar ? (React.createElement("img", { src: playerB.avatar, alt: playerB.name, className: 'w-full h-full object-cover' })) : (React.createElement("span", { className: 'text-white text-2xl' }, "\uD83D\uDC79")))),
                                        React.createElement("div", { className: 'absolute -bottom-2 -right-2 w-8 h-8 bg-gradient-to-br from-red-500 to-pink-500 rounded-full flex items-center justify-center border-2 border-slate-800' },
                                            React.createElement("span", { className: 'text-white text-xs font-bold' }, "B"))),
                                    React.createElement("h3", { className: 'text-lg font-semibold text-red-200 mb-2' }, playerB.name),
                                    React.createElement("div", { className: 'bg-slate-800/50 rounded-lg p-3 border border-red-400/20 w-full mb-3' },
                                        React.createElement("div", { className: 'flex items-center justify-between' },
                                            React.createElement("span", { className: 'text-red-100 text-sm' }, "\u6218\u529B"),
                                            React.createElement("span", { className: 'text-amber-300 font-bold text-lg' }, playerB.power))),
                                    React.createElement("div", { className: 'bg-slate-800/50 rounded-lg p-3 border border-red-400/20 w-full' },
                                        React.createElement("div", { className: 'flex items-center justify-between mb-2' },
                                            React.createElement("span", { className: 'text-red-100 text-sm' }, "\u8840\u91CF"),
                                            React.createElement("span", { className: 'text-red-300 font-bold text-sm' },
                                                playerB.hp,
                                                "/",
                                                playerB.maxHp)),
                                        React.createElement("div", { className: 'w-full bg-slate-700 rounded-full h-2' },
                                            React.createElement("div", { className: 'bg-gradient-to-r from-red-500 to-red-400 h-2 rounded-full transition-all duration-300', style: {
                                                    width: `${Math.max(0, (playerB.hp / playerB.maxHp) * 100)}%`
                                                } })))))),
                        React.createElement("div", { className: 'bg-gradient-to-br from-slate-700/80 to-slate-800/80 backdrop-blur-sm border border-slate-500/30 rounded-xl p-6 shadow-lg' },
                            React.createElement("div", { className: 'flex items-center justify-center mb-6' },
                                React.createElement("div", { className: 'w-10 h-10 bg-gradient-to-br from-yellow-400 to-orange-400 rounded-full flex items-center justify-center mr-3' },
                                    React.createElement("span", { className: 'text-white text-lg' }, "\u26A1")),
                                React.createElement("h3", { className: 'text-xl font-semibold text-slate-200' }, "\u6218\u6597\u8FC7\u7A0B")),
                            React.createElement("div", { className: 'space-y-4 pr-2' }, msg.map((item, index) => (React.createElement("div", { key: index, className: 'bg-gradient-to-r from-slate-600/50 to-slate-700/50 backdrop-blur-sm border border-slate-500/20 rounded-lg p-4 shadow-md relative overflow-hidden' },
                                React.createElement("div", { className: 'absolute top-0 left-0 w-full h-1 bg-gradient-to-r from-transparent via-slate-400/30 to-transparent' }),
                                React.createElement("div", { className: 'flex items-start' },
                                    React.createElement("div", { className: 'w-8 h-8 bg-gradient-to-br from-amber-400 to-orange-500 rounded-full flex items-center justify-center mr-4 mt-0.5 flex-shrink-0 shadow-md' },
                                        React.createElement("span", { className: 'text-white text-sm font-bold' }, index + 1)),
                                    React.createElement("p", { className: 'text-slate-200 text-sm leading-relaxed flex-1' }, item)))))))))),
            React.createElement("div", { className: 'flex justify-center' },
                React.createElement("div", { className: 'flex space-x-4' },
                    React.createElement("div", { className: 'w-3 h-3 bg-gradient-to-br from-purple-400 to-purple-600 rounded-full shadow-lg' }),
                    React.createElement("div", { className: 'w-3 h-3 bg-gradient-to-br from-blue-400 to-blue-600 rounded-full shadow-lg' }),
                    React.createElement("div", { className: 'w-3 h-3 bg-gradient-to-br from-cyan-400 to-cyan-600 rounded-full shadow-lg' }),
                    React.createElement("div", { className: 'w-3 h-3 bg-gradient-to-br from-purple-400 to-purple-600 rounded-full shadow-lg' }))))));
};

export { CombatResult as default };
