import React from 'react';
import HTML from './HTML.js';
import fileUrl from '../img/fairyrealm.jpg.js';

const Forum = ({ Forum: forumData }) => {
    return (React.createElement(HTML, { className: "w-full text-center p-4 md:p-8 bg-top bg-cover min-h-screen", style: { backgroundImage: `url(${fileUrl})` } },
        React.createElement("div", { className: "absolute inset-0 pointer-events-none \n        bg-[radial-gradient(circle_at_center,rgba(255,255,255,0.15)_1px,transparent_1px)] \n        bg-[length:18px_18px]" }),
        React.createElement("div", { className: "absolute inset-0 bg-gradient-to-b from-sky-900/40 via-sky-800/20 to-transparent" }),
        React.createElement("main", { className: "relative z-10 max-w-6xl mx-auto space-y-12" },
            React.createElement("header", { className: "space-y-6 flex flex-col items-center" },
                React.createElement("div", { className: "relative" },
                    React.createElement("div", { className: "absolute inset-0 bg-gradient-to-r from-sky-400/30 to-cyan-400/30 rounded-3xl blur-xl" }),
                    React.createElement("h1", { className: "relative inline-block px-10 py-4 rounded-3xl \n              bg-gradient-to-r from-sky-400/60 via-cyan-300/50 to-sky-400/60 \n              backdrop-blur-xl border-2 border-sky-300/50 \n              text-3xl md:text-4xl font-extrabold tracking-widest shadow-2xl ring-2 ring-sky-200/60" },
                        React.createElement("span", { className: "bg-gradient-to-r from-sky-100 to-cyan-100 bg-clip-text text-transparent" }, "\u805A\u5B9D\u5802"))),
                React.createElement("div", { className: "relative" },
                    React.createElement("div", { className: "absolute inset-0 bg-gradient-to-r from-sky-500/10 to-cyan-500/10 rounded-2xl blur-lg" }),
                    React.createElement("div", { className: "relative px-6 py-3 rounded-2xl bg-white/10 backdrop-blur-md border border-sky-200/30 text-sky-100/90 text-xs md:text-sm space-y-2 drop-shadow" },
                        React.createElement("div", { className: "flex items-center justify-center space-x-2" },
                            React.createElement("span", { className: "text-sky-300" }, "\uD83D\uDCDC"),
                            React.createElement("span", null, "\u53D1\u5E03\u6307\u4EE4\uFF1A#\u53D1\u5E03+\u7269\u54C1\u540D*\u4EF7\u683C*\u6570\u91CF")),
                        React.createElement("div", { className: "flex items-center justify-center space-x-2" },
                            React.createElement("span", { className: "text-sky-300" }, "\uD83E\uDD1D"),
                            React.createElement("span", null, "\u63A5\u53D6\u6307\u4EE4\uFF1A#\u63A5\u53D6+\u7F16\u53F7*\u6570\u91CF")),
                        React.createElement("div", { className: "flex items-center justify-center space-x-2" },
                            React.createElement("span", { className: "text-sky-300" }, "\u274C"),
                            React.createElement("span", null, "\u53D6\u6D88\u6307\u4EE4\uFF1A#\u53D6\u6D88+\u7F16\u53F7"))))),
            React.createElement("section", { className: "relative" },
                React.createElement("div", { className: "absolute inset-0 bg-gradient-to-br from-sky-600/5 to-cyan-600/5 rounded-3xl blur-2xl" }),
                React.createElement("div", { className: "relative grid gap-8 sm:grid-cols-2 lg:grid-cols-3" }, forumData?.length ? (forumData.map((item, index) => (React.createElement("article", { key: index, className: "relative rounded-2xl p-6 flex flex-col gap-3\n                    bg-white/15 backdrop-blur-xl border border-sky-200/40\n                    shadow-xl overflow-hidden" },
                    React.createElement("div", { className: "absolute top-0 left-0 w-full h-1 \n                    bg-gradient-to-r from-cyan-300 via-sky-400 to-cyan-300 shadow-md" }),
                    React.createElement("div", { className: "absolute top-3 right-3 w-3 h-3 bg-cyan-400/50 rounded-full" }),
                    React.createElement("div", { className: "space-y-3" },
                        React.createElement("div", { className: "flex items-center space-x-2" },
                            React.createElement("span", { className: "text-sky-300 text-lg" }, "\uD83C\uDFEA"),
                            React.createElement("h2", { className: "text-lg font-bold tracking-wide text-cyan-100 drop-shadow" },
                                "\u3010",
                                item.class,
                                "\u3011",
                                item.name)),
                        React.createElement("div", { className: "space-y-2 text-sm" },
                            React.createElement("div", { className: "flex items-center space-x-2 text-sky-100/90" },
                                React.createElement("span", { className: "text-sky-300" }, "\uD83C\uDD94"),
                                React.createElement("span", null, "\u7F16\u53F7\uFF1A"),
                                React.createElement("span", { className: "font-semibold text-indigo-200" },
                                    "No.",
                                    item.num)),
                            React.createElement("div", { className: "flex items-center space-x-2 text-sky-100/90" },
                                React.createElement("span", { className: "text-amber-300" }, "\uD83D\uDCB0"),
                                React.createElement("span", null, "\u5355\u4EF7\uFF1A"),
                                React.createElement("span", { className: "font-semibold text-amber-200" }, item.price)),
                            React.createElement("div", { className: "flex items-center space-x-2 text-sky-100/90" },
                                React.createElement("span", { className: "text-emerald-300" }, "\uD83D\uDCE6"),
                                React.createElement("span", null, "\u6570\u91CF\uFF1A"),
                                React.createElement("span", { className: "font-semibold text-emerald-200" }, item.aconut)),
                            React.createElement("div", { className: "flex items-center space-x-2 text-sky-100/90" },
                                React.createElement("span", { className: "text-orange-300" }, "\uD83E\uDE99"),
                                React.createElement("span", null, "\u603B\u4EF7\uFF1A"),
                                React.createElement("span", { className: "font-semibold text-orange-200" }, item.whole)),
                            React.createElement("div", { className: "flex items-center space-x-2 text-sky-100/90" },
                                React.createElement("span", { className: "text-cyan-300" }, "\u2709"),
                                React.createElement("span", null, "\u8D26\u53F7\uFF1A"),
                                React.createElement("span", { className: "font-semibold text-cyan-200" }, item.qq)))))))) : (React.createElement("div", { className: "col-span-full relative" },
                    React.createElement("div", { className: "absolute inset-0 bg-gradient-to-br from-sky-600/10 to-cyan-600/10 rounded-2xl blur-xl" }),
                    React.createElement("div", { className: "relative px-8 py-6 rounded-2xl \n                  border border-sky-200/40 bg-white/10 \n                  text-sky-100/80 backdrop-blur-xl" },
                        React.createElement("div", { className: "flex items-center justify-center space-x-3" },
                            React.createElement("span", { className: "text-sky-300 text-xl" }, "\uD83D\uDCED"),
                            React.createElement("span", { className: "text-lg font-semibold" }, "\u6682\u65E0\u53D1\u5E03"),
                            React.createElement("span", { className: "text-sky-300 text-xl" }, "\uD83D\uDCED"))))))),
            React.createElement("div", { className: "flex justify-center space-x-4 pt-8" },
                React.createElement("div", { className: "w-16 h-1 bg-gradient-to-r from-sky-400/50 to-transparent rounded-full" }),
                React.createElement("div", { className: "w-8 h-8 bg-gradient-to-br from-sky-400/30 to-cyan-400/30 rounded-full flex items-center justify-center" },
                    React.createElement("span", { className: "text-white/70 text-sm" }, "\uD83D\uDC8E")),
                React.createElement("div", { className: "w-16 h-1 bg-gradient-to-l from-cyan-400/50 to-transparent rounded-full" })))));
};

export { Forum as default };
