import React from 'react';
import fileUrl from '../img/player.jpg.js';
import fileUrl$1 from '../img/player_footer.png.js';
import HTML from './HTML.js';
import { Avatar } from './Avatar.js';
import { getAvatar } from '../../model/utils/utilsx.js';

const Najie = ({ user_id, player = {}, strand_hp = {}, najie = {}, strand_lingshi = {} }) => {
    const qualities = ['劣', '普', '优', '精', '极', '绝', '顶'];
    const lockStatus = ['未锁定', '已锁定'];
    const elements = ['金', '木', '土', '水', '火'];
    const renderEquipmentStats = item => {
        const isAbsolute = item.atk > 10 || item.def > 10 || item.HP > 10;
        return {
            attribute: isAbsolute ? '无' : elements[item.id - 1],
            atk: isAbsolute ? item.atk.toFixed(0) : (item.atk * 100).toFixed(0) + '%',
            def: isAbsolute ? item.def.toFixed(0) : (item.def * 100).toFixed(0) + '%',
            HP: isAbsolute ? item.HP.toFixed(0) : (item.HP * 100).toFixed(0) + '%'
        };
    };
    return (React.createElement(HTML, { className: 'p-0 m-0 w-full text-center', dangerouslySetInnerHTML: {
            __html: `
          body {
            background-image: url(${fileUrl}), url(${fileUrl$1});
            background-repeat: no-repeat, repeat;
            background-size: 100%, auto;
          }
        `
        } },
        React.createElement("div", { className: 'min-h-screen relative overflow-hidden' },
            React.createElement("div", { className: 'absolute inset-0' },
                React.createElement("div", { className: 'absolute top-10 left-10 w-32 h-32 border border-white/20 rounded-full backdrop-blur-sm' }),
                React.createElement("div", { className: 'absolute top-32 right-20 w-24 h-24 border border-white/20 rounded-full backdrop-blur-sm' }),
                React.createElement("div", { className: 'absolute bottom-20 left-1/4 w-16 h-16 border border-white/20 rounded-full backdrop-blur-sm' }),
                React.createElement("div", { className: 'absolute bottom-40 right-1/3 w-20 h-20 border border-white/20 rounded-full backdrop-blur-sm' }),
                React.createElement("div", { className: 'absolute top-20 left-1/3 w-20 h-20 border border-white/15 rounded-full backdrop-blur-sm' }),
                React.createElement("div", { className: 'absolute top-60 right-1/4 w-16 h-16 border border-white/15 rounded-full backdrop-blur-sm' }),
                React.createElement("div", { className: 'absolute bottom-60 left-1/5 w-24 h-24 border border-white/15 rounded-full backdrop-blur-sm' }),
                React.createElement("div", { className: 'absolute top-40 left-1/2 w-12 h-12 border border-white/10 rounded-full backdrop-blur-sm' }),
                React.createElement("div", { className: 'absolute bottom-80 right-1/6 w-28 h-28 border border-white/10 rounded-full backdrop-blur-sm' })),
            React.createElement("div", { className: 'relative z-10 container mx-auto px-4 py-8' },
                React.createElement("div", { className: 'max-w-4xl mx-auto mb-8' },
                    React.createElement("div", { className: 'relative' },
                        React.createElement("div", { className: 'absolute inset-0 bg-white/15 rounded-3xl blur-2xl' }),
                        React.createElement("div", { className: 'absolute inset-0 bg-white/10 rounded-3xl blur-xl' }),
                        React.createElement("div", { className: 'relative backdrop-blur-xl bg-white/25 rounded-3xl border border-white/40 p-6 shadow-2xl' },
                            React.createElement("div", { className: 'flex flex-col md:flex-row items-center gap-6' },
                                React.createElement("div", { className: 'flex flex-col items-center' },
                                    React.createElement("div", { className: 'relative' },
                                        React.createElement("div", { className: 'absolute inset-0 bg-white/30 rounded-full blur-lg' }),
                                        React.createElement("div", { className: 'absolute inset-0 bg-white/20 rounded-full blur-md' }),
                                        React.createElement(Avatar, { src: getAvatar(user_id), rootClassName: 'w-60 h-60', className: 'w-32 h-32 rounded-full border-4 border-white/50 relative z-10 backdrop-blur-sm' })),
                                    React.createElement("div", { className: 'mt-3 text-center' },
                                        React.createElement("div", { className: 'text-lg font-bold text-gray-700' }, user_id),
                                        React.createElement("div", { className: 'text-sm text-gray-600' }, "\u4FEE\u4ED9\u8005"))),
                                React.createElement("div", { className: 'flex-1 space-y-4' },
                                    React.createElement("div", { className: 'grid grid-cols-1 md:grid-cols-2 gap-4' },
                                        React.createElement("div", { className: 'bg-white/20 backdrop-blur-lg rounded-xl p-4 border border-white/30 shadow-lg' },
                                            React.createElement("div", { className: 'flex items-center gap-2 mb-2' },
                                                React.createElement("div", { className: 'w-6 h-6 bg-white/40 backdrop-blur-sm rounded-full flex items-center justify-center' },
                                                    React.createElement("span", { className: 'text-xs' }, "\uD83D\uDC64")),
                                                React.createElement("span", { className: 'text-sm font-medium text-gray-700' }, "\u9053\u53F7")),
                                            React.createElement("div", { className: 'text-lg font-bold text-gray-800' }, player.名号 || '无名')),
                                        React.createElement("div", { className: 'bg-white/20 backdrop-blur-lg rounded-xl p-4 border border-white/30 shadow-lg' },
                                            React.createElement("div", { className: 'flex items-center gap-2 mb-2' },
                                                React.createElement("div", { className: 'w-6 h-6 bg-white/40 backdrop-blur-sm rounded-full flex items-center justify-center' },
                                                    React.createElement("span", { className: 'text-xs' }, "\u2B50")),
                                                React.createElement("span", { className: 'text-sm font-medium text-gray-700' }, "\u7B49\u7EA7")),
                                            React.createElement("div", { className: 'text-lg font-bold text-gray-800' }, najie.等级 || 0)),
                                        React.createElement("div", { className: 'bg-white/20 backdrop-blur-lg rounded-xl p-4 border border-white/30 shadow-lg' },
                                            React.createElement("div", { className: 'flex items-center gap-2 mb-2' },
                                                React.createElement("div", { className: 'w-6 h-6 bg-white/40 backdrop-blur-sm rounded-full flex items-center justify-center' },
                                                    React.createElement("span", { className: 'text-xs' }, "\u2764\uFE0F")),
                                                React.createElement("span", { className: 'text-sm font-medium text-gray-700' }, "\u751F\u547D\u503C")),
                                            React.createElement("div", { className: 'space-y-2' },
                                                React.createElement("div", { className: 'flex items-center gap-2' },
                                                    React.createElement("div", { className: 'flex-1 bg-white/30 backdrop-blur-sm rounded-full h-3' },
                                                        React.createElement("div", { className: 'bg-gradient-to-r from-red-400 to-red-600 h-3 rounded-full', style: strand_hp.style })),
                                                    React.createElement("span", { className: 'text-sm font-bold text-gray-800' },
                                                        player.当前血量 || 0,
                                                        "/",
                                                        player.血量上限 || 0)))),
                                        React.createElement("div", { className: 'bg-white/20 backdrop-blur-lg rounded-xl p-4 border border-white/30 shadow-lg' },
                                            React.createElement("div", { className: 'flex items-center gap-2 mb-2' },
                                                React.createElement("div", { className: 'w-6 h-6 bg-white/40 backdrop-blur-sm rounded-full flex items-center justify-center' },
                                                    React.createElement("span", { className: 'text-xs' }, "\uD83D\uDC8E")),
                                                React.createElement("span", { className: 'text-sm font-medium text-gray-700' }, "\u7075\u77F3\u50A8\u91CF")),
                                            React.createElement("div", { className: 'space-y-2' },
                                                React.createElement("div", { className: 'flex items-center gap-2' },
                                                    React.createElement("div", { className: 'flex-1 bg-white/30 backdrop-blur-sm rounded-full h-3' },
                                                        React.createElement("div", { className: 'bg-gradient-to-r from-blue-400 to-blue-600 h-3 rounded-full', style: strand_lingshi.style })),
                                                    React.createElement("span", { className: 'text-sm font-bold text-gray-800' },
                                                        najie.灵石 || 0,
                                                        "/",
                                                        najie.灵石上限 || 0)))))))))),
                React.createElement("div", { className: 'max-w-6xl mx-auto space-y-6' },
                    najie.道具?.length > 0 && (React.createElement("div", { className: 'relative' },
                        React.createElement("div", { className: 'absolute inset-0 bg-white/15 rounded-3xl blur-2xl' }),
                        React.createElement("div", { className: 'absolute inset-0 bg-white/10 rounded-3xl blur-xl' }),
                        React.createElement("div", { className: 'relative backdrop-blur-xl bg-white/25 rounded-3xl border border-white/40 p-6 shadow-2xl' },
                            React.createElement("div", { className: 'flex items-center gap-3 mb-6' },
                                React.createElement("div", { className: 'w-10 h-10 bg-white/40 backdrop-blur-sm rounded-lg flex items-center justify-center' },
                                    React.createElement("span", { className: 'text-lg' }, "\uD83C\uDF92")),
                                React.createElement("h2", { className: 'text-2xl font-bold text-gray-700' }, "\u3010\u9053\u5177\u3011")),
                            React.createElement("div", { className: 'grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4' }, najie.道具.map((item, index) => (React.createElement("div", { key: index, className: 'bg-white/20 backdrop-blur-lg rounded-xl p-4 border border-white/30 shadow-lg' },
                                React.createElement("div", { className: 'flex items-center gap-2 mb-2' },
                                    React.createElement("div", { className: 'w-6 h-6 bg-white/40 backdrop-blur-sm rounded-full flex items-center justify-center' },
                                        React.createElement("span", { className: 'text-xs' }, "\uD83D\uDCE6")),
                                    React.createElement("h3", { className: 'text-lg font-bold text-gray-800' },
                                        "\u3010",
                                        item.type,
                                        "\u3011",
                                        item.name)),
                                React.createElement("div", { className: 'space-y-2 text-sm' },
                                    React.createElement("div", { className: 'text-gray-700' },
                                        "\u4ECB\u7ECD\uFF1A",
                                        item.desc),
                                    React.createElement("div", { className: 'flex items-center gap-2' },
                                        React.createElement("span", { className: 'text-gray-600' }, "\u6570\u91CF\uFF1A"),
                                        React.createElement("span", { className: 'font-bold text-gray-800' }, item.数量)),
                                    React.createElement("div", { className: 'flex items-center gap-2' },
                                        React.createElement("span", { className: 'text-gray-600' }, "\u51FA\u552E\u4EF7\uFF1A"),
                                        React.createElement("span", { className: 'font-bold text-gray-800' },
                                            item.出售价,
                                            "\u7075\u77F3")),
                                    React.createElement("div", { className: 'flex items-center gap-2' },
                                        React.createElement("span", { className: 'text-gray-600' }, "\u4EE3\u53F7\uFF1A"),
                                        React.createElement("span", { className: 'font-bold text-gray-800' }, index + 101)))))))))),
                    najie.装备?.length > 0 && (React.createElement("div", { className: 'relative' },
                        React.createElement("div", { className: 'absolute inset-0 bg-white/15 rounded-3xl blur-2xl' }),
                        React.createElement("div", { className: 'absolute inset-0 bg-white/10 rounded-3xl blur-xl' }),
                        React.createElement("div", { className: 'relative backdrop-blur-xl bg-white/25 rounded-3xl border border-white/40 p-6 shadow-2xl' },
                            React.createElement("div", { className: 'flex items-center gap-3 mb-6' },
                                React.createElement("div", { className: 'w-10 h-10 bg-white/40 backdrop-blur-sm rounded-lg flex items-center justify-center' },
                                    React.createElement("span", { className: 'text-lg' }, "\u2694\uFE0F")),
                                React.createElement("h2", { className: 'text-2xl font-bold text-gray-700' }, "\u3010\u88C5\u5907\u3011")),
                            React.createElement("div", { className: 'grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4' }, najie.装备.map((item, index) => {
                                const stats = renderEquipmentStats(item);
                                return (React.createElement("div", { key: index, className: 'bg-white/20 backdrop-blur-lg rounded-xl p-4 border border-white/30 shadow-lg' },
                                    React.createElement("div", { className: 'flex items-center gap-2 mb-2' },
                                        React.createElement("div", { className: 'w-6 h-6 bg-white/40 backdrop-blur-sm rounded-full flex items-center justify-center' },
                                            React.createElement("span", { className: 'text-xs' }, "\uD83D\uDDE1\uFE0F")),
                                        React.createElement("h3", { className: 'text-lg font-bold text-gray-800' },
                                            "\u3010",
                                            item.type,
                                            "\u3011",
                                            item.name,
                                            "(",
                                            qualities[item.pinji],
                                            ")(",
                                            lockStatus[item.islockd],
                                            ")")),
                                    React.createElement("div", { className: 'space-y-2 text-sm' },
                                        React.createElement("div", { className: 'grid grid-cols-2 gap-2' },
                                            React.createElement("div", { className: 'flex items-center gap-1' },
                                                React.createElement("span", { className: 'text-gray-600' }, "\u5C5E\u6027:"),
                                                React.createElement("span", { className: 'font-bold text-gray-800' }, stats.attribute)),
                                            React.createElement("div", { className: 'flex items-center gap-1' },
                                                React.createElement("span", { className: 'text-gray-600' }, "\u653B\u51FB:"),
                                                React.createElement("span", { className: 'font-bold text-gray-800' }, stats.atk)),
                                            React.createElement("div", { className: 'flex items-center gap-1' },
                                                React.createElement("span", { className: 'text-gray-600' }, "\u9632\u5FA1:"),
                                                React.createElement("span", { className: 'font-bold text-gray-800' }, stats.def)),
                                            React.createElement("div", { className: 'flex items-center gap-1' },
                                                React.createElement("span", { className: 'text-gray-600' }, "\u8840\u91CF:"),
                                                React.createElement("span", { className: 'font-bold text-gray-800' }, stats.HP))),
                                        React.createElement("div", { className: 'flex items-center gap-1' },
                                            React.createElement("span", { className: 'text-gray-600' }, "\u66B4\u51FB:"),
                                            React.createElement("span", { className: 'font-bold text-gray-800' },
                                                (item.bao * 100).toFixed(0),
                                                "%")),
                                        React.createElement("div", { className: 'flex items-center gap-2' },
                                            React.createElement("span", { className: 'text-gray-600' }, "\u6570\u91CF\uFF1A"),
                                            React.createElement("span", { className: 'font-bold text-gray-800' }, item.数量)),
                                        React.createElement("div", { className: 'flex items-center gap-2' },
                                            React.createElement("span", { className: 'text-gray-600' }, "\u51FA\u552E\u4EF7\uFF1A"),
                                            React.createElement("span", { className: 'font-bold text-gray-800' },
                                                item.出售价,
                                                "\u7075\u77F3")),
                                        React.createElement("div", { className: 'flex items-center gap-2' },
                                            React.createElement("span", { className: 'text-gray-600' }, "\u4EE3\u53F7\uFF1A"),
                                            React.createElement("span", { className: 'font-bold text-gray-800' }, index + 101)))));
                            }))))),
                    najie.丹药?.length > 0 && (React.createElement("div", { className: 'relative' },
                        React.createElement("div", { className: 'absolute inset-0 bg-white/15 rounded-3xl blur-2xl' }),
                        React.createElement("div", { className: 'absolute inset-0 bg-white/10 rounded-3xl blur-xl' }),
                        React.createElement("div", { className: 'relative backdrop-blur-xl bg-white/25 rounded-3xl border border-white/40 p-6 shadow-2xl' },
                            React.createElement("div", { className: 'flex items-center gap-3 mb-6' },
                                React.createElement("div", { className: 'w-10 h-10 bg-white/40 backdrop-blur-sm rounded-lg flex items-center justify-center' },
                                    React.createElement("span", { className: 'text-lg' }, "\uD83E\uDDEA")),
                                React.createElement("h2", { className: 'text-2xl font-bold text-gray-700' }, "\u3010\u4E39\u836F\u3011")),
                            React.createElement("div", { className: 'grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4' }, najie.丹药.map((item, index) => (React.createElement("div", { key: index, className: 'bg-white/20 backdrop-blur-lg rounded-xl p-4 border border-white/30 shadow-lg' },
                                React.createElement("div", { className: 'flex items-center gap-2 mb-2' },
                                    React.createElement("div", { className: 'w-6 h-6 bg-white/40 backdrop-blur-sm rounded-full flex items-center justify-center' },
                                        React.createElement("span", { className: 'text-xs' }, "\uD83D\uDC8A")),
                                    React.createElement("h3", { className: 'text-lg font-bold text-gray-800' },
                                        item.name,
                                        "(",
                                        lockStatus[item.islockd],
                                        ")")),
                                React.createElement("div", { className: 'space-y-2 text-sm' },
                                    item.HPp > 0 && (React.createElement("div", { className: 'flex items-center gap-1' },
                                        React.createElement("span", { className: 'text-gray-600' }, "\u6062\u590D\u767E\u5206\u6BD4:"),
                                        React.createElement("span", { className: 'font-bold text-gray-800' },
                                            item.HPp * 100,
                                            "%"))),
                                    item.exp > 0 && (React.createElement("div", { className: 'flex items-center gap-1' },
                                        React.createElement("span", { className: 'text-gray-600' }, "\u589E\u52A0\u4FEE\u4E3A:"),
                                        React.createElement("span", { className: 'font-bold text-gray-800' }, item.exp))),
                                    item.xingyun > 0 && (React.createElement("div", { className: 'flex items-center gap-1' },
                                        React.createElement("span", { className: 'text-gray-600' }, "\u5E78\u8FD0\u503C:"),
                                        React.createElement("span", { className: 'font-bold text-gray-800' },
                                            (item.xingyun * 100).toFixed(1),
                                            "%"))),
                                    React.createElement("div", { className: 'flex items-center gap-2' },
                                        React.createElement("span", { className: 'text-gray-600' }, "\u6570\u91CF\uFF1A"),
                                        React.createElement("span", { className: 'font-bold text-gray-800' }, item.数量)),
                                    React.createElement("div", { className: 'flex items-center gap-2' },
                                        React.createElement("span", { className: 'text-gray-600' }, "\u51FA\u552E\u4EF7\uFF1A"),
                                        React.createElement("span", { className: 'font-bold text-gray-800' },
                                            item.出售价,
                                            "\u7075\u77F3")),
                                    React.createElement("div", { className: 'flex items-center gap-2' },
                                        React.createElement("span", { className: 'text-gray-600' }, "\u4EE3\u53F7\uFF1A"),
                                        React.createElement("span", { className: 'font-bold text-gray-800' }, index + 201)))))))))),
                    najie.草药?.length > 0 && (React.createElement("div", { className: 'relative' },
                        React.createElement("div", { className: 'absolute inset-0 bg-white/15 rounded-3xl blur-2xl' }),
                        React.createElement("div", { className: 'absolute inset-0 bg-white/10 rounded-3xl blur-xl' }),
                        React.createElement("div", { className: 'relative backdrop-blur-xl bg-white/25 rounded-3xl border border-white/40 p-6 shadow-2xl' },
                            React.createElement("div", { className: 'flex items-center gap-3 mb-6' },
                                React.createElement("div", { className: 'w-10 h-10 bg-white/40 backdrop-blur-sm rounded-lg flex items-center justify-center' },
                                    React.createElement("span", { className: 'text-lg' }, "\uD83C\uDF3F")),
                                React.createElement("h2", { className: 'text-2xl font-bold text-gray-700' }, "\u3010\u8349\u836F\u3011")),
                            React.createElement("div", { className: 'grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4' }, najie.草药.map((item, index) => (React.createElement("div", { key: index, className: 'bg-white/20 backdrop-blur-lg rounded-xl p-4 border border-white/30 shadow-lg' },
                                React.createElement("div", { className: 'flex items-center gap-2 mb-2' },
                                    React.createElement("div", { className: 'w-6 h-6 bg-white/40 backdrop-blur-sm rounded-full flex items-center justify-center' },
                                        React.createElement("span", { className: 'text-xs' }, "\uD83C\uDF31")),
                                    React.createElement("h3", { className: 'text-lg font-bold text-gray-800' },
                                        item.name,
                                        "(",
                                        lockStatus[item.islockd],
                                        ")")),
                                React.createElement("div", { className: 'space-y-2 text-sm' },
                                    React.createElement("div", { className: 'text-gray-700' },
                                        "\u529F\u80FD\uFF1A",
                                        item.type),
                                    React.createElement("div", { className: 'text-gray-700' },
                                        "\u4ECB\u7ECD\uFF1A",
                                        item.desc),
                                    React.createElement("div", { className: 'flex items-center gap-2' },
                                        React.createElement("span", { className: 'text-gray-600' }, "\u6570\u91CF\uFF1A"),
                                        React.createElement("span", { className: 'font-bold text-gray-800' }, item.数量)),
                                    React.createElement("div", { className: 'flex items-center gap-2' },
                                        React.createElement("span", { className: 'text-gray-600' }, "\u51FA\u552E\u4EF7\uFF1A"),
                                        React.createElement("span", { className: 'font-bold text-gray-800' },
                                            item.出售价,
                                            "\u7075\u77F3")),
                                    React.createElement("div", { className: 'flex items-center gap-2' },
                                        React.createElement("span", { className: 'text-gray-600' }, "\u4EE3\u53F7\uFF1A"),
                                        React.createElement("span", { className: 'font-bold text-gray-800' }, index + 301)))))))))),
                    najie.材料?.length > 0 && (React.createElement("div", { className: 'relative' },
                        React.createElement("div", { className: 'absolute inset-0 bg-white/15 rounded-3xl blur-2xl' }),
                        React.createElement("div", { className: 'absolute inset-0 bg-white/10 rounded-3xl blur-xl' }),
                        React.createElement("div", { className: 'relative backdrop-blur-xl bg-white/25 rounded-3xl border border-white/40 p-6 shadow-2xl' },
                            React.createElement("div", { className: 'flex items-center gap-3 mb-6' },
                                React.createElement("div", { className: 'w-10 h-10 bg-white/40 backdrop-blur-sm rounded-lg flex items-center justify-center' },
                                    React.createElement("span", { className: 'text-lg' }, "\uD83D\uDD27")),
                                React.createElement("h2", { className: 'text-2xl font-bold text-gray-700' }, "\u3010\u6750\u6599\u3011")),
                            React.createElement("div", { className: 'grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4' }, najie.材料.map((item, index) => (React.createElement("div", { key: index, className: 'bg-white/20 backdrop-blur-lg rounded-xl p-4 border border-white/30 shadow-lg' },
                                React.createElement("div", { className: 'flex items-center gap-2 mb-2' },
                                    React.createElement("div", { className: 'w-6 h-6 bg-white/40 backdrop-blur-sm rounded-full flex items-center justify-center' },
                                        React.createElement("span", { className: 'text-xs' }, "\u2692\uFE0F")),
                                    React.createElement("h3", { className: 'text-lg font-bold text-gray-800' },
                                        item.name,
                                        "(",
                                        lockStatus[item.islockd],
                                        ")")),
                                React.createElement("div", { className: 'space-y-2 text-sm' },
                                    React.createElement("div", { className: 'text-gray-700' },
                                        "\u529F\u80FD\uFF1A",
                                        item.type),
                                    React.createElement("div", { className: 'text-gray-700' },
                                        "\u4ECB\u7ECD\uFF1A",
                                        item.desc),
                                    React.createElement("div", { className: 'flex items-center gap-2' },
                                        React.createElement("span", { className: 'text-gray-600' }, "\u6570\u91CF\uFF1A"),
                                        React.createElement("span", { className: 'font-bold text-gray-800' }, item.数量)),
                                    React.createElement("div", { className: 'flex items-center gap-2' },
                                        React.createElement("span", { className: 'text-gray-600' }, "\u51FA\u552E\u4EF7\uFF1A"),
                                        React.createElement("span", { className: 'font-bold text-gray-800' },
                                            item.出售价,
                                            "\u7075\u77F3")))))))))),
                    najie.仙宠?.length > 0 && (React.createElement("div", { className: 'relative' },
                        React.createElement("div", { className: 'absolute inset-0 bg-white/15 rounded-3xl blur-2xl' }),
                        React.createElement("div", { className: 'absolute inset-0 bg-white/10 rounded-3xl blur-xl' }),
                        React.createElement("div", { className: 'relative backdrop-blur-xl bg-white/25 rounded-3xl border border-white/40 p-6 shadow-2xl' },
                            React.createElement("div", { className: 'flex items-center gap-3 mb-6' },
                                React.createElement("div", { className: 'w-10 h-10 bg-white/40 backdrop-blur-sm rounded-lg flex items-center justify-center' },
                                    React.createElement("span", { className: 'text-lg' }, "\uD83D\uDC09")),
                                React.createElement("h2", { className: 'text-2xl font-bold text-gray-700' }, "\u3010\u4ED9\u5BA0\u3011")),
                            React.createElement("div", { className: 'grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4' }, najie.仙宠.map((item, index) => (React.createElement("div", { key: index, className: 'bg-white/20 backdrop-blur-lg rounded-xl p-4 border border-white/30 shadow-lg' },
                                React.createElement("div", { className: 'flex items-center gap-2 mb-2' },
                                    React.createElement("div", { className: 'w-6 h-6 bg-white/40 backdrop-blur-sm rounded-full flex items-center justify-center' },
                                        React.createElement("span", { className: 'text-xs' }, "\uD83D\uDC3E")),
                                    React.createElement("h3", { className: 'text-lg font-bold text-gray-800' },
                                        item.name,
                                        "(",
                                        lockStatus[item.islockd],
                                        ")")),
                                React.createElement("div", { className: 'space-y-2 text-sm' },
                                    React.createElement("div", { className: 'text-gray-700' },
                                        "\u529F\u80FD\uFF1A",
                                        item.type),
                                    React.createElement("div", { className: 'text-gray-700' },
                                        "\u4ECB\u7ECD\uFF1A",
                                        item.desc),
                                    React.createElement("div", { className: 'flex items-center gap-2' },
                                        React.createElement("span", { className: 'text-gray-600' }, "\u6570\u91CF\uFF1A"),
                                        React.createElement("span", { className: 'font-bold text-gray-800' }, item.数量)),
                                    React.createElement("div", { className: 'flex items-center gap-2' },
                                        React.createElement("span", { className: 'text-gray-600' }, "\u51FA\u552E\u4EF7\uFF1A"),
                                        React.createElement("span", { className: 'font-bold text-gray-800' },
                                            item.出售价,
                                            "\u7075\u77F3")),
                                    React.createElement("div", { className: 'flex items-center gap-2' },
                                        React.createElement("span", { className: 'text-gray-600' }, "\u54C1\u7EA7\uFF1A"),
                                        React.createElement("span", { className: 'font-bold text-gray-800' }, item.品级)))))))))),
                    najie.仙宠口粮?.length > 0 && (React.createElement("div", { className: 'relative' },
                        React.createElement("div", { className: 'absolute inset-0 bg-white/15 rounded-3xl blur-2xl' }),
                        React.createElement("div", { className: 'absolute inset-0 bg-white/10 rounded-3xl blur-xl' }),
                        React.createElement("div", { className: 'relative backdrop-blur-xl bg-white/25 rounded-3xl border border-white/40 p-6 shadow-2xl' },
                            React.createElement("div", { className: 'flex items-center gap-3 mb-6' },
                                React.createElement("div", { className: 'w-10 h-10 bg-white/40 backdrop-blur-sm rounded-lg flex items-center justify-center' },
                                    React.createElement("span", { className: 'text-lg' }, "\uD83E\uDD58")),
                                React.createElement("h2", { className: 'text-2xl font-bold text-gray-700' }, "\u3010\u4ED9\u5BA0\u53E3\u7CAE\u3011")),
                            React.createElement("div", { className: 'grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4' }, najie.仙宠口粮.map((item, index) => (React.createElement("div", { key: index, className: 'bg-white/20 backdrop-blur-lg rounded-xl p-4 border border-white/30 shadow-lg' },
                                React.createElement("div", { className: 'flex items-center gap-2 mb-2' },
                                    React.createElement("div", { className: 'w-6 h-6 bg-white/40 backdrop-blur-sm rounded-full flex items-center justify-center' },
                                        React.createElement("span", { className: 'text-xs' }, "\uD83E\uDD58")),
                                    React.createElement("h3", { className: 'text-lg font-bold text-gray-800' },
                                        item.name,
                                        "(",
                                        lockStatus[item.islockd],
                                        ")")),
                                React.createElement("div", { className: 'space-y-2 text-sm' },
                                    React.createElement("div", { className: 'flex items-center gap-2' },
                                        React.createElement("span", { className: 'text-gray-600' }, "\u6570\u91CF\uFF1A"),
                                        React.createElement("span", { className: 'font-bold text-gray-800' }, item.数量)),
                                    React.createElement("div", { className: 'flex items-center gap-2' },
                                        React.createElement("span", { className: 'text-gray-600' }, "\u51FA\u552E\u4EF7\uFF1A"),
                                        React.createElement("span", { className: 'font-bold text-gray-800' },
                                            item.出售价,
                                            "\u7075\u77F3"))))))))))),
                React.createElement("div", { className: 'text-center mt-12' },
                    React.createElement("div", { className: 'inline-block px-6 py-3 bg-white/20 backdrop-blur-lg rounded-full border border-white/30 shadow-lg' },
                        React.createElement("span", { className: 'text-gray-700 text-sm font-medium' }, "\uD83D\uDC8E \u7EB3\u6212\u7A7A\u95F4\u65E0\u9650\uFF0C\u4FEE\u4ED9\u8DEF\u4E0A\u76F8\u4F34 \uD83D\uDC8E")))))));
};

export { Najie as default };
