import React from 'react';
import fileUrl from '../img/player.jpg.js';
import fileUrl$1 from '../img/player_footer.png.js';
import HTML from './HTML.js';
import { Avatar } from './Avatar.js';
import { getAvatar } from '../../model/utils/utilsx.js';
import { BackgroundImage } from 'jsxp';

const Najie = ({ user_id, player = {}, strand_hp = {}, najie = {}, strand_lingshi = {} }) => {
    const qualities = ['劣', '普', '优', '精', '极', '绝', '顶'];
    const lockStatus = ['未锁定', '已锁定'];
    const elements = ['金', '木', '土', '水', '火'];
    const renderEquipmentStats = item => {
        const isAbsolute = item.atk > 10 || item.def > 10 || item.HP > 10;
        return {
            attribute: isAbsolute ? '无' : elements[item.id - 1],
            atk: isAbsolute ? item.atk.toFixed(0) : (item.atk * 100).toFixed(0) + '%',
            def: isAbsolute ? item.def.toFixed(0) : (item.def * 100).toFixed(0) + '%',
            HP: isAbsolute ? item.HP.toFixed(0) : (item.HP * 100).toFixed(0) + '%'
        };
    };
    const ItemCard = ({ title, icon, children }) => (React.createElement("div", { className: 'bg-[hsla(42,71%,91%,.502)] backdrop-blur-sm rounded-lg p-3 border border-white/20 shadow-lg' },
        React.createElement("div", { className: 'flex items-center gap-2 mb-3' },
            React.createElement("div", { className: 'w-6 h-6 bg-white/40 backdrop-blur-sm rounded-lg flex items-center justify-center' },
                React.createElement("span", { className: 'text-sm' }, icon)),
            React.createElement("h3", { className: 'text-base font-bold text-gray-900 drop-shadow-sm' }, title)),
        children));
    return (React.createElement(HTML, null,
        React.createElement(BackgroundImage, { src: [fileUrl, fileUrl$1], style: {
                backgroundRepeat: 'no-repeat, repeat',
                backgroundSize: '100%, auto'
            }, className: 'p-0 m-0 w-full text-center' },
            React.createElement("div", { className: 'h-3' }),
            React.createElement("div", null,
                React.createElement("div", { className: 'm-3 mx-auto flex flex-nowrap rounded-3xl z-999 bg-[radial-gradient(at_top_left,#ffffff10,#d7edea10)] border-t border-[#ffcc80] border-l border-[#ffcc80] border-r border-[#bb8020] border-b border-[#bb8020] backdrop-blur-sm w-[780px] pb-4' },
                    React.createElement("div", { className: 'text-center mt-5 ml-4 w-80' },
                        React.createElement("div", { className: 'flex justify-center' },
                            React.createElement(Avatar, { src: getAvatar(user_id), rootClassName: 'w-64 h-64', className: 'w-44 h-44' })),
                        React.createElement("div", { className: 'mt-3 mx-2 relative' },
                            React.createElement("div", { className: 'bg-gradient-to-r from-purple-400 to-purple-600 rounded-xl px-3 py-2 shadow-xl border-2 border-purple-300 backdrop-blur-sm' },
                                React.createElement("div", { className: 'flex items-center gap-2' },
                                    React.createElement("div", { className: 'w-6 h-6 bg-white/20 rounded-full flex items-center justify-center' },
                                        React.createElement("span", { className: 'text-white text-sm' }, "\uD83D\uDC8E")),
                                    React.createElement("div", { className: 'text-center' },
                                        React.createElement("div", { className: 'text-white text-xs font-semibold opacity-90 drop-shadow-sm' }, "\u7EB3\u6212"),
                                        React.createElement("div", { className: 'text-white text-lg font-bold drop-shadow-lg' },
                                            "Lv.",
                                            najie.等级 || 0))),
                                React.createElement("div", { className: 'absolute -top-1 -right-1 w-3 h-3 bg-purple-300 rounded-full opacity-60 animate-pulse' }),
                                React.createElement("div", { className: 'absolute -bottom-1 -left-1 w-2 h-2 bg-purple-400 rounded-full opacity-40' })))),
                    React.createElement("div", { className: 'float-right text-left mr-4 mt-4 rounded-3xl flex-1 text-slate-600' },
                        React.createElement("div", { className: 'space-y-2' },
                            React.createElement("div", { className: 'flex items-center gap-2 bg-[hsla(42,71%,91%,.502)] backdrop-blur-sm rounded-lg p-2 border border-white/20' },
                                React.createElement("span", { className: 'text-base' }, "\uD83D\uDC64"),
                                React.createElement("span", { className: 'text-base font-semibold text-gray-900 drop-shadow-sm' },
                                    "\u9053\u53F7\uFF1A",
                                    player.名号 || '无名')),
                            React.createElement("div", { className: 'flex items-center gap-2 bg-[hsla(42,71%,91%,.502)] backdrop-blur-sm rounded-lg p-2 border border-white/20' },
                                React.createElement("span", { className: 'text-base' }, "\uD83D\uDCAC"),
                                React.createElement("span", { className: 'text-base font-semibold text-gray-900 drop-shadow-sm' },
                                    "\u8D26\u53F7\uFF1A",
                                    user_id)),
                            React.createElement("div", { className: 'bg-[hsla(42,71%,91%,.502)] backdrop-blur-sm rounded-lg p-2 border border-white/20' },
                                React.createElement("div", { className: 'flex items-center gap-2 mb-2' },
                                    React.createElement("span", { className: 'text-base' }, "\u2764\uFE0F"),
                                    React.createElement("span", { className: 'text-base font-semibold text-gray-900 drop-shadow-sm' }, "\u751F\u547D")),
                                React.createElement("div", { className: 'relative w-64 text-white h-8 bg-gradient-to-r from-gray-800 to-gray-700 rounded-lg shadow-lg overflow-hidden border border-gray-600/50' },
                                    React.createElement("div", { className: 'absolute inset-0 bg-gradient-to-r from-transparent via-white/5 to-transparent' }),
                                    React.createElement("div", { className: 'h-full bg-gradient-to-r from-red-400 via-red-500 to-red-600 rounded-lg transition-all duration-300 ease-out shadow-lg relative overflow-hidden', style: strand_hp.style },
                                        React.createElement("div", { className: 'absolute inset-0 bg-gradient-to-r from-transparent via-white/20 to-transparent' }),
                                        React.createElement("div", { className: 'absolute top-0 left-0 w-full h-0.5 bg-gradient-to-r from-transparent via-white/30 to-transparent' }),
                                        React.createElement("div", { className: 'absolute bottom-0 left-0 w-full h-0.5 bg-gradient-to-r from-transparent via-black/20 to-transparent' })),
                                    React.createElement("div", { className: 'absolute inset-0 flex items-center justify-center' },
                                        React.createElement("span", { className: 'font-bold text-sm drop-shadow-lg' },
                                            player.当前血量 || 0,
                                            "/",
                                            player.血量上限 || 0)))),
                            React.createElement("div", { className: 'bg-[hsla(42,71%,91%,.502)] backdrop-blur-sm rounded-lg p-2 border border-white/20' },
                                React.createElement("div", { className: 'flex items-center gap-2 mb-2' },
                                    React.createElement("span", { className: 'text-base' }, "\uD83D\uDCB0"),
                                    React.createElement("span", { className: 'text-base font-semibold text-gray-900 drop-shadow-sm' }, "\u7075\u77F3\u50A8\u91CF")),
                                React.createElement("div", { className: 'relative w-64 text-white h-8 bg-gradient-to-r from-gray-800 to-gray-700 rounded-lg shadow-lg overflow-hidden border border-gray-600/50' },
                                    React.createElement("div", { className: 'absolute inset-0 bg-gradient-to-r from-transparent via-white/5 to-transparent' }),
                                    React.createElement("div", { className: 'h-full bg-gradient-to-r from-blue-400 via-blue-500 to-blue-600 rounded-lg transition-all duration-300 ease-out shadow-lg relative overflow-hidden', style: strand_lingshi.style },
                                        React.createElement("div", { className: 'absolute inset-0 bg-gradient-to-r from-transparent via-white/20 to-transparent' }),
                                        React.createElement("div", { className: 'absolute top-0 left-0 w-full h-0.5 bg-gradient-to-r from-transparent via-white/30 to-transparent' }),
                                        React.createElement("div", { className: 'absolute bottom-0 left-0 w-full h-0.5 bg-gradient-to-r from-transparent via-black/20 to-transparent' })),
                                    React.createElement("div", { className: 'absolute inset-0 flex items-center justify-center' },
                                        React.createElement("span", { className: 'font-bold text-sm drop-shadow-lg' },
                                            najie.灵石 || 0,
                                            "/",
                                            najie.灵石上限 || 0))))))),
                najie.道具 && najie.道具.length > 0 && (React.createElement("div", { className: 'm-3 mx-auto flex flex-nowrap rounded-3xl z-999 bg-[radial-gradient(at_top_left,#ffffff10,#d7edea10)] border-t border-[#ffcc80] border-l border-[#ffcc80] border-r border-[#bb8020] border-b border-[#bb8020] backdrop-blur-sm w-[780px]' },
                    React.createElement("div", { className: 'm-4 w-[780px]' },
                        React.createElement("div", { className: 'flex items-center gap-3 mb-3' },
                            React.createElement("div", { className: 'w-6 h-6 bg-white/40 backdrop-blur-sm rounded-lg flex items-center justify-center' },
                                React.createElement("span", { className: 'text-sm' }, "\uD83C\uDF92")),
                            React.createElement("h2", { className: 'text-xl font-bold text-gray-900 drop-shadow-sm' }, "\u3010\u9053\u5177\u3011")),
                        React.createElement("div", { className: 'grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-3' }, najie.道具.map((item, index) => (React.createElement(ItemCard, { key: index, title: `【${item.type}】${item.name}`, icon: '\uD83D\uDCE6' },
                            React.createElement("div", { className: 'space-y-1.5 text-sm' },
                                React.createElement("div", { className: 'text-gray-700 ' }, item.desc),
                                React.createElement("div", { className: 'flex items-center justify-between' },
                                    React.createElement("span", { className: 'font-semibold text-gray-800' }, "\u6570\u91CF"),
                                    React.createElement("span", { className: 'font-bold text-gray-900 text-base' }, item.数量)),
                                React.createElement("div", { className: 'flex items-center justify-between' },
                                    React.createElement("span", { className: 'font-semibold text-gray-800' }, "\u51FA\u552E\u4EF7"),
                                    React.createElement("span", { className: 'font-bold text-gray-900 text-base' },
                                        item.出售价,
                                        "\u7075\u77F3")),
                                React.createElement("div", { className: 'flex items-center justify-between' },
                                    React.createElement("span", { className: 'font-semibold text-gray-800' }, "\u4EE3\u53F7"),
                                    React.createElement("span", { className: 'font-bold text-gray-900 text-base' }, index + 101)))))))))),
                najie.装备 && najie.装备.length > 0 && (React.createElement("div", { className: 'm-3 mx-auto flex flex-nowrap rounded-3xl z-999 bg-[radial-gradient(at_top_left,#ffffff10,#d7edea10)] border-t border-[#ffcc80] border-l border-[#ffcc80] border-r border-[#bb8020] border-b border-[#bb8020] backdrop-blur-sm w-[780px]' },
                    React.createElement("div", { className: 'm-4 w-[780px]' },
                        React.createElement("div", { className: 'flex items-center gap-3 mb-3' },
                            React.createElement("div", { className: 'w-6 h-6 bg-white/40 backdrop-blur-sm rounded-lg flex items-center justify-center' },
                                React.createElement("span", { className: 'text-sm' }, "\u2694\uFE0F")),
                            React.createElement("h2", { className: 'text-xl font-bold text-gray-900 drop-shadow-sm' }, "\u3010\u88C5\u5907\u3011")),
                        React.createElement("div", { className: 'grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-3' }, najie.装备.map((item, index) => {
                            const stats = renderEquipmentStats(item);
                            return (React.createElement(ItemCard, { key: index, title: `【${item.type}】${item.name}(${qualities[item.pinji]})(${lockStatus[item.islockd]})`, icon: '\uD83D\uDDE1\uFE0F' },
                                React.createElement("div", { className: 'space-y-1.5 text-sm' },
                                    React.createElement("div", { className: 'grid grid-cols-2 gap-2' },
                                        React.createElement("div", { className: 'flex items-center justify-between' },
                                            React.createElement("span", { className: 'font-semibold text-gray-800' }, "\u5C5E\u6027"),
                                            React.createElement("span", { className: 'font-bold text-gray-900 text-base' }, stats.attribute)),
                                        React.createElement("div", { className: 'flex items-center justify-between' },
                                            React.createElement("span", { className: 'font-semibold text-gray-800' }, "\u653B\u51FB"),
                                            React.createElement("span", { className: 'font-bold text-gray-900 text-base' }, stats.atk)),
                                        React.createElement("div", { className: 'flex items-center justify-between' },
                                            React.createElement("span", { className: 'font-semibold text-gray-800' }, "\u9632\u5FA1"),
                                            React.createElement("span", { className: 'font-bold text-gray-900 text-base' }, stats.def)),
                                        React.createElement("div", { className: 'flex items-center justify-between' },
                                            React.createElement("span", { className: 'font-semibold text-gray-800' }, "\u8840\u91CF"),
                                            React.createElement("span", { className: 'font-bold text-gray-900 text-base' }, stats.HP))),
                                    React.createElement("div", { className: 'flex items-center justify-between' },
                                        React.createElement("span", { className: 'font-semibold text-gray-800' }, "\u66B4\u51FB"),
                                        React.createElement("span", { className: 'font-bold text-gray-900 text-base' },
                                            (item.bao * 100).toFixed(0),
                                            "%")),
                                    React.createElement("div", { className: 'flex items-center justify-between' },
                                        React.createElement("span", { className: 'font-semibold text-gray-800' }, "\u6570\u91CF"),
                                        React.createElement("span", { className: 'font-bold text-gray-900 text-base' }, item.数量)),
                                    React.createElement("div", { className: 'flex items-center justify-between' },
                                        React.createElement("span", { className: 'font-semibold text-gray-800' }, "\u51FA\u552E\u4EF7"),
                                        React.createElement("span", { className: 'font-bold text-gray-900 text-base' },
                                            item.出售价,
                                            "\u7075\u77F3")),
                                    React.createElement("div", { className: 'flex items-center justify-between' },
                                        React.createElement("span", { className: 'font-semibold text-gray-800' }, "\u4EE3\u53F7"),
                                        React.createElement("span", { className: 'font-bold text-gray-900 text-base' }, index + 101)))));
                        }))))),
                najie.丹药 && najie.丹药.length > 0 && (React.createElement("div", { className: 'm-3 mx-auto flex flex-nowrap rounded-3xl z-999 bg-[radial-gradient(at_top_left,#ffffff10,#d7edea10)] border-t border-[#ffcc80] border-l border-[#ffcc80] border-r border-[#bb8020] border-b border-[#bb8020] backdrop-blur-sm w-[780px]' },
                    React.createElement("div", { className: 'm-4 w-[780px]' },
                        React.createElement("div", { className: 'flex items-center gap-3 mb-3' },
                            React.createElement("div", { className: 'w-6 h-6 bg-white/40 backdrop-blur-sm rounded-lg flex items-center justify-center' },
                                React.createElement("span", { className: 'text-sm' }, "\uD83E\uDDEA")),
                            React.createElement("h2", { className: 'text-xl font-bold text-gray-900 drop-shadow-sm' }, "\u3010\u4E39\u836F\u3011")),
                        React.createElement("div", { className: 'grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-3' }, najie.丹药.map((item, index) => (React.createElement(ItemCard, { key: index, title: `${item.name}(${lockStatus[item.islockd]})`, icon: '\uD83D\uDC8A' },
                            React.createElement("div", { className: 'space-y-1.5 text-sm' },
                                item.HPp > 0 && (React.createElement("div", { className: 'flex items-center justify-between' },
                                    React.createElement("span", { className: 'font-semibold text-gray-800' }, "\u6062\u590D\u767E\u5206\u6BD4"),
                                    React.createElement("span", { className: 'font-bold text-gray-900 text-base' },
                                        item.HPp * 100,
                                        "%"))),
                                item.exp > 0 && (React.createElement("div", { className: 'flex items-center justify-between' },
                                    React.createElement("span", { className: 'font-semibold text-gray-800' }, "\u589E\u52A0\u4FEE\u4E3A"),
                                    React.createElement("span", { className: 'font-bold text-gray-900 text-base' }, item.exp))),
                                item.xingyun > 0 && (React.createElement("div", { className: 'flex items-center justify-between' },
                                    React.createElement("span", { className: 'font-semibold text-gray-800' }, "\u5E78\u8FD0\u503C"),
                                    React.createElement("span", { className: 'font-bold text-gray-900 text-base' },
                                        (item.xingyun * 100).toFixed(1),
                                        "%"))),
                                React.createElement("div", { className: 'flex items-center justify-between' },
                                    React.createElement("span", { className: 'font-semibold text-gray-800' }, "\u6570\u91CF"),
                                    React.createElement("span", { className: 'font-bold text-gray-900 text-base' }, item.数量)),
                                React.createElement("div", { className: 'flex items-center justify-between' },
                                    React.createElement("span", { className: 'font-semibold text-gray-800' }, "\u51FA\u552E\u4EF7"),
                                    React.createElement("span", { className: 'font-bold text-gray-900 text-base' },
                                        item.出售价,
                                        "\u7075\u77F3")),
                                React.createElement("div", { className: 'flex items-center justify-between' },
                                    React.createElement("span", { className: 'font-semibold text-gray-800' }, "\u4EE3\u53F7"),
                                    React.createElement("span", { className: 'font-bold text-gray-900 text-base' }, index + 201)))))))))),
                najie.草药?.length > 0 && (React.createElement("div", { className: 'm-3 mx-auto flex flex-nowrap rounded-3xl z-999 bg-[radial-gradient(at_top_left,#ffffff10,#d7edea10)] border-t border-[#ffcc80] border-l border-[#ffcc80] border-r border-[#bb8020] border-b border-[#bb8020] backdrop-blur-sm w-[780px]' },
                    React.createElement("div", { className: 'm-4 w-[780px]' },
                        React.createElement("div", { className: 'flex items-center gap-3 mb-3' },
                            React.createElement("div", { className: 'w-6 h-6 bg-white/40 backdrop-blur-sm rounded-lg flex items-center justify-center' },
                                React.createElement("span", { className: 'text-sm' }, "\uD83C\uDF3F")),
                            React.createElement("h2", { className: 'text-xl font-bold text-gray-900 drop-shadow-sm' }, "\u3010\u8349\u836F\u3011")),
                        React.createElement("div", { className: 'grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-3' }, najie.草药.map((item, index) => (React.createElement(ItemCard, { key: index, title: `${item.name}(${lockStatus[item.islockd]})`, icon: '\uD83C\uDF31' },
                            React.createElement("div", { className: 'space-y-1.5 text-sm' },
                                React.createElement("div", { className: 'text-gray-700 ' }, item.type),
                                React.createElement("div", { className: 'text-gray-700 ' }, item.desc),
                                React.createElement("div", { className: 'flex items-center justify-between' },
                                    React.createElement("span", { className: 'font-semibold text-gray-800' }, "\u6570\u91CF"),
                                    React.createElement("span", { className: 'font-bold text-gray-900 text-base' }, item.数量)),
                                React.createElement("div", { className: 'flex items-center justify-between' },
                                    React.createElement("span", { className: 'font-semibold text-gray-800' }, "\u51FA\u552E\u4EF7"),
                                    React.createElement("span", { className: 'font-bold text-gray-900 text-base' },
                                        item.出售价,
                                        "\u7075\u77F3")),
                                React.createElement("div", { className: 'flex items-center justify-between' },
                                    React.createElement("span", { className: 'font-semibold text-gray-800' }, "\u4EE3\u53F7"),
                                    React.createElement("span", { className: 'font-bold text-gray-900 text-base' }, index + 301)))))))))),
                najie.材料?.length > 0 && (React.createElement("div", { className: 'm-3 mx-auto flex flex-nowrap rounded-3xl z-999 bg-[radial-gradient(at_top_left,#ffffff10,#d7edea10)] border-t border-[#ffcc80] border-l border-[#ffcc80] border-r border-[#bb8020] border-b border-[#bb8020] backdrop-blur-sm w-[780px]' },
                    React.createElement("div", { className: 'm-4 w-[780px]' },
                        React.createElement("div", { className: 'flex items-center gap-3 mb-3' },
                            React.createElement("div", { className: 'w-6 h-6 bg-white/40 backdrop-blur-sm rounded-lg flex items-center justify-center' },
                                React.createElement("span", { className: 'text-sm' }, "\uD83D\uDD27")),
                            React.createElement("h2", { className: 'text-xl font-bold text-gray-900 drop-shadow-sm' }, "\u3010\u6750\u6599\u3011")),
                        React.createElement("div", { className: 'grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-3' }, najie.材料.map((item, index) => (React.createElement(ItemCard, { key: index, title: `${item.name}(${lockStatus[item.islockd]})`, icon: '\u2692\uFE0F' },
                            React.createElement("div", { className: 'space-y-1.5 text-sm' },
                                React.createElement("div", { className: 'text-gray-700 ' }, item.type),
                                React.createElement("div", { className: 'text-gray-700 ' }, item.desc),
                                React.createElement("div", { className: 'flex items-center justify-between' },
                                    React.createElement("span", { className: 'font-semibold text-gray-800' }, "\u6570\u91CF"),
                                    React.createElement("span", { className: 'font-bold text-gray-900 text-base' }, item.数量)),
                                React.createElement("div", { className: 'flex items-center justify-between' },
                                    React.createElement("span", { className: 'font-semibold text-gray-800' }, "\u51FA\u552E\u4EF7"),
                                    React.createElement("span", { className: 'font-bold text-gray-900 text-base' },
                                        item.出售价,
                                        "\u7075\u77F3")))))))))),
                najie.仙宠?.length > 0 && (React.createElement("div", { className: 'm-3 mx-auto flex flex-nowrap rounded-3xl z-999 bg-[radial-gradient(at_top_left,#ffffff10,#d7edea10)] border-t border-[#ffcc80] border-l border-[#ffcc80] border-r border-[#bb8020] border-b border-[#bb8020] backdrop-blur-sm w-[780px]' },
                    React.createElement("div", { className: 'm-4 w-[780px]' },
                        React.createElement("div", { className: 'flex items-center gap-3 mb-3' },
                            React.createElement("div", { className: 'w-6 h-6 bg-white/40 backdrop-blur-sm rounded-lg flex items-center justify-center' },
                                React.createElement("span", { className: 'text-sm' }, "\uD83D\uDC09")),
                            React.createElement("h2", { className: 'text-xl font-bold text-gray-900 drop-shadow-sm' }, "\u3010\u4ED9\u5BA0\u3011")),
                        React.createElement("div", { className: 'grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-3' }, najie.仙宠.map((item, index) => (React.createElement(ItemCard, { key: index, title: `${item.name}(${lockStatus[item.islockd]})`, icon: '\uD83D\uDC3E' },
                            React.createElement("div", { className: 'space-y-1.5 text-sm' },
                                React.createElement("div", { className: 'text-gray-700 ' }, item.type),
                                React.createElement("div", { className: 'text-gray-700 ' }, item.desc),
                                React.createElement("div", { className: 'flex items-center justify-between' },
                                    React.createElement("span", { className: 'font-semibold text-gray-800' }, "\u6570\u91CF"),
                                    React.createElement("span", { className: 'font-bold text-gray-900 text-base' }, item.数量)),
                                React.createElement("div", { className: 'flex items-center justify-between' },
                                    React.createElement("span", { className: 'font-semibold text-gray-800' }, "\u51FA\u552E\u4EF7"),
                                    React.createElement("span", { className: 'font-bold text-gray-900 text-base' },
                                        item.出售价,
                                        "\u7075\u77F3")),
                                React.createElement("div", { className: 'flex items-center justify-between' },
                                    React.createElement("span", { className: 'font-semibold text-gray-800' }, "\u54C1\u7EA7"),
                                    React.createElement("span", { className: 'font-bold text-gray-900 text-base' }, item.品级)))))))))),
                najie.仙宠口粮?.length > 0 && (React.createElement("div", { className: 'm-3 mx-auto flex flex-nowrap rounded-3xl z-999 bg-[radial-gradient(at_top_left,#ffffff10,#d7edea10)] border-t border-[#ffcc80] border-l border-[#ffcc80] border-r border-[#bb8020] border-b border-[#bb8020] backdrop-blur-sm w-[780px]' },
                    React.createElement("div", { className: 'm-4 w-[780px]' },
                        React.createElement("div", { className: 'flex items-center gap-3 mb-3' },
                            React.createElement("div", { className: 'w-6 h-6 bg-white/40 backdrop-blur-sm rounded-lg flex items-center justify-center' },
                                React.createElement("span", { className: 'text-sm' }, "\uD83E\uDD58")),
                            React.createElement("h2", { className: 'text-xl font-bold text-gray-900 drop-shadow-sm' }, "\u3010\u4ED9\u5BA0\u53E3\u7CAE\u3011")),
                        React.createElement("div", { className: 'grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-3' }, najie.仙宠口粮.map((item, index) => (React.createElement(ItemCard, { key: index, title: `${item.name}(${lockStatus[item.islockd]})`, icon: '\uD83E\uDD58' },
                            React.createElement("div", { className: 'space-y-1.5 text-sm' },
                                React.createElement("div", { className: 'flex items-center justify-between' },
                                    React.createElement("span", { className: 'font-semibold text-gray-800' }, "\u6570\u91CF"),
                                    React.createElement("span", { className: 'font-bold text-gray-900 text-base' }, item.数量)),
                                React.createElement("div", { className: 'flex items-center justify-between' },
                                    React.createElement("span", { className: 'font-semibold text-gray-800' }, "\u51FA\u552E\u4EF7"),
                                    React.createElement("span", { className: 'font-bold text-gray-900 text-base' },
                                        item.出售价,
                                        "\u7075\u77F3"))))))))))),
            React.createElement("div", { className: 'h-3' }))));
};

export { Najie as default };
