import React from 'react';
import HTML from './HTML.js';
import { Avatar } from './Avatar.js';

const PlayerCopy = ({ user_id, nickname, player_nowHP, player_maxHP, levelMax, xueqi, need_xueqi, lingshi, association, learned_gongfa = [] }) => {
    return (React.createElement(HTML, { className: "p-0 m-0 w-full text-center" },
        React.createElement("div", { className: " w-full max-w-4xl mx-auto" },
            React.createElement("div", { className: "inset-0 bg-gradient-to-br from-green-400/20 via-yellow-300/15 to-red-400/20 rounded-[2rem] blur-3xl scale-110" }),
            React.createElement("div", { className: " z-10 w-full bg-gradient-to-br from-green-100/90 via-yellow-50/95 to-red-100/90 backdrop-blur-3xl rounded-[2rem] shadow-[0_20px_60px_0_rgba(46,204,64,0.3),0_0_100px_0_rgba(255,215,0,0.2)] p-6 sm:p-8 mt-8 border border-green-300/60" },
                React.createElement("div", { className: "relative inset-0 pointer-events-none z-0" },
                    React.createElement("svg", { width: "100%", height: "100%", viewBox: "0 0 800 600", fill: "none", xmlns: "http://www.w3.org/2000/svg" },
                        React.createElement("rect", { x: "20", y: "20", width: "760", height: "560", rx: "40", fill: "none", stroke: "url(#borderGradient)", strokeWidth: "3", strokeDasharray: "20 10" }),
                        React.createElement("rect", { x: "30", y: "30", width: "740", height: "540", rx: "35", fill: "none", stroke: "url(#innerBorder)", strokeWidth: "1", strokeDasharray: "5 5" }),
                        React.createElement("path", { d: "M 40 40 L 80 40 L 80 80 L 40 80 Z", fill: "url(#cornerGradient)", stroke: "#2ecc40", strokeWidth: "2" }),
                        React.createElement("path", { d: "M 720 40 L 760 40 L 760 80 L 720 80 Z", fill: "url(#cornerGradient)", stroke: "#2ecc40", strokeWidth: "2" }),
                        React.createElement("path", { d: "M 40 520 L 80 520 L 80 560 L 40 560 Z", fill: "url(#cornerGradient)", stroke: "#2ecc40", strokeWidth: "2" }),
                        React.createElement("path", { d: "M 720 520 L 760 520 L 760 560 L 720 560 Z", fill: "url(#cornerGradient)", stroke: "#2ecc40", strokeWidth: "2" }),
                        React.createElement("path", { d: "M 100 80 Q 150 60 200 80 T 300 80", stroke: "#2ecc40", strokeWidth: "2", fill: "none", opacity: "0.6" }),
                        React.createElement("path", { d: "M 500 80 Q 550 60 600 80 T 700 80", stroke: "#2ecc40", strokeWidth: "2", fill: "none", opacity: "0.6" }),
                        React.createElement("path", { d: "M 100 520 Q 150 540 200 520 T 300 520", stroke: "#ff4e50", strokeWidth: "2", fill: "none", opacity: "0.6" }),
                        React.createElement("path", { d: "M 500 520 Q 550 540 600 520 T 700 520", stroke: "#ff4e50", strokeWidth: "2", fill: "none", opacity: "0.6" }),
                        React.createElement("circle", { cx: "150", cy: "120", r: "8", fill: "#2ecc40", opacity: "0.3" }),
                        React.createElement("circle", { cx: "650", cy: "480", r: "6", fill: "#ff4e50", opacity: "0.3" }),
                        React.createElement("circle", { cx: "200", cy: "450", r: "10", fill: "#ffd700", opacity: "0.2" }),
                        React.createElement("defs", null,
                            React.createElement("linearGradient", { id: "borderGradient", x1: "0%", y1: "0%", x2: "100%", y2: "100%" },
                                React.createElement("stop", { offset: "0%", stopColor: "#2ecc40", stopOpacity: "0.8" }),
                                React.createElement("stop", { offset: "50%", stopColor: "#ffd700", stopOpacity: "0.6" }),
                                React.createElement("stop", { offset: "100%", stopColor: "#ff4e50", stopOpacity: "0.8" })),
                            React.createElement("linearGradient", { id: "innerBorder", x1: "0%", y1: "0%", x2: "100%", y2: "100%" },
                                React.createElement("stop", { offset: "0%", stopColor: "#2ecc40", stopOpacity: "0.4" }),
                                React.createElement("stop", { offset: "100%", stopColor: "#ff4e50", stopOpacity: "0.4" })),
                            React.createElement("linearGradient", { id: "cornerGradient", x1: "0%", y1: "0%", x2: "100%", y2: "100%" },
                                React.createElement("stop", { offset: "0%", stopColor: "#2ecc40", stopOpacity: "0.3" }),
                                React.createElement("stop", { offset: "100%", stopColor: "#ffd700", stopOpacity: "0.3" })))),
                    React.createElement("div", { className: "absolute top-0 w-full " },
                        React.createElement("div", { className: "relative z-10 mb-6 sm:mb-8" },
                            React.createElement("div", { className: "text-2xl sm:text-4xl font-black text-transparent bg-clip-text bg-gradient-to-r from-green-600 via-yellow-600 to-red-600 mb-2 tracking-widest drop-shadow-lg" }, "\u2727 \u4FEE\u4ED9\u8005\u6863\u6848 \u2727"),
                            React.createElement("div", { className: "w-24 sm:w-32 h-1 bg-gradient-to-r from-green-400 via-yellow-400 to-red-400 mx-auto rounded-full shadow-lg" })),
                        React.createElement("div", { className: "flex flex-col items-center gap-6 sm:gap-8 mb-8 sm:mb-10 relative z-10" },
                            React.createElement("div", { className: "relative" },
                                React.createElement("div", { className: "inset-0 bg-gradient-to-r from-green-400 via-yellow-400 to-red-400 rounded-full p-1 shadow-2xl" },
                                    React.createElement(Avatar, { src: `https://q1.qlogo.cn/g?b=qq&s=0&nk=${user_id}`, rootClassName: "w-32 sm:w-40 h-32 sm:h-40 rounded-full ring-4 ring-white/80", className: "w-24 sm:w-32 h-24 sm:h-32 rounded-full" })),
                                React.createElement("div", { className: "text-sm text-gray-600" },
                                    "QQ: ",
                                    user_id)),
                            React.createElement("div", { className: "w-full max-w-2xl" },
                                React.createElement("div", { className: "bg-gradient-to-r from-green-200/90 via-yellow-100/90 to-red-200/90 backdrop-blur-sm px-4 sm:px-8 py-4 sm:py-6 rounded-2xl shadow-2xl border border-green-300/60 relative overflow-hidden" },
                                    React.createElement("div", { className: "absolute inset-0 bg-gradient-to-br from-green-300/20 to-red-300/20" }),
                                    React.createElement("div", { className: "relative z-10 text-center" },
                                        React.createElement("div", { className: "text-xl sm:text-3xl font-black text-green-800 tracking-wider mb-2 sm:mb-3 drop-shadow-lg" },
                                            "\uD83C\uDFEE \u9053\u53F7\uFF1A",
                                            nickname,
                                            " \uD83C\uDFEE"),
                                        React.createElement("div", { className: "text-lg sm:text-xl text-green-700 font-bold tracking-wide" },
                                            "\u2694\uFE0F \u4F53\u5883\uFF1A",
                                            levelMax,
                                            " \u2694\uFE0F"))))))),
                React.createElement("div", { className: "grid grid-cols-1 sm:grid-cols-2 gap-4 sm:gap-6 mb-8 sm:mb-10 relative z-10" },
                    React.createElement("div", { className: "bg-gradient-to-br from-red-200/90 via-red-100/90 to-red-300/90 backdrop-blur-sm rounded-2xl p-4 sm:p-6 shadow-2xl border border-red-300/60 relative overflow-hidden" },
                        React.createElement("div", { className: "absolute inset-0 bg-gradient-to-br from-red-400/10 to-red-600/10" }),
                        React.createElement("div", { className: "relative z-10" },
                            React.createElement("div", { className: "flex items-center gap-2 mb-3" },
                                React.createElement("span", { className: "text-xl sm:text-2xl" }, "\u2764\uFE0F"),
                                React.createElement("div", { className: "font-black text-lg sm:text-xl text-red-800 tracking-wide" }, "\u8840\u91CF")),
                            React.createElement("div", { className: "text-2xl sm:text-3xl font-black text-red-900 tracking-wider" },
                                player_nowHP,
                                " / ",
                                player_maxHP),
                            React.createElement("div", { className: "mt-3 bg-red-200/50 rounded-full h-2 sm:h-3 overflow-hidden border border-red-300/50" },
                                React.createElement("div", { className: "bg-gradient-to-r from-red-400 to-red-600 h-full rounded-full shadow-inner", style: { width: `${(player_nowHP / player_maxHP) * 100}%` } })))),
                    React.createElement("div", { className: "bg-gradient-to-br from-blue-200/90 via-blue-100/90 to-blue-300/90 backdrop-blur-sm rounded-2xl p-4 sm:p-6 shadow-2xl border border-blue-300/60 relative overflow-hidden" },
                        React.createElement("div", { className: "absolute inset-0 bg-gradient-to-br from-blue-400/10 to-blue-600/10" }),
                        React.createElement("div", { className: "relative z-10" },
                            React.createElement("div", { className: "flex items-center gap-2 mb-3" },
                                React.createElement("span", { className: "text-xl sm:text-2xl" }, "\uD83D\uDC99"),
                                React.createElement("div", { className: "font-black text-lg sm:text-xl text-blue-800 tracking-wide" }, "\u6C14\u8840")),
                            React.createElement("div", { className: "text-2xl sm:text-3xl font-black text-blue-900 tracking-wider" },
                                xueqi,
                                " / ",
                                need_xueqi),
                            React.createElement("div", { className: "mt-3 bg-blue-200/50 rounded-full h-2 sm:h-3 overflow-hidden border border-blue-300/50" },
                                React.createElement("div", { className: "bg-gradient-to-r from-blue-400 to-blue-600 h-full rounded-full shadow-inner", style: { width: `${(xueqi / need_xueqi) * 100}%` } })))),
                    React.createElement("div", { className: "bg-gradient-to-br from-yellow-200/90 via-yellow-100/90 to-yellow-300/90 backdrop-blur-sm rounded-2xl p-4 sm:p-6 shadow-2xl border border-yellow-300/60 relative overflow-hidden" },
                        React.createElement("div", { className: "absolute inset-0 bg-gradient-to-br from-yellow-400/10 to-yellow-600/10" }),
                        React.createElement("div", { className: "relative z-10" },
                            React.createElement("div", { className: "flex items-center gap-2 mb-3" },
                                React.createElement("span", { className: "text-xl sm:text-2xl" }, "\uD83D\uDCB0"),
                                React.createElement("div", { className: "font-black text-lg sm:text-xl text-yellow-800 tracking-wide" }, "\u7075\u77F3")),
                            React.createElement("div", { className: "text-2xl sm:text-3xl font-black text-yellow-900 tracking-wider" }, lingshi),
                            React.createElement("div", { className: "text-sm text-yellow-700 mt-2 font-semibold" }, "\u4FEE\u70BC\u8D44\u6E90"))),
                    React.createElement("div", { className: "bg-gradient-to-br from-purple-200/90 via-purple-100/90 to-purple-300/90 backdrop-blur-sm rounded-2xl p-4 sm:p-6 shadow-2xl border border-purple-300/60 relative overflow-hidden" },
                        React.createElement("div", { className: "absolute inset-0 bg-gradient-to-br from-purple-400/10 to-purple-600/10" }),
                        React.createElement("div", { className: "relative z-10" },
                            React.createElement("div", { className: "flex items-center gap-2 mb-3" },
                                React.createElement("span", { className: "text-xl sm:text-2xl" }, "\uD83C\uDFDB\uFE0F"),
                                React.createElement("div", { className: "font-black text-lg sm:text-xl text-purple-800 tracking-wide" }, "\u5B97\u95E8")),
                            React.createElement("div", { className: "text-xl sm:text-2xl font-black text-purple-900 tracking-wider mb-1" }, association?.宗门名称 || '无'),
                            React.createElement("div", { className: "text-sm text-purple-700 font-semibold" }, association?.职位 || '散修')))),
                React.createElement("div", { className: "relative z-10" },
                    React.createElement("div", { className: "text-2xl sm:text-3xl font-black text-transparent bg-clip-text bg-gradient-to-r from-green-600 via-yellow-600 to-red-600 mb-4 sm:mb-6 tracking-wider drop-shadow-lg flex items-center justify-center gap-3 sm:gap-4" },
                        React.createElement("span", { className: "text-xl sm:text-2xl" }, "\uD83D\uDCDA"),
                        "\u3010\u5DF2\u5B66\u529F\u6CD5\u3011",
                        React.createElement("span", { className: "text-xl sm:text-2xl" }, "\uD83D\uDCDA")),
                    React.createElement("div", { className: "bg-gradient-to-br from-green-100/90 via-yellow-50/90 to-red-100/90 backdrop-blur-sm rounded-2xl p-4 sm:p-6 shadow-2xl border border-green-300/60 relative overflow-hidden" },
                        React.createElement("div", { className: "absolute inset-0 bg-gradient-to-br from-green-300/10 to-red-300/10" }),
                        React.createElement("div", { className: "relative z-10" }, !learned_gongfa || learned_gongfa.length === 0 ? (React.createElement("div", { className: "flex items-center justify-center gap-3 py-6 sm:py-8" },
                            React.createElement("span", { className: "text-xl sm:text-2xl" }, "\uD83D\uDCD6"),
                            React.createElement("span", { className: "text-lg sm:text-xl font-bold text-green-700 tracking-wide opacity-70" }, "\u6682\u65E0\u529F\u6CD5"),
                            React.createElement("span", { className: "text-xl sm:text-2xl" }, "\uD83D\uDCD6"))) : (React.createElement("div", { className: "flex flex-wrap gap-3 sm:gap-4 justify-center" }, learned_gongfa.map((item, index) => (React.createElement("div", { key: index, className: "px-4 sm:px-6 py-2 sm:py-3 bg-gradient-to-r from-green-400/90 via-yellow-300/90 to-red-400/90 text-green-900 rounded-full shadow-xl font-black border-2 border-green-300/60 text-base sm:text-lg tracking-wide relative overflow-hidden", style: { textShadow: '0 2px 8px rgba(46,204,64,0.3)' } },
                            React.createElement("div", { className: "absolute inset-0 bg-gradient-to-r from-white/20 to-transparent" }),
                            React.createElement("span", { className: "relative z-10" },
                                "\u300A",
                                item,
                                "\u300B"))))))))),
                React.createElement("div", { className: "mt-6 sm:mt-8 flex justify-center" },
                    React.createElement("div", { className: "w-20 sm:w-24 h-1 bg-gradient-to-r from-green-400 via-yellow-400 to-red-400 rounded-full shadow-lg" }))))));
};

export { PlayerCopy as default };
