import React from 'react';
import HTML from './HTML.js';
import fileUrl from '../img/fairyrealm.jpg.js';

const SecretPlace = ({ didian_list }) => {
    return (React.createElement(HTML, null,
        React.createElement("div", { className: 'min-h-screen relative overflow-hidden', style: {
                backgroundImage: `url(${fileUrl})`,
                backgroundPosition: 'center'
            } },
            React.createElement("div", { className: 'absolute inset-0 opacity-20' },
                React.createElement("div", { className: 'absolute top-10 left-10 w-32 h-32 border border-blue-400 rounded-full' }),
                React.createElement("div", { className: 'absolute top-32 right-20 w-24 h-24 border border-cyan-400 rounded-full' }),
                React.createElement("div", { className: 'absolute bottom-20 left-1/4 w-16 h-16 border border-indigo-400 rounded-full' }),
                React.createElement("div", { className: 'absolute bottom-40 right-1/3 w-20 h-20 border border-blue-400 rounded-full' })),
            React.createElement("div", { className: 'relative z-10 container mx-auto px-4 py-8' },
                React.createElement("div", { className: 'text-center mb-8' },
                    React.createElement("div", { className: 'inline-block relative' },
                        React.createElement("div", { className: 'absolute inset-0 bg-gradient-to-r from-blue-600 to-cyan-600 rounded-2xl blur-lg opacity-30' }),
                        React.createElement("div", { className: 'relative bg-gradient-to-r from-blue-600 to-cyan-600 rounded-2xl px-8 py-4 border border-blue-400/30 backdrop-blur-sm' },
                            React.createElement("h1", { className: 'text-3xl font-bold text-white tracking-wider' }, "\uD83C\uDFD4\uFE0F \u79D8\u5883 \uD83C\uDFD4\uFE0F"))),
                    React.createElement("div", { className: 'mt-4 text-blue-700 text-sm font-medium' }, "\uD83C\uDF1F \u4FEE\u4ED9\u754C\u795E\u79D8\u79D8\u5883\uFF0C\u673A\u7F18\u4E0E\u6311\u6218\u5E76\u5B58 \uD83C\uDF1F")),
                React.createElement("div", { className: 'max-w-6xl mx-auto' },
                    React.createElement("div", { className: 'relative' },
                        React.createElement("div", { className: 'absolute inset-0 bg-gradient-to-r from-blue-500/10 to-cyan-500/10 rounded-3xl blur-xl' }),
                        React.createElement("div", { className: 'relative backdrop-blur-sm bg-white/80 rounded-3xl border border-blue-400/30 p-8 shadow-xl' },
                            React.createElement("div", { className: 'text-center mb-8' },
                                React.createElement("div", { className: 'grid grid-cols-1 md:grid-cols-2 gap-4 mb-6' },
                                    React.createElement("div", { className: 'bg-gradient-to-r from-blue-500/20 to-cyan-500/20 rounded-xl p-3 border border-blue-400/30 backdrop-blur-sm' },
                                        React.createElement("div", { className: 'text-sm text-blue-700 font-medium' }, "\u964D\u4E34\u6307\u4EE4"),
                                        React.createElement("div", { className: 'text-xs text-gray-600' }, "#\u964D\u4E34\u79D8\u5883+\u79D8\u5883\u540D")),
                                    React.createElement("div", { className: 'bg-gradient-to-r from-cyan-500/20 to-blue-500/20 rounded-xl p-3 border border-cyan-400/30 backdrop-blur-sm' },
                                        React.createElement("div", { className: 'text-sm text-cyan-700 font-medium' }, "\u7B5B\u9009\u6307\u4EE4"),
                                        React.createElement("div", { className: 'text-xs text-gray-600' }, "#\u79D8\u5883+\u7C7B\u578B\uFF08\u88C5\u5907/\u4E39\u836F/\u8349\u836F/\u529F\u6CD5\uFF09")))),
                            React.createElement("div", { className: 'grid grid-cols-1 lg:grid-cols-2 gap-6' }, didian_list?.map((item, index) => (React.createElement("div", { key: index, className: 'relative group' },
                                React.createElement("div", { className: 'absolute inset-0 bg-gradient-to-br from-blue-400/10 to-cyan-600/10 rounded-2xl blur-sm' }),
                                React.createElement("div", { className: 'relative backdrop-blur-md  rounded-2xl border border-blue-400/40 p-6 shadow-lg' },
                                    React.createElement("div", { className: 'flex items-center justify-between mb-4' },
                                        React.createElement("div", { className: 'flex items-center gap-3' },
                                            React.createElement("div", { className: 'w-10 h-10 bg-gradient-to-br from-blue-400 to-cyan-600 rounded-lg flex items-center justify-center border border-blue-300/50 shadow-md' },
                                                React.createElement("span", { className: 'text-sm' },
                                                    item.Grade === '初级' && '🌱',
                                                    item.Grade === '中级' && '🌿',
                                                    item.Grade === '高级' && '🌳',
                                                    item.Grade === '顶级' && '🌲',
                                                    item.Grade === '传说' && '🌟',
                                                    item.Grade === '神话' && '💎',
                                                    !['初级', '中级', '高级', '顶级', '传说', '神话'].includes(item.Grade) && '🏔️')),
                                            React.createElement("div", null,
                                                React.createElement("h3", { className: 'text-lg font-bold text-blue-800' },
                                                    "\u3010",
                                                    item.Grade,
                                                    "\u3011",
                                                    item.name),
                                                React.createElement("span", { className: 'text-xs text-gray-500' },
                                                    item.Grade,
                                                    "\u79D8\u5883"))),
                                        React.createElement("div", { className: 'text-right' },
                                            React.createElement("div", { className: 'text-lg font-bold text-green-600' }, item.Price),
                                            React.createElement("div", { className: 'text-xs text-green-500' }, "\u7075\u77F3"))),
                                    React.createElement("div", { className: 'space-y-4' },
                                        item.one && item.one.length > 0 && (React.createElement("div", { className: 'bg-gradient-to-r from-blue-500/10 to-blue-600/10 rounded-xl p-4 border border-blue-400/20' },
                                            React.createElement("div", { className: 'flex items-center gap-2 mb-2' },
                                                React.createElement("div", { className: 'w-6 h-6 bg-gradient-to-br from-blue-400 to-blue-600 rounded-full flex items-center justify-center' },
                                                    React.createElement("span", { className: 'text-xs' }, "\uD83C\uDF31")),
                                                React.createElement("span", { className: 'text-sm font-medium text-blue-700' }, "\u4F4E\u7EA7\u5956\u52B1")),
                                            React.createElement("div", { className: 'flex flex-wrap gap-2' }, item.one.map((thing, idx) => (React.createElement("span", { key: idx, className: 'inline-block bg-blue-200 text-blue-900 rounded-lg px-3 py-1 text-xs font-semibold border border-blue-300/50' }, thing.name)))))),
                                        item.two && item.two.length > 0 && (React.createElement("div", { className: 'bg-gradient-to-r from-green-500/10 to-emerald-600/10 rounded-xl p-4 border border-green-400/20' },
                                            React.createElement("div", { className: 'flex items-center gap-2 mb-2' },
                                                React.createElement("div", { className: 'w-6 h-6 bg-gradient-to-br from-green-400 to-green-600 rounded-full flex items-center justify-center' },
                                                    React.createElement("span", { className: 'text-xs' }, "\uD83C\uDF3F")),
                                                React.createElement("span", { className: 'text-sm font-medium text-green-700' }, "\u4E2D\u7EA7\u5956\u52B1")),
                                            React.createElement("div", { className: 'flex flex-wrap gap-2' }, item.two.map((thing, idx) => (React.createElement("span", { key: idx, className: 'inline-block bg-green-200 text-green-900 rounded-lg px-3 py-1 text-xs font-semibold border border-green-300/50' }, thing.name)))))),
                                        item.three && item.three.length > 0 && (React.createElement("div", { className: 'bg-gradient-to-r from-yellow-500/10 to-orange-600/10 rounded-xl p-4 border border-yellow-400/20' },
                                            React.createElement("div", { className: 'flex items-center gap-2 mb-2' },
                                                React.createElement("div", { className: 'w-6 h-6 bg-gradient-to-br from-yellow-400 to-yellow-600 rounded-full flex items-center justify-center' },
                                                    React.createElement("span", { className: 'text-xs' }, "\uD83C\uDF33")),
                                                React.createElement("span", { className: 'text-sm font-medium text-yellow-700' }, "\u9AD8\u7EA7\u5956\u52B1")),
                                            React.createElement("div", { className: 'flex flex-wrap gap-2' }, item.three.map((thing, idx) => (React.createElement("span", { key: idx, className: 'inline-block bg-yellow-200 text-yellow-900 rounded-lg px-3 py-1 text-xs font-semibold border border-yellow-300/50' }, thing.name))))))),
                                    React.createElement("div", { className: 'mt-4 text-center' },
                                        React.createElement("div", { className: 'inline-block px-4 py-2 bg-gradient-to-r from-blue-500/20 to-cyan-500/20 rounded-full border border-blue-400/30 backdrop-blur-sm' },
                                            React.createElement("span", { className: 'text-blue-700 text-sm font-medium' },
                                                item.Grade === '初级' && '🌱 新手秘境，适合初学者',
                                                item.Grade === '中级' && '🌿 进阶秘境，挑战与机遇并存',
                                                item.Grade === '高级' && '🌳 高级秘境，强者云集',
                                                item.Grade === '顶级' && '🌲 顶级秘境，传说级奖励',
                                                item.Grade === '传说' && '🌟 传说秘境，神话级宝物',
                                                item.Grade === '神话' && '💎 神话秘境，至尊级机缘',
                                                !['初级', '中级', '高级', '顶级', '传说', '神话'].includes(item.Grade) && '🏔️ 神秘秘境，未知的挑战')))))))),
                            React.createElement("div", { className: 'mt-8 pt-6 border-t border-blue-400/20' },
                                React.createElement("div", { className: 'flex items-center justify-center gap-6' },
                                    React.createElement("div", { className: 'flex items-center gap-2' },
                                        React.createElement("div", { className: 'w-6 h-6 bg-gradient-to-br from-blue-400 to-blue-600 rounded-full flex items-center justify-center' },
                                            React.createElement("span", { className: 'text-xs' }, "\uD83D\uDCCA")),
                                        React.createElement("span", { className: 'text-sm text-blue-700 font-medium' },
                                            "\u5171 ",
                                            didian_list?.length || 0,
                                            " \u4E2A\u79D8\u5883")),
                                    React.createElement("div", { className: 'flex items-center gap-2' },
                                        React.createElement("div", { className: 'w-6 h-6 bg-gradient-to-br from-green-400 to-green-600 rounded-full flex items-center justify-center' },
                                            React.createElement("span", { className: 'text-xs' }, "\uD83D\uDC8E")),
                                        React.createElement("span", { className: 'text-sm text-green-700 font-medium' },
                                            "\u6700\u9AD8\u4EF7\u683C\uFF1A",
                                            Math.max(...(didian_list?.map(item => item.Price) || [0])),
                                            " \u7075\u77F3"))))))),
                React.createElement("div", { className: 'text-center mt-12' },
                    React.createElement("div", { className: 'inline-block px-6 py-3 bg-gradient-to-r from-blue-600/20 to-cyan-600/20 rounded-full border border-blue-400/30 backdrop-blur-sm' },
                        React.createElement("span", { className: 'text-blue-700 text-sm font-medium' }, "\uD83C\uDFD4\uFE0F \u79D8\u5883\u6DF1\u5904\u85CF\u673A\u7F18\uFF0C\u4FEE\u4ED9\u8DEF\u4E0A\u5BFB\u4ED9\u7F18 \uD83C\uDFD4\uFE0F")))))));
};

export { SecretPlace as default };
