import React from 'react';
import HTML from './HTML.js';

const Shenbing = ({ newwupin }) => {
    return (React.createElement(HTML, null,
        React.createElement("div", { className: "min-h-screen bg-gradient-to-br from-slate-900 via-red-900 to-slate-900 relative overflow-hidden" },
            React.createElement("div", { className: "absolute inset-0 opacity-10" },
                React.createElement("div", { className: "absolute top-10 left-10 w-32 h-32 border border-red-400 rounded-full" }),
                React.createElement("div", { className: "absolute top-32 right-20 w-24 h-24 border border-orange-400 rounded-full" }),
                React.createElement("div", { className: "absolute bottom-20 left-1/4 w-16 h-16 border border-yellow-400 rounded-full" }),
                React.createElement("div", { className: "absolute bottom-40 right-1/3 w-20 h-20 border border-amber-400 rounded-full" })),
            React.createElement("div", { className: "relative z-10 container mx-auto px-4 py-8" },
                React.createElement("div", { className: "text-center mb-8" },
                    React.createElement("div", { className: "inline-block relative" },
                        React.createElement("div", { className: "absolute inset-0 bg-gradient-to-r from-red-600 to-orange-600 rounded-2xl blur-lg opacity-50" }),
                        React.createElement("div", { className: "relative bg-gradient-to-r from-red-600 to-orange-600 rounded-2xl px-8 py-4 border border-red-400/30" },
                            React.createElement("h1", { className: "text-3xl font-bold text-white tracking-wider" }, "\u2694\uFE0F \u795E\u5175\u699C \u2694\uFE0F"))),
                    React.createElement("div", { className: "mt-4 text-red-200 text-sm" }, "\uD83D\uDD25 \u4FEE\u4ED9\u754C\u6700\u5F3A\u795E\u5175\u6392\u884C\u699C \uD83D\uDD25")),
                React.createElement("div", { className: "max-w-4xl mx-auto" },
                    React.createElement("div", { className: "relative" },
                        React.createElement("div", { className: "absolute inset-0 bg-gradient-to-r from-red-500/20 to-orange-500/20 rounded-3xl blur-xl" }),
                        React.createElement("div", { className: "relative backdrop-blur-sm bg-white/10 rounded-3xl border border-red-400/30 p-8" },
                            React.createElement("div", { className: "text-center mb-8" },
                                React.createElement("div", { className: "flex items-center justify-center gap-4 mb-4" },
                                    React.createElement("div", { className: "w-12 h-12 bg-gradient-to-br from-red-400 to-orange-600 rounded-xl flex items-center justify-center border border-red-300/50" },
                                        React.createElement("span", { className: "text-2xl" }, "\u2694\uFE0F")),
                                    React.createElement("h2", { className: "text-2xl font-bold text-red-300" }, "\u795E\u5175\u699C")),
                                React.createElement("div", { className: "text-sm text-gray-300" }, "\u4FEE\u4ED9\u754C\u6700\u5F3A\u795E\u5175\uFF0C\u6BCF\u4E00\u4EF6\u90FD\u662F\u4F20\u5947")),
                            React.createElement("div", { className: "space-y-6" }, newwupin?.map((item, index) => (React.createElement("div", { key: index, className: "relative group" },
                                React.createElement("div", { className: "absolute inset-0 bg-gradient-to-r from-red-400/20 to-orange-600/20 rounded-2xl blur-sm" }),
                                React.createElement("div", { className: "relative backdrop-blur-md bg-white/5 rounded-2xl border border-red-400/40 p-6" },
                                    React.createElement("div", { className: "flex items-center justify-between mb-6" },
                                        React.createElement("div", { className: "flex items-center gap-4" },
                                            React.createElement("div", { className: "relative" },
                                                React.createElement("div", { className: "absolute inset-0 bg-gradient-to-br from-red-400 to-orange-600 rounded-full blur-sm" }),
                                                React.createElement("div", { className: "relative w-16 h-16 bg-gradient-to-br from-red-400 to-orange-600 rounded-full flex items-center justify-center border-2 border-red-300/50" },
                                                    React.createElement("span", { className: "text-xl font-bold text-white" },
                                                        index === 0 && '🥇',
                                                        index === 1 && '🥈',
                                                        index === 2 && '🥉',
                                                        index >= 3 && `#${index + 1}`))),
                                            React.createElement("div", null,
                                                React.createElement("h3", { className: "text-2xl font-bold text-red-200 mb-1" }, item.name),
                                                React.createElement("span", { className: "text-sm text-gray-400" }, item.type))),
                                        React.createElement("div", { className: "text-right" },
                                            React.createElement("div", { className: "text-3xl font-bold text-yellow-300" }, item.评分),
                                            React.createElement("div", { className: "text-sm text-yellow-400" }, "\u7075\u97F5\u503C"))),
                                    React.createElement("div", { className: "grid grid-cols-1 md:grid-cols-2 gap-6" },
                                        React.createElement("div", { className: "bg-gradient-to-r from-blue-500/10 to-indigo-500/10 rounded-xl p-4 border border-blue-400/20" },
                                            React.createElement("div", { className: "flex items-center gap-2 mb-2" },
                                                React.createElement("div", { className: "w-6 h-6 bg-gradient-to-br from-blue-400 to-blue-600 rounded-full flex items-center justify-center" },
                                                    React.createElement("span", { className: "text-xs" }, "\uD83D\uDD28")),
                                                React.createElement("span", { className: "text-sm font-medium text-blue-200" }, "\u7F14\u9020\u8005")),
                                            React.createElement("div", { className: "flex items-center gap-2" },
                                                React.createElement("div", { className: "w-8 h-8 bg-gradient-to-br from-blue-400 to-indigo-600 rounded-full flex items-center justify-center" },
                                                    React.createElement("span", { className: "text-xs" }, "\uD83D\uDC68\u200D\uD83D\uDD27")),
                                                React.createElement("span", { className: "text-lg font-bold text-blue-100" }, item.制作者))),
                                        React.createElement("div", { className: "bg-gradient-to-r from-green-500/10 to-emerald-500/10 rounded-xl p-4 border border-green-400/20" },
                                            React.createElement("div", { className: "flex items-center gap-2 mb-2" },
                                                React.createElement("div", { className: "w-6 h-6 bg-gradient-to-br from-green-400 to-green-600 rounded-full flex items-center justify-center" },
                                                    React.createElement("span", { className: "text-xs" }, "\u2694\uFE0F")),
                                                React.createElement("span", { className: "text-sm font-medium text-green-200" }, "\u6301\u5175\u8005")),
                                            React.createElement("div", { className: "flex items-center gap-2" },
                                                React.createElement("div", { className: "w-8 h-8 bg-gradient-to-br from-green-400 to-emerald-600 rounded-full flex items-center justify-center" },
                                                    React.createElement("span", { className: "text-xs" }, "\uD83D\uDC64")),
                                                React.createElement("span", { className: "text-lg font-bold text-green-100" }, item.使用者)))),
                                    React.createElement("div", { className: "mt-6" },
                                        React.createElement("div", { className: "flex items-center gap-3 mb-2" },
                                            React.createElement("div", { className: "w-6 h-6 bg-gradient-to-br from-yellow-400 to-orange-600 rounded-full flex items-center justify-center" },
                                                React.createElement("span", { className: "text-xs" }, "\u2B50")),
                                            React.createElement("span", { className: "text-sm font-medium text-yellow-200" }, "\u795E\u5175\u7B49\u7EA7")),
                                        React.createElement("div", { className: "flex items-center gap-2" },
                                            React.createElement("div", { className: "flex-1 bg-gray-700/30 rounded-full h-3" },
                                                React.createElement("div", { className: "bg-gradient-to-r from-yellow-400 to-orange-600 h-3 rounded-full", style: {
                                                        width: `${Math.min((item.评分 / 100) * 100, 100)}%`
                                                    } })),
                                            React.createElement("span", { className: "text-xs text-gray-300" },
                                                Math.min((item.评分 / 100) * 100, 100).toFixed(0),
                                                "%"))),
                                    React.createElement("div", { className: "mt-4 text-center" },
                                        React.createElement("div", { className: "inline-block px-4 py-2 bg-gradient-to-r from-red-500/20 to-orange-500/20 rounded-full border border-red-400/30 backdrop-blur-sm" },
                                            React.createElement("span", { className: "text-red-200 text-sm font-medium" },
                                                index === 0 && '🏆 至尊神兵，威震修仙界',
                                                index === 1 && '🥈 绝世神兵，锋芒毕露',
                                                index === 2 && '🥉 传奇神兵，名震四方',
                                                index >= 3 &&
                                                    index < 10 &&
                                                    '⚔️ 顶级神兵，威力无穷',
                                                index >= 10 && '🗡️ 精品神兵，品质上乘')))))))),
                            React.createElement("div", { className: "mt-8 pt-6 border-t border-red-400/20" },
                                React.createElement("div", { className: "flex items-center justify-center gap-6" },
                                    React.createElement("div", { className: "flex items-center gap-2" },
                                        React.createElement("div", { className: "w-6 h-6 bg-gradient-to-br from-red-400 to-red-600 rounded-full flex items-center justify-center" },
                                            React.createElement("span", { className: "text-xs" }, "\uD83D\uDCCA")),
                                        React.createElement("span", { className: "text-sm text-red-200" },
                                            "\u5171 ",
                                            newwupin?.length || 0,
                                            " \u4EF6\u795E\u5175")),
                                    React.createElement("div", { className: "flex items-center gap-2" },
                                        React.createElement("div", { className: "w-6 h-6 bg-gradient-to-br from-yellow-400 to-orange-600 rounded-full flex items-center justify-center" },
                                            React.createElement("span", { className: "text-xs" }, "\uD83C\uDFC6")),
                                        React.createElement("span", { className: "text-sm text-yellow-200" },
                                            "\u6700\u9AD8\u7075\u97F5\u503C\uFF1A",
                                            newwupin?.[0]?.评分 || 0))))))),
                React.createElement("div", { className: "text-center mt-12" },
                    React.createElement("div", { className: "inline-block px-6 py-3 bg-gradient-to-r from-red-600/20 to-orange-600/20 rounded-full border border-red-400/30 backdrop-blur-sm" },
                        React.createElement("span", { className: "text-red-200 text-sm" }, "\u2694\uFE0F \u795E\u5175\u5728\u624B\uFF0C\u5929\u4E0B\u6211\u6709 \u2694\uFE0F")))))));
};

export { Shenbing as default };
