import React from 'react';
import HTML from './HTML.js';

const Statezhiye = ({ Level_list }) => {
    return (React.createElement(HTML, null,
        React.createElement("div", { className: "min-h-screen bg-gradient-to-br from-slate-900 via-violet-900 to-slate-900 relative overflow-hidden" },
            React.createElement("div", { className: "absolute inset-0 opacity-10" },
                React.createElement("div", { className: "absolute top-10 left-10 w-32 h-32 border border-violet-400 rounded-full" }),
                React.createElement("div", { className: "absolute top-32 right-20 w-24 h-24 border border-purple-400 rounded-full" }),
                React.createElement("div", { className: "absolute bottom-20 left-1/4 w-16 h-16 border border-indigo-400 rounded-full" }),
                React.createElement("div", { className: "absolute bottom-40 right-1/3 w-20 h-20 border border-pink-400 rounded-full" })),
            React.createElement("div", { className: "relative z-10 container mx-auto px-4 py-8" },
                React.createElement("div", { className: "text-center mb-12" },
                    React.createElement("div", { className: "inline-block relative" },
                        React.createElement("div", { className: "absolute inset-0 bg-gradient-to-r from-violet-600 to-purple-600 rounded-2xl blur-lg opacity-50" }),
                        React.createElement("div", { className: "relative bg-gradient-to-r from-violet-600 to-purple-600 rounded-2xl px-8 py-4 border border-violet-400/30" },
                            React.createElement("h1", { className: "text-3xl font-bold text-white tracking-wider" }, "\uD83C\uDFAF \u804C\u4E1A\u7B49\u7EA7\u56FE\u9274 \uD83C\uDFAF"))),
                    React.createElement("div", { className: "mt-4 text-violet-200 text-sm" }, "\u2B50 \u4FEE\u4ED9\u8DEF\u4E0A\uFF0C\u804C\u4E1A\u8FDB\u9636\u4E4B\u8DEF \u2B50")),
                React.createElement("div", { className: "max-w-4xl mx-auto" },
                    React.createElement("div", { className: "relative" },
                        React.createElement("div", { className: "absolute inset-0 bg-gradient-to-r from-violet-500/20 to-purple-500/20 rounded-3xl blur-xl" }),
                        React.createElement("div", { className: "relative backdrop-blur-sm bg-white/10 rounded-3xl border border-violet-400/30 p-8" },
                            React.createElement("div", { className: "text-center mb-8" },
                                React.createElement("div", { className: "flex items-center justify-center gap-4 mb-4" },
                                    React.createElement("div", { className: "w-12 h-12 bg-gradient-to-br from-violet-400 to-purple-600 rounded-xl flex items-center justify-center border border-violet-300/50" },
                                        React.createElement("span", { className: "text-2xl" }, "\uD83C\uDFAF")),
                                    React.createElement("h2", { className: "text-2xl font-bold text-violet-300" }, "\u804C\u4E1A\u7B49\u7EA7")),
                                React.createElement("div", { className: "text-sm text-gray-300" }, "\u4ECE\u521D\u5B66\u8005\u5230\u5927\u5E08\uFF0C\u6BCF\u4E00\u6B65\u90FD\u662F\u4FEE\u4ED9\u8DEF\u4E0A\u7684\u91CD\u8981\u91CC\u7A0B\u7891")),
                            React.createElement("div", { className: "grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6" }, Level_list?.map((item, index) => (React.createElement("div", { key: index, className: "relative group" },
                                React.createElement("div", { className: "absolute inset-0 bg-gradient-to-br from-violet-400/20 to-purple-600/20 rounded-2xl blur-sm" }),
                                React.createElement("div", { className: "relative backdrop-blur-md bg-white/5 rounded-2xl border border-violet-400/40 p-6" },
                                    React.createElement("div", { className: "flex items-center justify-between mb-4" },
                                        React.createElement("div", { className: "flex items-center gap-3" },
                                            React.createElement("div", { className: "w-10 h-10 bg-gradient-to-br from-violet-400 to-purple-600 rounded-lg flex items-center justify-center" },
                                                React.createElement("span", { className: "text-sm" },
                                                    index === 0 && '🌱',
                                                    index === 1 && '🌿',
                                                    index === 2 && '🌳',
                                                    index === 3 && '🌲',
                                                    index === 4 && '🌺',
                                                    index === 5 && '🌸',
                                                    index === 6 && '🌹',
                                                    index === 7 && '🌻',
                                                    index === 8 && '🌼',
                                                    index === 9 && '💐',
                                                    index >= 10 && '🏆')),
                                            React.createElement("div", null,
                                                React.createElement("h3", { className: "text-lg font-bold text-violet-200" },
                                                    "\u7B49\u7EA7 ",
                                                    item.name),
                                                React.createElement("span", { className: "text-xs text-gray-400" },
                                                    index === 0 && '初学者',
                                                    index === 1 && '学徒',
                                                    index === 2 && '熟练工',
                                                    index === 3 && '技师',
                                                    index === 4 && '专家',
                                                    index === 5 && '大师',
                                                    index === 6 && '宗师',
                                                    index === 7 && '传奇',
                                                    index === 8 && '神话',
                                                    index === 9 && '传说',
                                                    index >= 10 && '至尊'))),
                                        React.createElement("div", { className: "text-right" },
                                            React.createElement("div", { className: "text-lg font-bold text-yellow-300" },
                                                "#",
                                                index + 1),
                                            React.createElement("div", { className: "text-xs text-yellow-400" }, "\u7B49\u7EA7"))),
                                    React.createElement("div", { className: "bg-gradient-to-r from-violet-500/10 to-purple-500/10 rounded-xl p-4 border border-violet-400/20 mb-4" },
                                        React.createElement("div", { className: "flex items-center gap-2 mb-2" },
                                            React.createElement("div", { className: "w-6 h-6 bg-gradient-to-br from-violet-400 to-violet-600 rounded-full flex items-center justify-center" },
                                                React.createElement("span", { className: "text-xs" }, "\uD83D\uDCCA")),
                                            React.createElement("span", { className: "text-sm font-medium text-violet-200" }, "\u719F\u7EC3\u5EA6\u8981\u6C42")),
                                        React.createElement("div", { className: "flex items-center gap-2" },
                                            React.createElement("div", { className: "w-6 h-6 bg-gradient-to-br from-yellow-400 to-orange-600 rounded-full flex items-center justify-center" },
                                                React.createElement("span", { className: "text-xs" }, "\u2B50")),
                                            React.createElement("span", { className: "text-lg font-bold text-yellow-200" }, item.experience))),
                                    React.createElement("div", { className: "flex items-center gap-2" },
                                        React.createElement("div", { className: "flex-1 bg-gray-700/30 rounded-full h-2" },
                                            React.createElement("div", { className: "bg-gradient-to-r from-violet-400 to-purple-600 h-2 rounded-full", style: {
                                                    width: `${Math.min((index + 1) * 10, 100)}%`
                                                } })),
                                        React.createElement("span", { className: "text-xs text-gray-300" },
                                            Math.min((index + 1) * 10, 100),
                                            "%")),
                                    React.createElement("div", { className: "mt-4 text-center" },
                                        React.createElement("div", { className: "inline-block px-3 py-1 bg-gradient-to-r from-violet-500/20 to-purple-500/20 rounded-full border border-violet-400/30 backdrop-blur-sm" },
                                            React.createElement("span", { className: "text-violet-200 text-xs font-medium" },
                                                index === 0 && '初入修仙路',
                                                index === 1 && '掌握基础技能',
                                                index === 2 && '技艺日渐纯熟',
                                                index === 3 && '成为技术专家',
                                                index === 4 && '技艺炉火纯青',
                                                index === 5 && '达到大师境界',
                                                index === 6 && '技艺登峰造极',
                                                index === 7 && '成为传奇人物',
                                                index === 8 && '技艺超越凡俗',
                                                index === 9 && '达到传说境界',
                                                index >= 10 && '修仙界至尊')))))))),
                            React.createElement("div", { className: "mt-8 pt-6 border-t border-violet-400/20" },
                                React.createElement("div", { className: "flex items-center justify-center gap-6" },
                                    React.createElement("div", { className: "flex items-center gap-2" },
                                        React.createElement("div", { className: "w-6 h-6 bg-gradient-to-br from-violet-400 to-violet-600 rounded-full flex items-center justify-center" },
                                            React.createElement("span", { className: "text-xs" }, "\uD83D\uDCC8")),
                                        React.createElement("span", { className: "text-sm text-violet-200" },
                                            "\u5171 ",
                                            Level_list?.length || 0,
                                            " \u4E2A\u7B49\u7EA7")),
                                    React.createElement("div", { className: "flex items-center gap-2" },
                                        React.createElement("div", { className: "w-6 h-6 bg-gradient-to-br from-yellow-400 to-orange-600 rounded-full flex items-center justify-center" },
                                            React.createElement("span", { className: "text-xs" }, "\u2B50")),
                                        React.createElement("span", { className: "text-sm text-yellow-200" },
                                            "\u6700\u9AD8\u719F\u7EC3\u5EA6\uFF1A",
                                            Level_list?.[Level_list.length - 1]?.experience || 0))))))),
                React.createElement("div", { className: "text-center mt-12" },
                    React.createElement("div", { className: "inline-block px-6 py-3 bg-gradient-to-r from-violet-600/20 to-purple-600/20 rounded-full border border-violet-400/30 backdrop-blur-sm" },
                        React.createElement("span", { className: "text-violet-200 text-sm" }, "\uD83C\uDFAF \u4FEE\u4ED9\u8DEF\u4E0A\uFF0C\u804C\u4E1A\u7B49\u7EA7\u89C1\u8BC1\u6210\u957F \uD83C\uDFAF")))))));
};

export { Statezhiye as default };
