import React from 'react';
import HTML from './HTML.js';

const Supermarket = ({ Exchange_list }) => {
    return (React.createElement(HTML, null,
        React.createElement("div", { className: "min-h-screen bg-gradient-to-br from-slate-900 via-cyan-900 to-slate-900 relative overflow-hidden" },
            React.createElement("div", { className: "absolute inset-0 opacity-10" },
                React.createElement("div", { className: "absolute top-10 left-10 w-32 h-32 border border-cyan-400 rounded-full" }),
                React.createElement("div", { className: "absolute top-32 right-20 w-24 h-24 border border-blue-400 rounded-full" }),
                React.createElement("div", { className: "absolute bottom-20 left-1/4 w-16 h-16 border border-teal-400 rounded-full" }),
                React.createElement("div", { className: "absolute bottom-40 right-1/3 w-20 h-20 border border-indigo-400 rounded-full" })),
            React.createElement("div", { className: "relative z-10 container mx-auto px-4 py-8" },
                React.createElement("div", { className: "text-center mb-12" },
                    React.createElement("div", { className: "inline-block relative" },
                        React.createElement("div", { className: "absolute inset-0 bg-gradient-to-r from-cyan-600 to-blue-600 rounded-2xl blur-lg opacity-50" }),
                        React.createElement("div", { className: "relative bg-gradient-to-r from-cyan-600 to-blue-600 rounded-2xl px-8 py-4 border border-cyan-400/30" },
                            React.createElement("h1", { className: "text-3xl font-bold text-white tracking-wider" }, "\uD83C\uDFEA \u51B2\u6C34\u5802 \uD83C\uDFEA"))),
                    React.createElement("div", { className: "mt-4 text-cyan-200 text-sm" }, "\uD83D\uDCB0 \u4FEE\u4ED9\u754C\u4EA4\u6613\u96C6\u5E02 \uD83D\uDCB0")),
                React.createElement("div", { className: "max-w-6xl mx-auto" },
                    React.createElement("div", { className: "relative" },
                        React.createElement("div", { className: "absolute inset-0 bg-gradient-to-r from-cyan-500/20 to-blue-500/20 rounded-3xl blur-xl" }),
                        React.createElement("div", { className: "relative backdrop-blur-sm bg-white/10 rounded-3xl border border-cyan-400/30 p-8" },
                            React.createElement("div", { className: "text-center mb-8" },
                                React.createElement("div", { className: "flex items-center justify-center gap-4 mb-4" },
                                    React.createElement("div", { className: "w-12 h-12 bg-gradient-to-br from-cyan-400 to-blue-600 rounded-xl flex items-center justify-center border border-cyan-300/50" },
                                        React.createElement("span", { className: "text-2xl" }, "\uD83C\uDFEA")),
                                    React.createElement("h2", { className: "text-2xl font-bold text-cyan-300" }, "\u51B2\u6C34\u5802")),
                                React.createElement("div", { className: "grid grid-cols-1 md:grid-cols-3 gap-4 mb-6" },
                                    React.createElement("div", { className: "bg-gradient-to-r from-green-500/20 to-emerald-500/20 rounded-xl p-3 border border-green-400/30 backdrop-blur-sm" },
                                        React.createElement("div", { className: "text-sm text-green-200 font-medium" }, "\u4E0A\u67B6\u6307\u4EE4"),
                                        React.createElement("div", { className: "text-xs text-gray-300" }, "#\u4E0A\u67B6+\u7269\u54C1\u540D*\u4EF7\u683C*\u6570\u91CF")),
                                    React.createElement("div", { className: "bg-gradient-to-r from-blue-500/20 to-indigo-500/20 rounded-xl p-3 border border-blue-400/30 backdrop-blur-sm" },
                                        React.createElement("div", { className: "text-sm text-blue-200 font-medium" }, "\u9009\u8D2D\u6307\u4EE4"),
                                        React.createElement("div", { className: "text-xs text-gray-300" }, "#\u9009\u8D2D+\u7F16\u53F7*\u6570\u91CF")),
                                    React.createElement("div", { className: "bg-gradient-to-r from-red-500/20 to-pink-500/20 rounded-xl p-3 border border-red-400/30 backdrop-blur-sm" },
                                        React.createElement("div", { className: "text-sm text-red-200 font-medium" }, "\u4E0B\u67B6\u6307\u4EE4"),
                                        React.createElement("div", { className: "text-xs text-gray-300" }, "#\u4E0B\u67B6+\u7F16\u53F7")))),
                            React.createElement("div", { className: "grid grid-cols-2 gap-6" }, Exchange_list &&
                                Exchange_list.map((item, index) => (React.createElement("div", { key: index, className: "relative group" },
                                    React.createElement("div", { className: "absolute inset-0 bg-gradient-to-br from-cyan-400/20 to-blue-600/20 rounded-2xl blur-sm" }),
                                    React.createElement("div", { className: "relative backdrop-blur-md bg-white/5 rounded-2xl border border-cyan-400/40 p-6" },
                                        React.createElement("div", { className: "flex items-center justify-between mb-4" },
                                            React.createElement("div", { className: "flex items-center gap-3" },
                                                React.createElement("div", { className: "w-10 h-10 bg-gradient-to-br from-cyan-400 to-blue-600 rounded-lg flex items-center justify-center" },
                                                    React.createElement("span", { className: "text-sm" },
                                                        item.name.class === '装备' && '⚔️',
                                                        item.name.class === '丹药' && '🧪',
                                                        item.name.class === '功法' && '📚',
                                                        item.name.class === '道具' && '🎒',
                                                        item.name.class === '仙宠' && '🐉',
                                                        item.name.class === '草药' && '🌿')),
                                                React.createElement("div", null,
                                                    React.createElement("h3", { className: "text-lg font-bold text-cyan-200" }, item.name.class === '装备'
                                                        ? `【${item.name.class}】${item.name.name}【${item.pinji}】`
                                                        : `【${item.name.class}】${item.name.name}`),
                                                    React.createElement("span", { className: "text-xs text-gray-400" }, item.name.class))),
                                            React.createElement("div", { className: "text-right" },
                                                React.createElement("div", { className: "text-lg font-bold text-yellow-300" },
                                                    "No.",
                                                    item.num),
                                                React.createElement("div", { className: "text-xs text-yellow-400" }, "\u7F16\u53F7"))),
                                        item.name.class === '装备' && (React.createElement("div", { className: "grid grid-cols-2 gap-3 mb-4" },
                                            item.name.atk > 10 ||
                                                item.name.def > 10 ||
                                                item.name.HP > 10 ? (React.createElement(React.Fragment, null,
                                                React.createElement("div", { className: "flex items-center gap-2" },
                                                    React.createElement("div", { className: "w-6 h-6 bg-gradient-to-br from-gray-400 to-gray-600 rounded-full flex items-center justify-center" },
                                                        React.createElement("span", { className: "text-xs" }, "\u26A1")),
                                                    React.createElement("span", { className: "text-sm text-gray-200" }, "\u5C5E\u6027: \u65E0")),
                                                React.createElement("div", { className: "flex items-center gap-2" },
                                                    React.createElement("div", { className: "w-6 h-6 bg-gradient-to-br from-red-400 to-red-600 rounded-full flex items-center justify-center" },
                                                        React.createElement("span", { className: "text-xs" }, "\u2694\uFE0F")),
                                                    React.createElement("span", { className: "text-sm text-red-200" },
                                                        "\u653B\u51FB\uFF1A",
                                                        item.name.atk.toFixed(0))),
                                                React.createElement("div", { className: "flex items-center gap-2" },
                                                    React.createElement("div", { className: "w-6 h-6 bg-gradient-to-br from-blue-400 to-blue-600 rounded-full flex items-center justify-center" },
                                                        React.createElement("span", { className: "text-xs" }, "\uD83D\uDEE1\uFE0F")),
                                                    React.createElement("span", { className: "text-sm text-blue-200" },
                                                        "\u9632\u5FA1\uFF1A",
                                                        item.name.def.toFixed(0))),
                                                React.createElement("div", { className: "flex items-center gap-2" },
                                                    React.createElement("div", { className: "w-6 h-6 bg-gradient-to-br from-green-400 to-green-600 rounded-full flex items-center justify-center" },
                                                        React.createElement("span", { className: "text-xs" }, "\u2764\uFE0F")),
                                                    React.createElement("span", { className: "text-sm text-green-200" },
                                                        "\u8840\u91CF\uFF1A",
                                                        item.name.HP.toFixed(0))))) : (React.createElement(React.Fragment, null,
                                                React.createElement("div", { className: "flex items-center gap-2" },
                                                    React.createElement("div", { className: "w-6 h-6 bg-gradient-to-br from-yellow-400 to-yellow-600 rounded-full flex items-center justify-center" },
                                                        React.createElement("span", { className: "text-xs" }, "\uD83C\uDF1F")),
                                                    React.createElement("span", { className: "text-sm text-yellow-200" },
                                                        "\u5C5E\u6027:",
                                                        ' ',
                                                        ['金', '木', '土', '水', '火'][item.name.id - 1])),
                                                React.createElement("div", { className: "flex items-center gap-2" },
                                                    React.createElement("div", { className: "w-6 h-6 bg-gradient-to-br from-red-400 to-red-600 rounded-full flex items-center justify-center" },
                                                        React.createElement("span", { className: "text-xs" }, "\u2694\uFE0F")),
                                                    React.createElement("span", { className: "text-sm text-red-200" },
                                                        "\u653B\u51FB\uFF1A",
                                                        (item.name.atk * 100).toFixed(0),
                                                        "%")),
                                                React.createElement("div", { className: "flex items-center gap-2" },
                                                    React.createElement("div", { className: "w-6 h-6 bg-gradient-to-br from-blue-400 to-blue-600 rounded-full flex items-center justify-center" },
                                                        React.createElement("span", { className: "text-xs" }, "\uD83D\uDEE1\uFE0F")),
                                                    React.createElement("span", { className: "text-sm text-blue-200" },
                                                        "\u9632\u5FA1\uFF1A",
                                                        (item.name.def * 100).toFixed(0),
                                                        "%")),
                                                React.createElement("div", { className: "flex items-center gap-2" },
                                                    React.createElement("div", { className: "w-6 h-6 bg-gradient-to-br from-green-400 to-green-600 rounded-full flex items-center justify-center" },
                                                        React.createElement("span", { className: "text-xs" }, "\u2764\uFE0F")),
                                                    React.createElement("span", { className: "text-sm text-green-200" },
                                                        "\u8840\u91CF\uFF1A",
                                                        (item.name.HP * 100).toFixed(0),
                                                        "%")))),
                                            React.createElement("div", { className: "flex items-center gap-2" },
                                                React.createElement("div", { className: "w-6 h-6 bg-gradient-to-br from-purple-400 to-purple-600 rounded-full flex items-center justify-center" },
                                                    React.createElement("span", { className: "text-xs" }, "\uD83D\uDCA5")),
                                                React.createElement("span", { className: "text-sm text-purple-200" },
                                                    "\u66B4\u51FB\uFF1A",
                                                    (item.name.bao * 100).toFixed(0),
                                                    "%")))),
                                        item.name.class === '仙宠' && (React.createElement("div", { className: "bg-gradient-to-r from-purple-500/10 to-pink-500/10 rounded-xl p-4 border border-purple-400/20 mb-4" },
                                            React.createElement("div", { className: "flex items-center gap-2" },
                                                React.createElement("div", { className: "w-6 h-6 bg-gradient-to-br from-purple-400 to-purple-600 rounded-full flex items-center justify-center" },
                                                    React.createElement("span", { className: "text-xs" }, "\uD83D\uDC09")),
                                                React.createElement("span", { className: "text-sm font-medium text-purple-200" },
                                                    "\u7B49\u7EA7\uFF1A",
                                                    item.name.等级.toFixed(0))))),
                                        React.createElement("div", { className: "grid grid-cols-2 gap-3 mb-4" },
                                            React.createElement("div", { className: "flex items-center gap-2" },
                                                React.createElement("div", { className: "w-6 h-6 bg-gradient-to-br from-blue-400 to-blue-600 rounded-full flex items-center justify-center" },
                                                    React.createElement("span", { className: "text-xs" }, "\uD83D\uDCB0")),
                                                React.createElement("span", { className: "text-sm text-blue-200" },
                                                    "\u5355\u4EF7\uFF1A",
                                                    item.price)),
                                            React.createElement("div", { className: "flex items-center gap-2" },
                                                React.createElement("div", { className: "w-6 h-6 bg-gradient-to-br from-green-400 to-green-600 rounded-full flex items-center justify-center" },
                                                    React.createElement("span", { className: "text-xs" }, "\uD83D\uDCE6")),
                                                React.createElement("span", { className: "text-sm text-green-200" },
                                                    "\u6570\u91CF\uFF1A",
                                                    item.aconut)),
                                            React.createElement("div", { className: "flex items-center gap-2" },
                                                React.createElement("div", { className: "w-6 h-6 bg-gradient-to-br from-yellow-400 to-yellow-600 rounded-full flex items-center justify-center" },
                                                    React.createElement("span", { className: "text-xs" }, "\uD83D\uDC8E")),
                                                React.createElement("span", { className: "text-sm text-yellow-200" },
                                                    "\u603B\u4EF7\uFF1A",
                                                    item.whole)),
                                            React.createElement("div", { className: "flex items-center gap-2" },
                                                React.createElement("div", { className: "w-6 h-6 bg-gradient-to-br from-gray-400 to-gray-600 rounded-full flex items-center justify-center" },
                                                    React.createElement("span", { className: "text-xs" }, "\uD83D\uDC64")),
                                                React.createElement("span", { className: "text-sm text-gray-200" },
                                                    "\u8D26\u53F7\uFF1A",
                                                    item.qq))),
                                        React.createElement("div", { className: "flex justify-center gap-3" },
                                            React.createElement("div", { className: "inline-block px-3 py-2 bg-gradient-to-r from-green-500/20 to-emerald-500/20 rounded-full border border-green-400/30 backdrop-blur-sm" },
                                                React.createElement("span", { className: "text-green-200 text-sm font-medium" }, "\uD83D\uDED2 \u8D2D\u4E70")),
                                            React.createElement("div", { className: "inline-block px-3 py-2 bg-gradient-to-r from-red-500/20 to-pink-500/20 rounded-full border border-red-400/30 backdrop-blur-sm" },
                                                React.createElement("span", { className: "text-red-200 text-sm font-medium" }, "\u274C \u4E0B\u67B6"))))))))))),
                React.createElement("div", { className: "text-center mt-12" },
                    React.createElement("div", { className: "inline-block px-6 py-3 bg-gradient-to-r from-cyan-600/20 to-blue-600/20 rounded-full border border-cyan-400/30 backdrop-blur-sm" },
                        React.createElement("span", { className: "text-cyan-200 text-sm" }, "\uD83D\uDCB0 \u51B2\u6C34\u5802\u4E2D\u4EA4\u6613\u5FD9\uFF0C\u4FEE\u4ED9\u8DEF\u4E0A\u5171\u6210\u957F \uD83D\uDCB0")))))));
};

export { Supermarket as default };
