import React from 'react';
import HTML from './HTML.js';

const TianDiTang = ({ name, jifen, commodities_list }) => {
    return (React.createElement(HTML, null,
        React.createElement("div", { className: "min-h-screen bg-gradient-to-br from-slate-900 via-orange-900 to-slate-900 relative overflow-hidden" },
            React.createElement("div", { className: "absolute inset-0 opacity-10" },
                React.createElement("div", { className: "absolute top-10 left-10 w-32 h-32 border border-orange-400 rounded-full" }),
                React.createElement("div", { className: "absolute top-32 right-20 w-24 h-24 border border-yellow-400 rounded-full" }),
                React.createElement("div", { className: "absolute bottom-20 left-1/4 w-16 h-16 border border-red-400 rounded-full" }),
                React.createElement("div", { className: "absolute bottom-40 right-1/3 w-20 h-20 border border-amber-400 rounded-full" })),
            React.createElement("div", { className: "relative z-10 container mx-auto px-4 py-8" },
                React.createElement("div", { className: "text-center mb-12" },
                    React.createElement("div", { className: "inline-block relative" },
                        React.createElement("div", { className: "absolute inset-0 bg-gradient-to-r from-orange-600 to-yellow-600 rounded-2xl blur-lg opacity-50" }),
                        React.createElement("div", { className: "relative bg-gradient-to-r from-orange-600 to-yellow-600 rounded-2xl px-8 py-4 border border-orange-400/30" },
                            React.createElement("h1", { className: "text-3xl font-bold text-white tracking-wider" }, "\uD83C\uDFDB\uFE0F \u5929\u5730\u5802 \uD83C\uDFDB\uFE0F"))),
                    React.createElement("div", { className: "mt-4 text-orange-200 text-sm" }, "\uD83D\uDC8E \u4FEE\u4ED9\u754C\u79EF\u5206\u5151\u6362\u5723\u5730 \uD83D\uDC8E")),
                React.createElement("div", { className: "max-w-6xl mx-auto" },
                    React.createElement("div", { className: "relative" },
                        React.createElement("div", { className: "absolute inset-0 bg-gradient-to-r from-orange-500/20 to-yellow-500/20 rounded-3xl blur-xl" }),
                        React.createElement("div", { className: "relative backdrop-blur-sm bg-white/10 rounded-3xl border border-orange-400/30 p-8" },
                            React.createElement("div", { className: "text-center mb-8" },
                                React.createElement("div", { className: "flex items-center justify-center gap-4 mb-4" },
                                    React.createElement("div", { className: "w-12 h-12 bg-gradient-to-br from-orange-400 to-yellow-600 rounded-xl flex items-center justify-center border border-orange-300/50" },
                                        React.createElement("span", { className: "text-2xl" }, "\uD83C\uDFDB\uFE0F")),
                                    React.createElement("h2", { className: "text-2xl font-bold text-orange-300" }, "\u5929\u5730\u5802")),
                                React.createElement("div", { className: "space-y-2 mb-6" },
                                    React.createElement("div", { className: "text-sm text-gray-300" }, "\u8D2D\u4E70\u6307\u4EE4\uFF1A#\u79EF\u5206\u5151\u6362+\u7269\u54C1\u540D"),
                                    React.createElement("div", { className: "text-sm text-gray-300" }, "\u6BCF\u5468\u65E5\u5F00\u653E\u7269\u54C1\u5151\u6362")),
                                React.createElement("div", { className: "inline-block px-6 py-3 bg-gradient-to-r from-green-500/20 to-emerald-500/20 rounded-full border border-green-400/30 backdrop-blur-sm" },
                                    React.createElement("span", { className: "text-green-200 text-lg font-bold" },
                                        name,
                                        "\u7684\u79EF\u5206\uFF1A",
                                        jifen))),
                            React.createElement("div", { className: "grid grid-cols-2 gap-6" }, commodities_list &&
                                commodities_list.map((item, index) => (React.createElement("div", { key: index, className: "relative group" },
                                    React.createElement("div", { className: "absolute inset-0 bg-gradient-to-br from-orange-400/20 to-yellow-600/20 rounded-2xl blur-sm" }),
                                    React.createElement("div", { className: "relative backdrop-blur-md bg-white/5 rounded-2xl border border-orange-400/40 p-6" },
                                        React.createElement("div", { className: "flex items-center justify-between mb-4" },
                                            React.createElement("div", { className: "flex items-center gap-3" },
                                                React.createElement("div", { className: "w-10 h-10 bg-gradient-to-br from-orange-400 to-yellow-600 rounded-lg flex items-center justify-center" },
                                                    React.createElement("span", { className: "text-sm" },
                                                        item.class === '装备' && '⚔️',
                                                        item.class === '丹药' && '🧪',
                                                        item.class === '功法' && '📚',
                                                        item.class === '道具' && '🎒',
                                                        item.class === '草药' && '🌿')),
                                                React.createElement("div", null,
                                                    React.createElement("h3", { className: "text-lg font-bold text-orange-200" },
                                                        "\u3010",
                                                        item.type,
                                                        "\u3011",
                                                        item.name),
                                                    React.createElement("span", { className: "text-xs text-gray-400" }, item.class))),
                                            React.createElement("div", { className: "text-right" },
                                                React.createElement("div", { className: "text-lg font-bold text-green-300" }, item.积分),
                                                React.createElement("div", { className: "text-xs text-green-400" }, "\u79EF\u5206"))),
                                        item.class === '装备' && (React.createElement("div", { className: "grid grid-cols-2 gap-3 mb-4" },
                                            React.createElement("div", { className: "flex items-center gap-2" },
                                                React.createElement("div", { className: "w-6 h-6 bg-gradient-to-br from-red-400 to-red-600 rounded-full flex items-center justify-center" },
                                                    React.createElement("span", { className: "text-xs" }, "\u2694\uFE0F")),
                                                React.createElement("span", { className: "text-sm text-red-200" },
                                                    "\u653B\u51FB\uFF1A",
                                                    item.atk)),
                                            React.createElement("div", { className: "flex items-center gap-2" },
                                                React.createElement("div", { className: "w-6 h-6 bg-gradient-to-br from-blue-400 to-blue-600 rounded-full flex items-center justify-center" },
                                                    React.createElement("span", { className: "text-xs" }, "\uD83D\uDEE1\uFE0F")),
                                                React.createElement("span", { className: "text-sm text-blue-200" },
                                                    "\u9632\u5FA1\uFF1A",
                                                    item.def)),
                                            React.createElement("div", { className: "flex items-center gap-2" },
                                                React.createElement("div", { className: "w-6 h-6 bg-gradient-to-br from-green-400 to-green-600 rounded-full flex items-center justify-center" },
                                                    React.createElement("span", { className: "text-xs" }, "\u2764\uFE0F")),
                                                React.createElement("span", { className: "text-sm text-green-200" },
                                                    "\u8840\u91CF\uFF1A",
                                                    item.HP)),
                                            React.createElement("div", { className: "flex items-center gap-2" },
                                                React.createElement("div", { className: "w-6 h-6 bg-gradient-to-br from-purple-400 to-purple-600 rounded-full flex items-center justify-center" },
                                                    React.createElement("span", { className: "text-xs" }, "\uD83D\uDCA5")),
                                                React.createElement("span", { className: "text-sm text-purple-200" },
                                                    "\u66B4\u51FB\uFF1A",
                                                    (item.bao * 100).toFixed(0),
                                                    "%")))),
                                        item.class === '丹药' && (React.createElement("div", { className: "bg-gradient-to-r from-red-500/10 to-pink-500/10 rounded-xl p-4 border border-red-400/20 mb-4" },
                                            React.createElement("div", { className: "flex items-center gap-2 mb-2" },
                                                React.createElement("div", { className: "w-6 h-6 bg-gradient-to-br from-red-400 to-red-600 rounded-full flex items-center justify-center" },
                                                    React.createElement("span", { className: "text-xs" }, "\uD83D\uDC8A")),
                                                React.createElement("span", { className: "text-sm font-medium text-red-200" }, "\u4E39\u836F\u6548\u679C")),
                                            React.createElement("p", { className: "text-sm text-gray-200" },
                                                item.exp,
                                                item.xueqi))),
                                        item.class === '功法' && (React.createElement("div", { className: "bg-gradient-to-r from-purple-500/10 to-indigo-500/10 rounded-xl p-4 border border-purple-400/20 mb-4" },
                                            React.createElement("div", { className: "flex items-center gap-2 mb-2" },
                                                React.createElement("div", { className: "w-6 h-6 bg-gradient-to-br from-purple-400 to-purple-600 rounded-full flex items-center justify-center" },
                                                    React.createElement("span", { className: "text-xs" }, "\uD83D\uDCDA")),
                                                React.createElement("span", { className: "text-sm font-medium text-purple-200" }, "\u4FEE\u70BC\u52A0\u6210")),
                                            React.createElement("p", { className: "text-sm text-gray-200" },
                                                (item.修炼加成 * 100).toFixed(0),
                                                "%"))),
                                        (item.class === '道具' || item.class === '草药') && (React.createElement("div", { className: "bg-gradient-to-r from-green-500/10 to-emerald-500/10 rounded-xl p-4 border border-green-400/20 mb-4" },
                                            React.createElement("div", { className: "flex items-center gap-2 mb-2" },
                                                React.createElement("div", { className: "w-6 h-6 bg-gradient-to-br from-green-400 to-green-600 rounded-full flex items-center justify-center" },
                                                    React.createElement("span", { className: "text-xs" }, "\uD83D\uDCDD")),
                                                React.createElement("span", { className: "text-sm font-medium text-green-200" }, "\u63CF\u8FF0")),
                                            React.createElement("p", { className: "text-sm text-gray-200" }, item.desc))),
                                        React.createElement("div", { className: "flex justify-center" },
                                            React.createElement("div", { className: "inline-block px-4 py-2 bg-gradient-to-r from-orange-500/20 to-yellow-500/20 rounded-full border border-orange-400/30 backdrop-blur-sm" },
                                                React.createElement("span", { className: "text-orange-200 text-sm font-medium" }, "\uD83D\uDCB0 \u5151\u6362\u6B64\u7269\u54C1"))))))))))),
                React.createElement("div", { className: "text-center mt-12" },
                    React.createElement("div", { className: "inline-block px-6 py-3 bg-gradient-to-r from-orange-600/20 to-yellow-600/20 rounded-full border border-orange-400/30 backdrop-blur-sm" },
                        React.createElement("span", { className: "text-orange-200 text-sm" }, "\uD83D\uDC8E \u5929\u5730\u5802\u4E2D\u85CF\u73CD\u5B9D\uFF0C\u79EF\u5206\u5151\u6362\u663E\u795E\u901A \uD83D\uDC8E")))))));
};

export { TianDiTang as default };
