import React from 'react';
import HTML from './HTML.js';
import { Image } from 'jsxp';

var updateRecord = ({ Record }) => {
    return (React.createElement(HTML, null,
        React.createElement("div", { className: 'min-h-screen bg-gradient-to-br from-slate-900 via-teal-900 to-slate-900 relative overflow-hidden' },
            React.createElement("div", { className: 'absolute inset-0 opacity-10' },
                React.createElement("div", { className: 'absolute top-10 left-10 w-32 h-32 border border-teal-400 rounded-full' }),
                React.createElement("div", { className: 'absolute top-32 right-20 w-24 h-24 border border-cyan-400 rounded-full' }),
                React.createElement("div", { className: 'absolute bottom-20 left-1/4 w-16 h-16 border border-blue-400 rounded-full' }),
                React.createElement("div", { className: 'absolute bottom-40 right-1/3 w-20 h-20 border border-indigo-400 rounded-full' })),
            React.createElement("div", { className: 'relative z-10 container mx-auto px-4 py-8' },
                React.createElement("div", { className: 'text-center mb-8' },
                    React.createElement("div", { className: 'inline-block relative' },
                        React.createElement("div", { className: 'absolute inset-0 bg-gradient-to-r from-teal-600 to-cyan-600 rounded-2xl blur-lg opacity-50' }),
                        React.createElement("div", { className: 'relative bg-gradient-to-r from-teal-600 to-cyan-600 rounded-2xl px-8 py-4 border border-teal-400/30' },
                            React.createElement("h1", { className: 'text-3xl font-bold text-white tracking-wider' }, "\uD83D\uDCDC \u4FEE\u4ED9\u754C\u66F4\u65B0\u65E5\u5FD7 \uD83D\uDCDC")))),
                React.createElement("div", { className: 'max-w-4xl mx-auto' },
                    React.createElement("div", { className: 'relative' },
                        React.createElement("div", { className: 'absolute inset-0 bg-gradient-to-r from-teal-500/20 to-cyan-500/20 rounded-3xl blur-xl' }),
                        React.createElement("div", { className: 'relative backdrop-blur-sm bg-white/10 rounded-3xl border border-teal-400/30 p-8' },
                            React.createElement("div", { className: 'space-y-6' }, Record.map((item, index) => (React.createElement("div", { key: item.id || index, className: 'relative' },
                                React.createElement("div", { className: 'absolute inset-0 bg-gradient-to-r from-teal-400/10 to-cyan-400/10 rounded-2xl blur-sm' }),
                                React.createElement("div", { className: 'relative backdrop-blur-md bg-white/5 rounded-2xl border border-teal-400/20 p-6' },
                                    React.createElement("div", { className: 'flex items-start gap-6' },
                                        React.createElement("div", { className: 'flex flex-col items-center' },
                                            React.createElement("div", { className: 'relative' },
                                                React.createElement("div", { className: 'absolute inset-0 bg-gradient-to-br from-teal-400 to-cyan-600 rounded-full blur-sm' }),
                                                React.createElement("div", { className: 'relative w-16 h-16 rounded-full border-2 border-teal-400/30 overflow-hidden' }, item.user.avatar ? (React.createElement(Image, { src: item.user.avatar, alt: item.user.name, className: 'w-full h-full object-cover' })) : (React.createElement("div", { className: 'w-full h-full bg-gradient-to-br from-teal-400 to-cyan-600 flex items-center justify-center text-2xl font-bold text-white' }, item.user.name.charAt(0))))),
                                            React.createElement("div", { className: 'mt-3 text-center' },
                                                React.createElement("span", { className: 'text-sm font-medium text-teal-200' }, item.user.name))),
                                        React.createElement("div", { className: 'flex-1' },
                                            React.createElement("div", { className: 'bg-gradient-to-r from-teal-500/10 to-cyan-500/10 rounded-xl p-4 border border-teal-400/20' },
                                                React.createElement("p", { className: 'text-base text-gray-200 leading-relaxed' }, item.text)),
                                            React.createElement("div", { className: 'flex items-center gap-2 mt-4' },
                                                React.createElement("div", { className: 'w-6 h-6 bg-gradient-to-br from-yellow-400 to-orange-600 rounded-full flex items-center justify-center' },
                                                    React.createElement("span", { className: 'text-xs' }, "\u23F0")),
                                                React.createElement("time", { className: 'text-sm text-yellow-200 font-medium' }, item.time))))))))),
                            React.createElement("div", { className: 'mt-8 pt-6 border-t border-teal-400/20' },
                                React.createElement("div", { className: 'flex items-center justify-center gap-6' },
                                    React.createElement("div", { className: 'flex items-center gap-2' },
                                        React.createElement("div", { className: 'w-6 h-6 bg-gradient-to-br from-teal-400 to-cyan-600 rounded-full flex items-center justify-center' },
                                            React.createElement("span", { className: 'text-xs' }, "\uD83D\uDCCA")),
                                        React.createElement("span", { className: 'text-sm text-teal-200' },
                                            "\u5171 ",
                                            Record.length,
                                            " \u6761\u66F4\u65B0\u8BB0\u5F55"))))))),
                React.createElement("div", { className: 'text-center mt-12' },
                    React.createElement("div", { className: 'inline-block px-6 py-3 bg-gradient-to-r from-teal-600/20 to-cyan-600/20 rounded-full border border-teal-400/30 backdrop-blur-sm' },
                        React.createElement("span", { className: 'text-teal-200 text-sm' }, "\uD83D\uDCDC \u4FEE\u4ED9\u8DEF\u4E0A\uFF0C\u6BCF\u4E00\u6B21\u66F4\u65B0\u90FD\u662F\u65B0\u7684\u5F00\u59CB \uD83D\uDCDC")))))));
};

export { updateRecord as default };
