import React from 'react';
import fileUrl$2 from '../styles/player.scss.js';
import fileUrl from '../img/player.jpg.js';
import fileUrl$1 from '../img/player_footer.png.js';
import HTML from './HTML.js';
import { Avatar } from './Avatar.js';

const Player = ({ avatar, PowerMini, player = {}, user_id, strand_hp = {}, lingshi, this_association = {}, player_atk, player_atk2, player_def, player_def2, bao, 攻击加成, 攻击加成_t, 防御加成, 防御加成_t, 生命加成, 生命加成_t, talent, occupation, 婚姻状况, rank_lianqi, expmax_lianqi, strand_lianqi = {}, rank_llianti, expmax_llianti, strand_llianti = {}, rank_liandan, expmax_liandan, strand_liandan = {}, neidan, player_action }) => {
    const genders = ['未知', '女', '男', '扶她'];
    const Pets = ({ value }) => {
        return (React.createElement("div", { className: "item wupin " },
            React.createElement("div", { className: "item_title2" },
                "\u3010",
                value.品级,
                "\u3011",
                value.name),
            React.createElement("div", { className: "item_int2" },
                "\u7B49\u7EA7\uFF1A",
                value.等级),
            value.type === '战斗' ? (React.createElement("div", { className: "item_int2" },
                "\u4E09\u7EF4\u52A0\u6210",
                value.atk)) : (React.createElement("div", { className: "item_int2" },
                value.type,
                "\u52A0\u6210:",
                (value.加成 * 100).toFixed(1),
                "%")),
            React.createElement("div", { className: "item_int2" },
                "\u7ED1\u5B9A\uFF1A",
                value.灵魂绑定 === 1 ? '有' : '无')));
    };
    const PetsReander = Array.isArray(player.仙宠) ? (player.仙宠.map((pet, index) => React.createElement(Pets, { key: index, value: pet }))) : (React.createElement(Pets, { value: player.仙宠 }));
    return (React.createElement(HTML, { className: "p-0 m-0 w-full text-center", linkStyleSheets: [fileUrl$2], dangerouslySetInnerHTML: {
            __html: `
          body {
            background-image: url(${fileUrl}), url(${fileUrl$1});
            background-repeat: no-repeat, repeat;
            background-size: 100%, auto;
          }
        `
        } },
        React.createElement("div", null,
            React.createElement("div", { className: "header" }),
            React.createElement("div", { className: "card_box flex pb-6" },
                React.createElement("div", { className: "user_top_left w-72" },
                    React.createElement("div", { className: "flex justify-center" },
                        React.createElement(Avatar, { src: avatar, rootClassName: "w-60 h-60", className: "w-40 h-40" })),
                    React.createElement("div", { className: "mt-4 mx-4 relative" },
                        React.createElement("div", { className: "bg-gradient-to-r from-amber-400 to-orange-500 rounded-2xl px-4 py-2 shadow-xl border-2 border-amber-300 backdrop-blur-sm" },
                            React.createElement("div", { className: "flex items-center gap-3" },
                                React.createElement("div", { className: "w-8 h-8 bg-white/20 rounded-full flex items-center justify-center" },
                                    React.createElement("span", { className: "text-white text-sm" }, "\u2694\uFE0F")),
                                React.createElement("div", { className: "text-center" },
                                    React.createElement("div", { className: "text-white text-xs font-medium opacity-90" }, "\u6218\u529B"),
                                    React.createElement("div", { className: "text-white text-2xl font-bold drop-shadow-lg" }, PowerMini))),
                            React.createElement("div", { className: "absolute -top-1 -right-1 w-3 h-3 bg-yellow-300 rounded-full opacity-60 animate-pulse" }),
                            React.createElement("div", { className: "absolute -bottom-1 -left-1 w-2 h-2 bg-orange-300 rounded-full opacity-40" })))),
                React.createElement("div", { className: "user_top_right flex-1 text-slate-600" },
                    React.createElement("div", { className: "space-y-3" },
                        React.createElement("div", { className: "flex items-center gap-2 bg-[hsla(42,71%,91%,.502)] backdrop-blur-sm rounded-lg p-2 border border-white/20" },
                            React.createElement("span", { className: " text-sm" }, "\uD83D\uDC64"),
                            React.createElement("span", { className: " font-medium" },
                                "\u9053\u53F7\uFF1A",
                                player.名号)),
                        React.createElement("div", { className: "flex items-center gap-2 bg-[hsla(42,71%,91%,.502)] backdrop-blur-sm rounded-lg p-2 border border-white/20" },
                            React.createElement("span", { className: " text-sm" }, "\uD83D\uDCAC"),
                            React.createElement("span", { className: "font-medium" },
                                "QQ\uFF1A",
                                user_id)),
                        React.createElement("div", { className: "flex items-center gap-2 bg-[hsla(42,71%,91%,.502)] backdrop-blur-sm rounded-lg p-2 border border-white/20" },
                            React.createElement("span", { className: " text-sm" }, "\u26A7"),
                            React.createElement("span", { className: " font-medium" },
                                "\u6027\u522B\uFF1A(",
                                genders[player.sex],
                                ")")),
                        React.createElement("div", { className: "bg-[hsla(42,71%,91%,.502)] backdrop-blur-sm rounded-lg p-3 border border-white/20" },
                            React.createElement("div", { className: "flex items-center gap-2 mb-2" },
                                React.createElement("span", { className: " text-sm" }, "\u2764\uFE0F"),
                                React.createElement("span", { className: "font-medium " }, "\u751F\u547D")),
                            React.createElement("div", { className: "relative w-72 text-white h-8 bg-gray-800/80 rounded-xl shadow-lg overflow-hidden border-2 border-l-yellow-300/50" },
                                React.createElement("div", { className: "h-full bg-gradient-to-r from-red-500 to-red-600 rounded-lg transition-all duration-300 ease-out shadow-inner", style: strand_hp.style }),
                                React.createElement("div", { className: "absolute inset-0 flex items-center justify-center" },
                                    React.createElement("span", { className: "font-bold text-sm drop-shadow-lg" },
                                        player.当前血量?.toFixed(0),
                                        "/",
                                        player.血量上限?.toFixed(0))))),
                        React.createElement("div", { className: "flex items-center gap-2 bg-[hsla(42,71%,91%,.502)] backdrop-blur-sm rounded-lg p-2 border border-white/20" },
                            React.createElement("span", { className: " text-sm" }, "\uD83D\uDCB0"),
                            React.createElement("span", { className: "text-white font-medium" },
                                "\u7075\u77F3\uFF1A",
                                lingshi)),
                        React.createElement("div", { className: "flex items-center gap-2 bg-[hsla(42,71%,91%,.502)] backdrop-blur-sm rounded-lg p-2 border border-white/20" },
                            React.createElement("span", { className: " text-sm" }, "\uD83C\uDFDB\uFE0F"),
                            React.createElement("span", { className: "  font-medium" },
                                "\u5B97\u95E8\uFF1A\u3010",
                                this_association.宗门名称,
                                "\u3011",
                                this_association.宗门名称 !== '无' &&
                                    `[${this_association.职位}]`)),
                        React.createElement("div", { className: "flex items-center gap-2 bg-[hsla(42,71%,91%,.502)] backdrop-blur-sm rounded-lg p-2 border border-white/20" },
                            React.createElement("span", { className: " text-sm" }, "\uD83D\uDCDC"),
                            React.createElement("span", { className: "font-medium" },
                                "\u9053\u5BA3\uFF1A",
                                player.宣言))))),
            React.createElement("div", { className: "card_box" },
                React.createElement("div", { className: "use_data" },
                    React.createElement("div", { className: "flex items-center gap-3 mb-6" },
                        React.createElement("div", { className: "w-10 h-10 bg-white/40 backdrop-blur-sm rounded-lg flex items-center justify-center" },
                            React.createElement("span", { className: "text-lg" }, "\uD83D\uDC64")),
                        React.createElement("h2", { className: "text-2xl font-bold text-gray-700" }, "\u3010\u57FA\u7840\u4FE1\u606F\u3011")),
                    React.createElement("div", { className: "user_font wupin" },
                        React.createElement("div", { className: "item" },
                            React.createElement("div", { className: "item_title font_left" },
                                "\u653B\u51FB\uFF1A",
                                player_atk,
                                React.createElement("sup", null, player_atk2)),
                            React.createElement("div", { className: "item_title font_left" },
                                "\u9632\u5FA1\uFF1A",
                                player_def,
                                React.createElement("sup", null, player_def2)),
                            React.createElement("div", { className: "item_title font_left" },
                                "\u66B4\u51FB\uFF1A",
                                bao),
                            React.createElement("div", { className: "item_title font_left" },
                                "\u66B4\u4F24\uFF1A",
                                (player.暴击伤害 * 100).toFixed(0),
                                "%")),
                        React.createElement("div", { className: "item" },
                            React.createElement("div", { className: "item_title font_left" },
                                "\u653B\u51FB\uFF1A",
                                攻击加成,
                                React.createElement("sup", null, 攻击加成_t)),
                            React.createElement("div", { className: "item_title font_left" },
                                "\u9632\u5FA1\uFF1A",
                                防御加成,
                                React.createElement("sup", null, 防御加成_t)),
                            React.createElement("div", { className: "item_title font_left" },
                                "\u751F\u547D\uFF1A",
                                生命加成,
                                React.createElement("sup", null, 生命加成_t))),
                        React.createElement("div", { className: "item" },
                            React.createElement("div", { className: "item_title font_left" },
                                "\u4FEE\u70BC\u52A0\u6210\uFF1A",
                                talent,
                                "%"),
                            React.createElement("div", { className: "item_title font_left" },
                                "\u804C\u4E1A\uFF1A[",
                                occupation,
                                "]"),
                            React.createElement("div", { className: "item_title font_left" },
                                "\u9053\u4FA3[",
                                婚姻状况,
                                "]"))),
                    React.createElement("div", { className: "user_font wupin" },
                        React.createElement("div", { className: "item" },
                            React.createElement("div", { className: "item_title font_left" },
                                rank_lianqi,
                                player.修为 >= expmax_lianqi && '[UP]'),
                            React.createElement("div", { className: "item_int" },
                                React.createElement("div", { className: "relative w-full h-6 bg-gray-700 rounded-lg overflow-hidden border border-gray-600" },
                                    React.createElement("div", { className: "h-full bg-gradient-to-r from-blue-500 to-blue-600 rounded-lg transition-all duration-300 ease-out shadow-inner", style: strand_lianqi.style }),
                                    React.createElement("div", { className: "absolute inset-0 flex items-center justify-center" },
                                        React.createElement("span", { className: "text-white font-bold text-xs drop-shadow-lg" },
                                            strand_lianqi.num,
                                            "%")))),
                            React.createElement("div", { className: "item_int" },
                                player.修为,
                                "/",
                                expmax_lianqi)),
                        React.createElement("div", { className: "item" },
                            React.createElement("div", { className: "item_title font_left" },
                                rank_llianti,
                                player.血气 >= expmax_llianti && '[UP]'),
                            React.createElement("div", { className: "item_int" },
                                React.createElement("div", { className: "relative w-full h-6 bg-gray-700 rounded-lg overflow-hidden border border-gray-600" },
                                    React.createElement("div", { className: "h-full bg-gradient-to-r from-green-500 to-green-600 rounded-lg transition-all duration-300 ease-out shadow-inner", style: strand_llianti.style }),
                                    React.createElement("div", { className: "absolute inset-0 flex items-center justify-center" },
                                        React.createElement("span", { className: "text-white font-bold text-xs drop-shadow-lg" },
                                            strand_llianti.num,
                                            "%")))),
                            React.createElement("div", { className: "item_int" },
                                player.血气,
                                "/",
                                expmax_llianti)),
                        player.occupation.length == 0 ? (React.createElement("div", { className: "item" },
                            React.createElement("div", { className: "item_title font_left" }, "\u804C\u4E1A\uFF1A"),
                            React.createElement("div", { className: "item_title font_left" }, "\u65E0\u4E1A\u6E38\u6C11"))) : (React.createElement("div", { className: "item" },
                            React.createElement("div", { className: "item_title font_left" },
                                rank_liandan,
                                player.occupation_exp >= expmax_liandan && '[UP]'),
                            React.createElement("div", { className: "item_int" },
                                React.createElement("div", { className: "relative w-full h-6 bg-gray-700 rounded-lg overflow-hidden border border-gray-600" },
                                    React.createElement("div", { className: "h-full bg-gradient-to-r from-purple-500 to-purple-600 rounded-lg transition-all duration-300 ease-out shadow-inner", style: strand_liandan.style }),
                                    React.createElement("div", { className: "absolute inset-0 flex items-center justify-center" },
                                        React.createElement("span", { className: "text-white font-bold text-xs drop-shadow-lg" },
                                            strand_liandan.num,
                                            "%")))),
                            React.createElement("div", { className: "item_int" },
                                player.occupation_exp,
                                "/",
                                expmax_liandan)))),
                    React.createElement("div", { className: "user_font wupin" },
                        React.createElement("div", { className: "item" },
                            React.createElement("div", { className: "item_title font_left" },
                                React.createElement("div", null),
                                "\u7075\u6839\uFF1A\u3010",
                                player.灵根?.type,
                                "\u3011",
                                player.灵根?.type !== '无' && (React.createElement(React.Fragment, null,
                                    player.灵根?.name,
                                    React.createElement("br", null),
                                    "\u88AB\u52A8\uFF1A\u3010\u989D\u5916\u589E\u4F24\u3011\u653B\u51FB+",
                                    (player.灵根?.法球倍率 * 100).toFixed(1),
                                    "%")),
                                React.createElement("br", null),
                                "\u9547\u5996\uFF1A\u3010",
                                player.镇妖塔层数,
                                "\u5C42\u3011",
                                React.createElement("br", null),
                                "\u795E\u9B42\uFF1A\u3010",
                                player.神魄段数,
                                "\u5C42\u3011",
                                React.createElement("br", null),
                                "\u5E78\u8FD0:\u3010",
                                (player.幸运 * 100).toFixed(1),
                                "%\u3011",
                                React.createElement("br", null),
                                "\u9B54\u9053\u503C:\u3010",
                                player.魔道值,
                                "\u3011",
                                React.createElement("br", null),
                                "\u5185\u4E39:\u3010",
                                neidan,
                                "\u3011",
                                React.createElement("br", null),
                                "\u72B6\u6001\uFF1A\u3010",
                                player_action,
                                "\u3011"))))),
            React.createElement("div", { className: "card_box" },
                React.createElement("div", { className: "use_data" },
                    React.createElement("div", { className: "flex items-center gap-3 mb-6" },
                        React.createElement("div", { className: "w-10 h-10 bg-white/40 backdrop-blur-sm rounded-lg flex items-center justify-center" },
                            React.createElement("span", { className: "text-lg" }, "\uD83D\uDC08\u200D\u2B1B")),
                        React.createElement("h2", { className: "text-2xl font-bold text-gray-700" }, "\u4ED9\u5BA0")),
                    React.createElement("div", { className: "user_font wupin" }, PetsReander))),
            React.createElement("div", { className: "user_bottom2" }))));
};

export { Player as default };
