import React from 'react';
import fileUrl from '../img/player.jpg.js';
import fileUrl$1 from '../img/player_footer.png.js';
import HTML from './HTML.js';
import { Avatar } from './Avatar.js';
import { BackgroundImage } from 'jsxp';

const Player = ({ avatar, PowerMini, bg_url: bgURL, player = {}, user_id, strand_hp = {}, lingshi, this_association = {}, player_atk, player_atk2, player_def, player_def2, bao, 攻击加成, 攻击加成_t, 防御加成, 防御加成_t, 生命加成, 生命加成_t, talent, occupation, 婚姻状况, rank_lianqi, expmax_lianqi, strand_lianqi = {}, rank_llianti, expmax_llianti, strand_llianti = {}, rank_liandan, expmax_liandan, strand_liandan = {}, neidan, player_action }) => {
    const genders = ['未知', '女', '男', '扶她'];
    const Pets = ({ value }) => {
        return (React.createElement("div", { className: 'bg-[hsla(42,71%,91%,.502)] backdrop-blur-sm rounded-lg p-3 border border-white/20 shadow-lg' },
            React.createElement("div", { className: 'space-y-2' },
                React.createElement("div", { className: 'text-center' },
                    React.createElement("h3", { className: 'text-base font-bold text-gray-900 drop-shadow-sm' },
                        "\u3010",
                        value.品级,
                        "\u3011",
                        value.name)),
                React.createElement("div", { className: 'space-y-1.5 text-sm' },
                    React.createElement("div", { className: 'flex items-center justify-between' },
                        React.createElement("span", { className: 'font-semibold text-gray-800' }, "\u7B49\u7EA7"),
                        React.createElement("span", { className: 'font-bold text-gray-900 text-base' }, value.等级)),
                    value.type === '战斗' ? (React.createElement("div", { className: 'flex items-center justify-between' },
                        React.createElement("span", { className: 'font-semibold text-gray-800' }, "\u4E09\u7EF4\u52A0\u6210"),
                        React.createElement("span", { className: 'font-bold text-gray-900 text-base' }, value.atk))) : (React.createElement("div", { className: 'flex items-center justify-between' },
                        React.createElement("span", { className: 'font-semibold text-gray-800' },
                            value.type,
                            "\u52A0\u6210"),
                        React.createElement("span", { className: 'font-bold text-gray-900 text-base' },
                            (value.加成 * 100).toFixed(1),
                            "%"))),
                    React.createElement("div", { className: 'flex items-center justify-between' },
                        React.createElement("span", { className: 'font-semibold text-gray-800' }, "\u7ED1\u5B9A"),
                        React.createElement("span", { className: 'font-bold text-gray-900 text-base' }, value.灵魂绑定 === 1 ? '有' : '无'))))));
    };
    const PetsReander = Array.isArray(player.仙宠) ? (player.仙宠.map((pet, index) => React.createElement(Pets, { key: index, value: pet }))) : player?.仙宠?.name ? (React.createElement(Pets, { value: player.仙宠 })) : null;
    const curBGImage = bgURL ? [bgURL] : [fileUrl, fileUrl$1];
    return (React.createElement(HTML, null,
        React.createElement(BackgroundImage, { className: 'bg-cover p-0 m-0 w-full text-center', src: curBGImage, style: {
                backgroundRepeat: 'no-repeat, repeat',
                backgroundSize: '100%, auto'
            } },
            React.createElement("div", { className: 'h-3' }),
            React.createElement("div", null,
                React.createElement("div", { className: 'm-3 mx-auto flex flex-nowrap rounded-3xl z-999 bg-[radial-gradient(at_top_left,#ffffff10,#d7edea10)] border-t border-[#ffcc80] border-l border-[#ffcc80] border-r border-[#bb8020] border-b border-[#bb8020] backdrop-blur-sm w-[780px] pb-4' },
                    React.createElement("div", { className: 'text-center mt-5 ml-4 w-80' },
                        React.createElement("div", { className: 'flex justify-center' },
                            React.createElement(Avatar, { src: avatar, rootClassName: 'w-64 h-64', className: 'w-44 h-44' })),
                        React.createElement("div", { className: 'mt-3 mx-2 relative' },
                            React.createElement("div", { className: 'bg-gradient-to-r from-amber-400 to-orange-500 rounded-xl px-3 py-2 shadow-xl border-2 border-amber-300 backdrop-blur-sm' },
                                React.createElement("div", { className: 'flex items-center gap-2' },
                                    React.createElement("div", { className: 'w-6 h-6 bg-white/20 rounded-full flex items-center justify-center' },
                                        React.createElement("span", { className: 'text-white text-sm' }, "\u2694\uFE0F")),
                                    React.createElement("div", { className: 'text-center' },
                                        React.createElement("div", { className: 'text-white text-xs font-semibold opacity-90 drop-shadow-sm' }, "\u6218\u529B"),
                                        React.createElement("div", { className: 'text-white text-2xl font-bold drop-shadow-lg' }, PowerMini))),
                                React.createElement("div", { className: 'absolute -top-1 -right-1 w-3 h-3 bg-yellow-300 rounded-full opacity-60 animate-pulse' }),
                                React.createElement("div", { className: 'absolute -bottom-1 -left-1 w-2 h-2 bg-orange-300 rounded-full opacity-40' })))),
                    React.createElement("div", { className: 'float-right text-left mr-4 mt-4 rounded-3xl flex-1 text-slate-600' },
                        React.createElement("div", { className: 'space-y-2' },
                            React.createElement("div", { className: 'flex items-center gap-2 bg-[hsla(42,71%,91%,.502)] backdrop-blur-sm rounded-lg p-2 border border-white/20' },
                                React.createElement("span", { className: 'text-base' }, "\uD83D\uDC64"),
                                React.createElement("span", { className: 'text-base font-semibold text-gray-900 drop-shadow-sm' },
                                    "\u9053\u53F7\uFF1A",
                                    player.名号)),
                            React.createElement("div", { className: 'flex items-center gap-2 bg-[hsla(42,71%,91%,.502)] backdrop-blur-sm rounded-lg p-2 border border-white/20' },
                                React.createElement("span", { className: 'text-base' }, "\uD83D\uDCAC"),
                                React.createElement("span", { className: 'text-base font-semibold text-gray-900 drop-shadow-sm' },
                                    "\u8D26\u53F7\uFF1A",
                                    user_id)),
                            React.createElement("div", { className: 'flex items-center gap-2 bg-[hsla(42,71%,91%,.502)] backdrop-blur-sm rounded-lg p-2 border border-white/20' },
                                React.createElement("span", { className: 'text-base' }, "\u26A7"),
                                React.createElement("span", { className: 'text-base font-semibold text-gray-900 drop-shadow-sm' },
                                    "\u6027\u522B\uFF1A(",
                                    genders[player.sex || 0],
                                    ")")),
                            React.createElement("div", { className: 'bg-[hsla(42,71%,91%,.502)] backdrop-blur-sm rounded-lg p-2 border border-white/20' },
                                React.createElement("div", { className: 'flex items-center gap-2 mb-2' },
                                    React.createElement("span", { className: 'text-base' }, "\u2764\uFE0F"),
                                    React.createElement("span", { className: 'text-base font-semibold text-gray-900 drop-shadow-sm' }, "\u751F\u547D")),
                                React.createElement("div", { className: 'relative w-64 text-white h-8 bg-gradient-to-r from-gray-800 to-gray-700 rounded-lg shadow-lg overflow-hidden border border-gray-600/50' },
                                    React.createElement("div", { className: 'absolute inset-0 bg-gradient-to-r from-transparent via-white/5 to-transparent' }),
                                    React.createElement("div", { className: 'h-full bg-gradient-to-r from-red-400 via-red-500 to-red-600 rounded-lg transition-all duration-300 ease-out shadow-lg relative overflow-hidden', style: strand_hp.style },
                                        React.createElement("div", { className: 'absolute inset-0 bg-gradient-to-r from-transparent via-white/20 to-transparent' }),
                                        React.createElement("div", { className: 'absolute top-0 left-0 w-full h-0.5 bg-gradient-to-r from-transparent via-white/30 to-transparent' }),
                                        React.createElement("div", { className: 'absolute bottom-0 left-0 w-full h-0.5 bg-gradient-to-r from-transparent via-black/20 to-transparent' })),
                                    React.createElement("div", { className: 'absolute inset-0 flex items-center justify-center' },
                                        React.createElement("span", { className: 'font-bold text-sm drop-shadow-lg' },
                                            player.当前血量?.toFixed(0),
                                            "/",
                                            player.血量上限?.toFixed(0))))),
                            React.createElement("div", { className: 'flex items-center gap-2 bg-[hsla(42,71%,91%,.502)] backdrop-blur-sm rounded-lg p-2 border border-white/20' },
                                React.createElement("span", { className: 'text-base' }, "\uD83D\uDCB0"),
                                React.createElement("span", { className: 'text-base font-semibold text-gray-900 drop-shadow-sm' },
                                    "\u7075\u77F3\uFF1A",
                                    lingshi)),
                            React.createElement("div", { className: 'flex items-center gap-2 bg-[hsla(42,71%,91%,.502)] backdrop-blur-sm rounded-lg p-2 border border-white/20' },
                                React.createElement("span", { className: 'text-base' }, "\uD83C\uDFDB\uFE0F"),
                                React.createElement("span", { className: 'text-base font-semibold text-gray-900 drop-shadow-sm' },
                                    "\u5B97\u95E8\uFF1A\u3010",
                                    this_association.宗门名称,
                                    "\u3011",
                                    this_association.宗门名称 !== '无' && `[${this_association.职位}]`)),
                            React.createElement("div", { className: 'flex items-center gap-2 bg-[hsla(42,71%,91%,.502)] backdrop-blur-sm rounded-lg p-2 border border-white/20' },
                                React.createElement("span", { className: 'text-base' }, "\uD83D\uDCDC"),
                                React.createElement("span", { className: 'text-base font-semibold text-gray-900 drop-shadow-sm' },
                                    "\u9053\u5BA3\uFF1A",
                                    player.宣言))))),
                React.createElement("div", { className: 'm-3 mx-auto flex flex-nowrap rounded-3xl z-999 bg-[radial-gradient(at_top_left,#ffffff10,#d7edea10)] border-t border-[#ffcc80] border-l border-[#ffcc80] border-r border-[#bb8020] border-b border-[#bb8020] backdrop-blur-sm w-[780px]' },
                    React.createElement("div", { className: 'm-4 w-[780px]' },
                        React.createElement("div", { className: 'flex items-center gap-3 mb-3' },
                            React.createElement("div", { className: 'w-6 h-6 bg-white/40 backdrop-blur-sm rounded-lg flex items-center justify-center' },
                                React.createElement("span", { className: 'text-sm' }, "\uD83D\uDC64")),
                            React.createElement("h2", { className: 'text-xl font-bold text-gray-900 drop-shadow-sm' }, "\u3010\u57FA\u7840\u4FE1\u606F\u3011")),
                        React.createElement("div", { className: 'space-y-3' },
                            React.createElement("div", { className: 'grid grid-cols-1 md:grid-cols-3 gap-3' },
                                React.createElement("div", { className: 'bg-[hsla(42,71%,91%,.502)] backdrop-blur-sm rounded-lg p-3 border border-white/20 shadow-lg' },
                                    React.createElement("div", { className: 'space-y-2' },
                                        React.createElement("div", { className: 'flex items-center justify-between' },
                                            React.createElement("span", { className: 'text-base font-semibold text-gray-800' }, "\u653B\u51FB"),
                                            React.createElement("span", { className: 'font-bold text-gray-900 text-lg' },
                                                player_atk,
                                                React.createElement("sup", { className: 'text-sm text-gray-700 ml-1' }, player_atk2))),
                                        React.createElement("div", { className: 'flex items-center justify-between' },
                                            React.createElement("span", { className: 'text-base font-semibold text-gray-800' }, "\u9632\u5FA1"),
                                            React.createElement("span", { className: 'font-bold text-gray-900 text-lg' },
                                                player_def,
                                                React.createElement("sup", { className: 'text-sm text-gray-700 ml-1' }, player_def2))),
                                        React.createElement("div", { className: 'flex items-center justify-between' },
                                            React.createElement("span", { className: 'text-base font-semibold text-gray-800' }, "\u66B4\u51FB"),
                                            React.createElement("span", { className: 'font-bold text-gray-900 text-lg' }, bao)),
                                        React.createElement("div", { className: 'flex items-center justify-between' },
                                            React.createElement("span", { className: 'text-base font-semibold text-gray-800' }, "\u66B4\u4F24"),
                                            React.createElement("span", { className: 'font-bold text-gray-900 text-lg' },
                                                ((player.暴击伤害 || 0) * 100).toFixed(0),
                                                "%")))),
                                React.createElement("div", { className: 'bg-[hsla(42,71%,91%,.502)] backdrop-blur-sm rounded-lg p-3 border border-white/20 shadow-lg' },
                                    React.createElement("div", { className: 'space-y-2' },
                                        React.createElement("div", { className: 'flex items-center justify-between' },
                                            React.createElement("span", { className: 'text-base font-semibold text-gray-800' }, "\u653B\u51FB\u52A0\u6210"),
                                            React.createElement("span", { className: 'font-bold text-gray-900 text-lg' },
                                                攻击加成,
                                                React.createElement("sup", { className: 'text-sm text-gray-700 ml-1' }, 攻击加成_t))),
                                        React.createElement("div", { className: 'flex items-center justify-between' },
                                            React.createElement("span", { className: 'text-base font-semibold text-gray-800' }, "\u9632\u5FA1\u52A0\u6210"),
                                            React.createElement("span", { className: 'font-bold text-gray-900 text-lg' },
                                                防御加成,
                                                React.createElement("sup", { className: 'text-sm text-gray-700 ml-1' }, 防御加成_t))),
                                        React.createElement("div", { className: 'flex items-center justify-between' },
                                            React.createElement("span", { className: 'text-base font-semibold text-gray-800' }, "\u751F\u547D\u52A0\u6210"),
                                            React.createElement("span", { className: 'font-bold text-gray-900 text-lg' },
                                                生命加成,
                                                React.createElement("sup", { className: 'text-sm text-gray-700 ml-1' }, 生命加成_t))))),
                                React.createElement("div", { className: 'bg-[hsla(42,71%,91%,.502)] backdrop-blur-sm rounded-lg p-3 border border-white/20 shadow-lg' },
                                    React.createElement("div", { className: 'space-y-2' },
                                        React.createElement("div", { className: 'flex items-center justify-between' },
                                            React.createElement("span", { className: 'text-base font-semibold text-gray-800' }, "\u4FEE\u70BC\u52A0\u6210"),
                                            React.createElement("span", { className: 'font-bold text-gray-900 text-lg' },
                                                talent,
                                                "%")),
                                        React.createElement("div", { className: 'flex items-center justify-between' },
                                            React.createElement("span", { className: 'text-base font-semibold text-gray-800' }, "\u804C\u4E1A"),
                                            React.createElement("span", { className: 'font-bold text-gray-900 text-lg' },
                                                "[",
                                                occupation,
                                                "]")),
                                        React.createElement("div", { className: 'flex items-center justify-between' },
                                            React.createElement("span", { className: 'text-base font-semibold text-gray-800' }, "\u9053\u4FA3"),
                                            React.createElement("span", { className: 'font-bold text-gray-900 text-lg' },
                                                "[",
                                                婚姻状况,
                                                "]")))))),
                        React.createElement("div", { className: 'space-y-3 mt-4' },
                            React.createElement("div", { className: 'grid grid-cols-1 md:grid-cols-3 gap-3' },
                                React.createElement("div", { className: 'bg-[hsla(42,71%,91%,.502)] backdrop-blur-sm rounded-lg p-3 border border-white/20 shadow-lg relative overflow-hidden' },
                                    React.createElement("div", { className: 'absolute top-0 right-0 w-12 h-12 bg-blue-400/10 rounded-full blur-lg' }),
                                    React.createElement("div", { className: 'absolute bottom-0 left-0 w-8 h-8 bg-blue-400/5 rounded-full blur-md' }),
                                    React.createElement("div", { className: 'space-y-2 relative z-10' },
                                        React.createElement("div", { className: 'flex items-center justify-between' },
                                            React.createElement("span", { className: 'text-sm font-semibold text-gray-800 flex items-center gap-1.5' },
                                                React.createElement("span", { className: 'w-3 h-3 bg-blue-500/20 rounded-full flex items-center justify-center' },
                                                    React.createElement("span", { className: 'text-blue-500 text-xs' }, "\u26A1")),
                                                React.createElement("span", { className: 'text-base font-bold text-gray-900' }, rank_lianqi),
                                                player.修为 >= expmax_lianqi && React.createElement("span", { className: 'text-green-600 text-sm font-bold' }, "[UP]"))),
                                        React.createElement("div", { className: 'relative w-full h-8 bg-gradient-to-r from-gray-800 to-gray-700 rounded-lg overflow-hidden border border-gray-600/50 shadow-inner' },
                                            React.createElement("div", { className: 'absolute inset-0 bg-gradient-to-r from-transparent via-white/5 to-transparent' }),
                                            React.createElement("div", { className: 'h-full bg-gradient-to-r from-blue-400 via-blue-500 to-blue-600 rounded-lg transition-all duration-300 ease-out shadow-lg relative overflow-hidden', style: strand_lianqi.style },
                                                React.createElement("div", { className: 'absolute inset-0 bg-gradient-to-r from-transparent via-white/20 to-transparent' }),
                                                React.createElement("div", { className: 'absolute top-0 left-0 w-full h-0.5 bg-gradient-to-r from-transparent via-white/30 to-transparent' }),
                                                React.createElement("div", { className: 'absolute bottom-0 left-0 w-full h-0.5 bg-gradient-to-r from-transparent via-black/20 to-transparent' })),
                                            React.createElement("div", { className: 'absolute inset-0 flex items-center justify-center' },
                                                React.createElement("span", { className: 'text-white font-bold text-base drop-shadow-lg' },
                                                    strand_lianqi.num,
                                                    "%"))),
                                        React.createElement("div", { className: 'text-center text-base font-semibold text-gray-800' },
                                            player.修为,
                                            "/",
                                            expmax_lianqi))),
                                React.createElement("div", { className: 'bg-[hsla(42,71%,91%,.502)] backdrop-blur-sm rounded-lg p-3 border border-white/20 shadow-lg relative overflow-hidden' },
                                    React.createElement("div", { className: 'absolute top-0 right-0 w-12 h-12 bg-green-400/10 rounded-full blur-lg' }),
                                    React.createElement("div", { className: 'absolute bottom-0 left-0 w-8 h-8 bg-green-400/5 rounded-full blur-md' }),
                                    React.createElement("div", { className: 'space-y-2 relative z-10' },
                                        React.createElement("div", { className: 'flex items-center justify-between' },
                                            React.createElement("span", { className: 'text-sm font-semibold text-gray-800 flex items-center gap-1.5' },
                                                React.createElement("span", { className: 'w-3 h-3 bg-green-500/20 rounded-full flex items-center justify-center' },
                                                    React.createElement("span", { className: 'text-green-500 text-xs' }, "\uD83D\uDCAA")),
                                                React.createElement("span", { className: 'text-base font-bold text-gray-900' }, rank_llianti),
                                                player.血气 >= expmax_llianti && React.createElement("span", { className: 'text-green-600 text-sm font-bold' }, "[UP]"))),
                                        React.createElement("div", { className: 'relative w-full h-8 bg-gradient-to-r from-gray-800 to-gray-700 rounded-lg overflow-hidden border border-gray-600/50 shadow-inner' },
                                            React.createElement("div", { className: 'absolute inset-0 bg-gradient-to-r from-transparent via-white/5 to-transparent' }),
                                            React.createElement("div", { className: 'h-full bg-gradient-to-r from-green-400 via-green-500 to-green-600 rounded-lg transition-all duration-300 ease-out shadow-lg relative overflow-hidden', style: strand_llianti.style },
                                                React.createElement("div", { className: 'absolute inset-0 bg-gradient-to-r from-transparent via-white/20 to-transparent' }),
                                                React.createElement("div", { className: 'absolute top-0 left-0 w-full h-0.5 bg-gradient-to-r from-transparent via-white/30 to-transparent' }),
                                                React.createElement("div", { className: 'absolute bottom-0 left-0 w-full h-0.5 bg-gradient-to-r from-transparent via-black/20 to-transparent' })),
                                            React.createElement("div", { className: 'absolute inset-0 flex items-center justify-center' },
                                                React.createElement("span", { className: 'text-white font-bold text-base drop-shadow-lg' },
                                                    strand_llianti.num,
                                                    "%"))),
                                        React.createElement("div", { className: 'text-center text-base font-semibold text-gray-800' },
                                            player.血气,
                                            "/",
                                            expmax_llianti))),
                                player?.occupation.length === 0 ? (React.createElement("div", { className: 'bg-[hsla(42,71%,91%,.502)] backdrop-blur-sm rounded-lg p-3 border border-white/20 shadow-lg' },
                                    React.createElement("div", { className: 'space-y-2' },
                                        React.createElement("div", { className: 'flex items-center justify-between' },
                                            React.createElement("span", { className: 'text-sm font-semibold text-gray-800' }, "\u804C\u4E1A"),
                                            React.createElement("span", { className: 'font-bold text-gray-900 text-base' }, "\u65E0\u4E1A\u6E38\u6C11"))))) : (React.createElement("div", { className: 'bg-[hsla(42,71%,91%,.502)] backdrop-blur-sm rounded-lg p-3 border border-white/20 shadow-lg relative overflow-hidden' },
                                    React.createElement("div", { className: 'absolute top-0 right-0 w-12 h-12 bg-purple-400/10 rounded-full blur-lg' }),
                                    React.createElement("div", { className: 'absolute bottom-0 left-0 w-8 h-8 bg-purple-400/5 rounded-full blur-md' }),
                                    React.createElement("div", { className: 'space-y-2 relative z-10' },
                                        React.createElement("div", { className: 'flex items-center justify-between' },
                                            React.createElement("span", { className: 'text-sm font-semibold text-gray-800 flex items-center gap-1.5' },
                                                React.createElement("span", { className: 'w-3 h-3 bg-purple-500/20 rounded-full flex items-center justify-center' },
                                                    React.createElement("span", { className: 'text-purple-500 text-xs' }, "\uD83E\uDDEA")),
                                                React.createElement("span", { className: 'text-base font-bold text-gray-900' }, rank_liandan),
                                                player?.occupation_exp >= expmax_liandan && React.createElement("span", { className: 'text-green-600 text-sm font-bold' }, "[UP]"))),
                                        React.createElement("div", { className: 'relative w-full h-8 bg-gradient-to-r from-gray-800 to-gray-700 rounded-lg overflow-hidden border border-gray-600/50 shadow-inner' },
                                            React.createElement("div", { className: 'absolute inset-0 bg-gradient-to-r from-transparent via-white/5 to-transparent' }),
                                            React.createElement("div", { className: 'h-full bg-gradient-to-r from-purple-400 via-purple-500 to-purple-600 rounded-lg transition-all duration-300 ease-out shadow-lg relative overflow-hidden', style: strand_liandan.style },
                                                React.createElement("div", { className: 'absolute inset-0 bg-gradient-to-r from-transparent via-white/20 to-transparent' }),
                                                React.createElement("div", { className: 'absolute top-0 left-0 w-full h-0.5 bg-gradient-to-r from-transparent via-white/30 to-transparent' }),
                                                React.createElement("div", { className: 'absolute bottom-0 left-0 w-full h-0.5 bg-gradient-to-r from-transparent via-black/20 to-transparent' })),
                                            React.createElement("div", { className: 'absolute inset-0 flex items-center justify-center' },
                                                React.createElement("span", { className: 'text-white font-bold text-base drop-shadow-lg' },
                                                    strand_liandan.num,
                                                    "%"))),
                                        React.createElement("div", { className: 'text-center text-base font-semibold text-gray-800' },
                                            player.occupation_exp,
                                            "/",
                                            expmax_liandan)))))),
                        React.createElement("div", { className: 'space-y-3 mt-4' },
                            React.createElement("div", { className: 'grid grid-cols-1 md:grid-cols-3 gap-3' },
                                React.createElement("div", { className: 'bg-[hsla(42,71%,91%,.502)] backdrop-blur-sm rounded-lg p-3 border border-white/20 shadow-lg' },
                                    React.createElement("div", { className: 'space-y-2 text-sm' },
                                        React.createElement("div", { className: 'flex items-center justify-between' },
                                            React.createElement("span", { className: 'font-semibold text-gray-800' }, "\u7075\u6839"),
                                            React.createElement("span", { className: 'font-bold text-gray-900 text-base' },
                                                "\u3010",
                                                player.灵根?.type,
                                                "\u3011")),
                                        player.灵根?.type !== '无' && (React.createElement(React.Fragment, null,
                                            React.createElement("div", { className: 'text-center text-gray-800 text-sm font-medium' }, player.灵根?.name),
                                            React.createElement("div", { className: 'text-center text-gray-800 text-sm font-medium' },
                                                "\u88AB\u52A8\uFF1A\u3010\u989D\u5916\u589E\u4F24\u3011\u653B\u51FB+",
                                                (player.灵根?.法球倍率 * 100).toFixed(1),
                                                "%"))),
                                        React.createElement("div", { className: 'flex items-center justify-between' },
                                            React.createElement("span", { className: 'font-semibold text-gray-800' }, "\u9547\u5996"),
                                            React.createElement("span", { className: 'font-bold text-gray-900 text-base' },
                                                "\u3010",
                                                player.镇妖塔层数,
                                                "\u5C42\u3011")))),
                                React.createElement("div", { className: 'bg-[hsla(42,71%,91%,.502)] backdrop-blur-sm rounded-lg p-3 border border-white/20 shadow-lg' },
                                    React.createElement("div", { className: 'space-y-2 text-sm' },
                                        React.createElement("div", { className: 'flex items-center justify-between' },
                                            React.createElement("span", { className: 'font-semibold text-gray-800' }, "\u795E\u9B42"),
                                            React.createElement("span", { className: 'font-bold text-gray-900 text-base' },
                                                "\u3010",
                                                player.神魄段数,
                                                "\u5C42\u3011")),
                                        React.createElement("div", { className: 'flex items-center justify-between' },
                                            React.createElement("span", { className: 'font-semibold text-gray-800' }, "\u5E78\u8FD0"),
                                            React.createElement("span", { className: 'font-bold text-gray-900 text-base' },
                                                "\u3010",
                                                ((player.幸运 || 0) * 100).toFixed(1),
                                                "%\u3011")),
                                        React.createElement("div", { className: 'flex items-center justify-between' },
                                            React.createElement("span", { className: 'font-semibold text-gray-800' }, "\u9B54\u9053\u503C"),
                                            React.createElement("span", { className: 'font-bold text-gray-900 text-base' },
                                                "\u3010",
                                                player.魔道值,
                                                "\u3011")))),
                                React.createElement("div", { className: 'bg-[hsla(42,71%,91%,.502)] backdrop-blur-sm rounded-lg p-3 border border-white/20 shadow-lg' },
                                    React.createElement("div", { className: 'space-y-2 text-sm' },
                                        React.createElement("div", { className: 'flex items-center justify-between' },
                                            React.createElement("span", { className: 'font-semibold text-gray-800' }, "\u5185\u4E39"),
                                            React.createElement("span", { className: 'font-bold text-gray-900 text-base' },
                                                "\u3010",
                                                neidan,
                                                "\u3011")),
                                        React.createElement("div", { className: 'flex items-center justify-between' },
                                            React.createElement("span", { className: 'font-semibold text-gray-800' }, "\u72B6\u6001"),
                                            React.createElement("span", { className: 'font-bold text-gray-900 text-base' },
                                                "\u3010",
                                                player_action,
                                                "\u3011")))))))),
                React.createElement("div", { className: 'm-3 mx-auto flex flex-nowrap rounded-3xl z-999 bg-[radial-gradient(at_top_left,#ffffff10,#d7edea10)] border-t border-[#ffcc80] border-l border-[#ffcc80] border-r border-[#bb8020] border-b border-[#bb8020] backdrop-blur-sm w-[780px]' },
                    React.createElement("div", { className: 'm-4 w-[780px]' },
                        React.createElement("div", { className: 'flex items-center gap-3 mb-3' },
                            React.createElement("div", { className: 'w-6 h-6 bg-white/40 backdrop-blur-sm rounded-lg flex items-center justify-center' },
                                React.createElement("span", { className: 'text-sm' }, "\uD83D\uDC08\u200D\u2B1B")),
                            React.createElement("h2", { className: 'text-xl font-bold text-gray-900 drop-shadow-sm' }, "\u4ED9\u5BA0")),
                        React.createElement("div", { className: 'grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-3' }, PetsReander)))),
            React.createElement("div", { className: 'h-3' }))));
};

export { Player as default };
