import React from 'react';
import fileUrl from '../styles/tw.scss.js';
import fileUrl$1 from '../font/tttgbnumber.ttf.js';
import { LinkStyleSheet } from 'jsxp';

const WuQi = ({ nickname, wuqi_have, wuqi_need }) => {
    return (React.createElement("html", null,
        React.createElement("head", null,
            React.createElement(LinkStyleSheet, { src: fileUrl }),
            React.createElement("meta", { httpEquiv: "content-type", content: "text/html;charset=utf-8" }),
            React.createElement("style", { dangerouslySetInnerHTML: {
                    __html: `
              @font-face { font-family: 'tttgbnumber'; src: url('${fileUrl$1}'); font-weight: normal; font-style: normal; }
              body { font-family: 'tttgbnumber', system-ui, sans-serif; }
            `
                } })),
        React.createElement("body", null,
            React.createElement("div", { className: "min-h-screen bg-gradient-to-b from-gray-100 to-blue-200 flex flex-col items-center py-6" },
                React.createElement("div", { className: "w-full max-w-2xl mx-auto" },
                    React.createElement("div", { className: "text-2xl font-bold text-blue-700 mb-6 text-center drop-shadow" },
                        nickname,
                        "\u7684\u88C5\u5907"),
                    wuqi_have && wuqi_have.length > 0 && (React.createElement("div", { className: "bg-white rounded-xl shadow-lg p-6 mb-6" },
                        React.createElement("div", { className: "text-lg font-semibold text-green-600 mb-2" }, "\u3010\u5DF2\u62E5\u6709\u3011"),
                        React.createElement("div", { className: "grid grid-cols-1 md:grid-cols-2 gap-4" }, wuqi_have.map((item, index) => (React.createElement("div", { key: index, className: "border rounded-lg p-4 bg-gray-50 hover:bg-gray-100 transition" },
                            React.createElement("div", { className: "font-bold text-blue-800 text-lg mb-2 h-11 flex items-center" }, item.name),
                            React.createElement("div", { className: "text-sm text-gray-700" },
                                "\u7C7B\u578B\uFF1A",
                                item.type),
                            item.atk > 10 || item.def > 10 || item.HP > 10 ? (React.createElement(React.Fragment, null,
                                React.createElement("div", { className: "text-sm text-gray-700" },
                                    "\u653B\u51FB\uFF1A",
                                    item.atk),
                                React.createElement("div", { className: "text-sm text-gray-700" },
                                    "\u9632\u5FA1\uFF1A",
                                    item.def),
                                React.createElement("div", { className: "text-sm text-gray-700" },
                                    "\u8840\u91CF\uFF1A",
                                    item.HP))) : (React.createElement(React.Fragment, null,
                                React.createElement("div", { className: "text-sm text-gray-700" },
                                    "\u653B\u51FB\uFF1A",
                                    (item.atk * 100).toFixed(0),
                                    "%"),
                                React.createElement("div", { className: "text-sm text-gray-700" },
                                    "\u9632\u5FA1\uFF1A",
                                    (item.def * 100).toFixed(0),
                                    "%"),
                                React.createElement("div", { className: "text-sm text-gray-700" },
                                    "\u8840\u91CF\uFF1A",
                                    (item.HP * 100).toFixed(0),
                                    "%"))),
                            React.createElement("div", { className: "text-sm text-gray-700" },
                                "\u66B4\u51FB\uFF1A",
                                (item.bao * 100).toFixed(0),
                                "%"))))))),
                    wuqi_need && wuqi_need.length > 0 && (React.createElement("div", { className: "bg-white rounded-xl shadow-lg p-6 mb-6" },
                        React.createElement("div", { className: "text-lg font-semibold text-red-600 mb-2" }, "\u3010\u672A\u62E5\u6709\u3011"),
                        React.createElement("div", { className: "grid grid-cols-1 md:grid-cols-2 gap-4" }, wuqi_need.map((item, index) => (React.createElement("div", { key: index, className: "border rounded-lg p-4 bg-gray-50 hover:bg-gray-100 transition" },
                            React.createElement("div", { className: "font-bold text-blue-800 text-lg mb-2 h-11 flex items-center" }, item.name),
                            React.createElement("div", { className: "text-sm text-gray-700" },
                                "\u7C7B\u578B\uFF1A",
                                item.type),
                            item.atk > 10 || item.def > 10 || item.HP > 10 ? (React.createElement(React.Fragment, null,
                                React.createElement("div", { className: "text-sm text-gray-700" },
                                    "\u653B\u51FB\uFF1A",
                                    item.atk),
                                React.createElement("div", { className: "text-sm text-gray-700" },
                                    "\u9632\u5FA1\uFF1A",
                                    item.def),
                                React.createElement("div", { className: "text-sm text-gray-700" },
                                    "\u8840\u91CF\uFF1A",
                                    item.HP))) : (React.createElement(React.Fragment, null,
                                React.createElement("div", { className: "text-sm text-gray-700" },
                                    "\u653B\u51FB\uFF1A",
                                    (item.atk * 100).toFixed(0),
                                    "%"),
                                React.createElement("div", { className: "text-sm text-gray-700" },
                                    "\u9632\u5FA1\uFF1A",
                                    (item.def * 100).toFixed(0),
                                    "%"),
                                React.createElement("div", { className: "text-sm text-gray-700" },
                                    "\u8840\u91CF\uFF1A",
                                    (item.HP * 100).toFixed(0),
                                    "%"))),
                            React.createElement("div", { className: "text-sm text-gray-700" },
                                "\u66B4\u51FB\uFF1A",
                                (item.bao * 100).toFixed(0),
                                "%"))))))))))));
};

export { WuQi as default };
