import React from 'react';
import HTML from './HTML.js';

const WuQi = ({ nickname, wuqi_have, wuqi_need }) => {
    return (React.createElement(HTML, null,
        React.createElement("div", { className: "min-h-screen bg-gradient-to-br from-slate-900 via-indigo-900 to-slate-900 relative overflow-hidden" },
            React.createElement("div", { className: "absolute inset-0 opacity-10" },
                React.createElement("div", { className: "absolute top-10 left-10 w-32 h-32 border border-indigo-400 rounded-full" }),
                React.createElement("div", { className: "absolute top-32 right-20 w-24 h-24 border border-blue-400 rounded-full" }),
                React.createElement("div", { className: "absolute bottom-20 left-1/4 w-16 h-16 border border-cyan-400 rounded-full" }),
                React.createElement("div", { className: "absolute bottom-40 right-1/3 w-20 h-20 border border-purple-400 rounded-full" })),
            React.createElement("div", { className: "relative z-10 container mx-auto px-4 py-8" },
                React.createElement("div", { className: "text-center mb-8" },
                    React.createElement("div", { className: "inline-block relative" },
                        React.createElement("div", { className: "absolute inset-0 bg-gradient-to-r from-indigo-600 to-blue-600 rounded-2xl blur-lg opacity-50" }),
                        React.createElement("div", { className: "relative bg-gradient-to-r from-indigo-600 to-blue-600 rounded-2xl px-8 py-4 border border-indigo-400/30" },
                            React.createElement("h1", { className: "text-3xl font-bold text-white tracking-wider" },
                                "\u2694\uFE0F ",
                                nickname,
                                "\u7684\u88C5\u5907\u56FE\u9274 \u2694\uFE0F"))),
                    React.createElement("div", { className: "mt-4 text-indigo-200 text-sm" }, "\uD83D\uDDE1\uFE0F \u4FEE\u4ED9\u4E4B\u8DEF\uFF0C\u795E\u5175\u76F8\u4F34 \uD83D\uDDE1\uFE0F")),
                React.createElement("div", { className: "max-w-6xl mx-auto space-y-8" },
                    wuqi_have && wuqi_have.length > 0 && (React.createElement("div", { className: "relative" },
                        React.createElement("div", { className: "absolute inset-0 bg-gradient-to-r from-green-500/20 to-emerald-500/20 rounded-3xl blur-xl" }),
                        React.createElement("div", { className: "relative backdrop-blur-sm bg-white/10 rounded-3xl border border-green-400/30 p-8" },
                            React.createElement("div", { className: "flex items-center mb-6" },
                                React.createElement("div", { className: "w-12 h-12 bg-gradient-to-br from-green-400 to-emerald-600 rounded-xl flex items-center justify-center mr-4 border border-green-300/50" },
                                    React.createElement("span", { className: "text-2xl" }, "\u2694\uFE0F")),
                                React.createElement("h2", { className: "text-2xl font-bold text-green-300 tracking-wide" }, "\u3010\u5DF2\u62E5\u6709\u88C5\u5907\u3011")),
                            React.createElement("div", { className: "grid grid-cols-2 gap-6" }, wuqi_have.map((item, index) => (React.createElement("div", { key: index, className: "group relative" },
                                React.createElement("div", { className: "absolute inset-0 bg-gradient-to-br from-green-400/20 to-emerald-600/20 rounded-2xl blur-sm" }),
                                React.createElement("div", { className: "relative backdrop-blur-md bg-white/5 rounded-2xl border border-green-400/40 p-6" },
                                    React.createElement("div", { className: "flex items-center justify-between mb-4" },
                                        React.createElement("h3", { className: "text-xl font-bold text-green-200" }, item.name),
                                        React.createElement("div", { className: "w-8 h-8 bg-gradient-to-br from-green-400 to-emerald-600 rounded-lg flex items-center justify-center" },
                                            React.createElement("span", { className: "text-sm" }, "\uD83D\uDDE1\uFE0F"))),
                                    React.createElement("div", { className: "space-y-3" },
                                        React.createElement("div", { className: "flex items-center text-sm" },
                                            React.createElement("span", { className: "w-16 text-indigo-200" }, "\u7C7B\u578B"),
                                            React.createElement("span", { className: "text-green-100 font-medium" }, item.type)),
                                        item.atk > 10 || item.def > 10 || item.HP > 10 ? (React.createElement(React.Fragment, null,
                                            React.createElement("div", { className: "flex items-center text-sm" },
                                                React.createElement("span", { className: "w-16 text-indigo-200" }, "\u653B\u51FB"),
                                                React.createElement("span", { className: "text-red-300 font-medium" }, item.atk)),
                                            React.createElement("div", { className: "flex items-center text-sm" },
                                                React.createElement("span", { className: "w-16 text-indigo-200" }, "\u9632\u5FA1"),
                                                React.createElement("span", { className: "text-blue-300 font-medium" }, item.def)),
                                            React.createElement("div", { className: "flex items-center text-sm" },
                                                React.createElement("span", { className: "w-16 text-indigo-200" }, "\u8840\u91CF"),
                                                React.createElement("span", { className: "text-green-300 font-medium" }, item.HP)))) : (React.createElement(React.Fragment, null,
                                            React.createElement("div", { className: "flex items-center text-sm" },
                                                React.createElement("span", { className: "w-16 text-indigo-200" }, "\u653B\u51FB"),
                                                React.createElement("span", { className: "text-red-300 font-medium" },
                                                    (item.atk * 100).toFixed(0),
                                                    "%")),
                                            React.createElement("div", { className: "flex items-center text-sm" },
                                                React.createElement("span", { className: "w-16 text-indigo-200" }, "\u9632\u5FA1"),
                                                React.createElement("span", { className: "text-blue-300 font-medium" },
                                                    (item.def * 100).toFixed(0),
                                                    "%")),
                                            React.createElement("div", { className: "flex items-center text-sm" },
                                                React.createElement("span", { className: "w-16 text-indigo-200" }, "\u8840\u91CF"),
                                                React.createElement("span", { className: "text-green-300 font-medium" },
                                                    (item.HP * 100).toFixed(0),
                                                    "%")))),
                                        React.createElement("div", { className: "flex items-center text-sm" },
                                            React.createElement("span", { className: "w-16 text-indigo-200" }, "\u66B4\u51FB"),
                                            React.createElement("span", { className: "text-purple-300 font-medium" },
                                                (item.bao * 100).toFixed(0),
                                                "%"))))))))))),
                    wuqi_need && wuqi_need.length > 0 && (React.createElement("div", { className: "relative" },
                        React.createElement("div", { className: "absolute inset-0 bg-gradient-to-r from-red-500/20 to-pink-500/20 rounded-3xl blur-xl" }),
                        React.createElement("div", { className: "relative backdrop-blur-sm bg-white/10 rounded-3xl border border-red-400/30 p-8" },
                            React.createElement("div", { className: "flex items-center mb-6" },
                                React.createElement("div", { className: "w-12 h-12 bg-gradient-to-br from-red-400 to-pink-600 rounded-xl flex items-center justify-center mr-4 border border-red-300/50" },
                                    React.createElement("span", { className: "text-2xl" }, "\uD83D\uDD2E")),
                                React.createElement("h2", { className: "text-2xl font-bold text-red-300 tracking-wide" }, "\u3010\u672A\u62E5\u6709\u88C5\u5907\u3011")),
                            React.createElement("div", { className: "grid grid-cols-2 gap-6" }, wuqi_need.map((item, index) => (React.createElement("div", { key: index, className: "group relative" },
                                React.createElement("div", { className: "absolute inset-0 bg-gradient-to-br from-red-400/20 to-pink-600/20 rounded-2xl blur-sm" }),
                                React.createElement("div", { className: "relative backdrop-blur-md bg-white/5 rounded-2xl border border-red-400/40 p-6" },
                                    React.createElement("div", { className: "flex items-center justify-between mb-4" },
                                        React.createElement("h3", { className: "text-xl font-bold text-red-200" }, item.name),
                                        React.createElement("div", { className: "w-8 h-8 bg-gradient-to-br from-red-400 to-pink-600 rounded-lg flex items-center justify-center" },
                                            React.createElement("span", { className: "text-sm" }, "\uD83D\uDD12"))),
                                    React.createElement("div", { className: "space-y-3" },
                                        React.createElement("div", { className: "flex items-center text-sm" },
                                            React.createElement("span", { className: "w-16 text-indigo-200" }, "\u7C7B\u578B"),
                                            React.createElement("span", { className: "text-red-100 font-medium" }, item.type)),
                                        item.atk > 10 || item.def > 10 || item.HP > 10 ? (React.createElement(React.Fragment, null,
                                            React.createElement("div", { className: "flex items-center text-sm" },
                                                React.createElement("span", { className: "w-16 text-indigo-200" }, "\u653B\u51FB"),
                                                React.createElement("span", { className: "text-red-300 font-medium" }, item.atk)),
                                            React.createElement("div", { className: "flex items-center text-sm" },
                                                React.createElement("span", { className: "w-16 text-indigo-200" }, "\u9632\u5FA1"),
                                                React.createElement("span", { className: "text-blue-300 font-medium" }, item.def)),
                                            React.createElement("div", { className: "flex items-center text-sm" },
                                                React.createElement("span", { className: "w-16 text-indigo-200" }, "\u8840\u91CF"),
                                                React.createElement("span", { className: "text-green-300 font-medium" }, item.HP)))) : (React.createElement(React.Fragment, null,
                                            React.createElement("div", { className: "flex items-center text-sm" },
                                                React.createElement("span", { className: "w-16 text-indigo-200" }, "\u653B\u51FB"),
                                                React.createElement("span", { className: "text-red-300 font-medium" },
                                                    (item.atk * 100).toFixed(0),
                                                    "%")),
                                            React.createElement("div", { className: "flex items-center text-sm" },
                                                React.createElement("span", { className: "w-16 text-indigo-200" }, "\u9632\u5FA1"),
                                                React.createElement("span", { className: "text-blue-300 font-medium" },
                                                    (item.def * 100).toFixed(0),
                                                    "%")),
                                            React.createElement("div", { className: "flex items-center text-sm" },
                                                React.createElement("span", { className: "w-16 text-indigo-200" }, "\u8840\u91CF"),
                                                React.createElement("span", { className: "text-green-300 font-medium" },
                                                    (item.HP * 100).toFixed(0),
                                                    "%")))),
                                        React.createElement("div", { className: "flex items-center text-sm" },
                                            React.createElement("span", { className: "w-16 text-indigo-200" }, "\u66B4\u51FB"),
                                            React.createElement("span", { className: "text-purple-300 font-medium" },
                                                (item.bao * 100).toFixed(0),
                                                "%")))))))))))),
                React.createElement("div", { className: "text-center mt-12" },
                    React.createElement("div", { className: "inline-block px-6 py-3 bg-gradient-to-r from-indigo-600/20 to-blue-600/20 rounded-full border border-indigo-400/30 backdrop-blur-sm" },
                        React.createElement("span", { className: "text-indigo-200 text-sm" }, "\u2694\uFE0F \u4FEE\u4ED9\u4E4B\u8DEF\u6F2B\u6F2B\uFF0C\u795E\u5175\u5229\u5668\u76F8\u4F34 \u2694\uFE0F")))))));
};

export { WuQi as default };
