import React from 'react';
import HTML from './HTML.js';
import fileUrl from '../img/fairyrealm.jpg.js';

const ZongMeng = ({ temp }) => {
    const data = temp || [];
    return (React.createElement(HTML, null,
        React.createElement("div", { className: "min-h-screen w-full text-white/90 p-4 md:p-8 bg-center bg-cover font-serif", style: { backgroundImage: `url(${fileUrl})` } },
            React.createElement("main", { className: "max-w-6xl mx-auto space-y-8" },
                React.createElement("header", { className: "flex flex-col items-center text-center" },
                    React.createElement("h1", { className: "px-8 py-3 rounded-lg bg-black/30 backdrop-blur-md text-3xl md:text-4xl font-bold tracking-widest text-amber-200", style: { textShadow: '0 2px 8px rgba(252, 211, 77, 0.5)' } }, "\u4ED9\u95E8\u767E\u5BB6"),
                    React.createElement("p", { className: "mt-2 text-base text-sky-200/80" }, "\u4E8E\u6B64\u65B9\u5929\u5730\uFF0C\u5BFB\u89C5\u6C5D\u4E4B\u9053\u9014")),
                React.createElement("section", { className: "grid gap-6 md:gap-8 sm:grid-cols-2 lg:grid-cols-3" }, data.length ? (data.map((item, index) => (React.createElement("article", { key: index, className: "flex flex-col rounded-xl bg-slate-900/60 backdrop-blur-lg border border-sky-500/30 transition-all duration-300 hover:border-amber-400 hover:shadow-2xl hover:shadow-amber-500/20 hover:-translate-y-2" },
                    React.createElement("header", { className: "p-4 border-b border-sky-500/20 flex justify-between items-center" },
                        React.createElement("h2", { className: "text-xl font-semibold text-amber-100 tracking-wider" }, item.宗名),
                        React.createElement("span", { className: "px-3 py-1 text-sm font-bold bg-sky-800/80 border border-sky-600 rounded-md text-sky-200" },
                            "Lv.",
                            item.等级)),
                    React.createElement("div", { className: "p-4 space-y-3 text-sm flex-grow" },
                        React.createElement("div", { className: "flex items-center gap-3" },
                            React.createElement("span", { className: "text-sky-300 w-20 shrink-0" },
                                ' ',
                                " \u4ED9\u76DF\u4EBA\u6570:"),
                            React.createElement("span", { className: "font-semibold text-white" },
                                item.人数,
                                " / ",
                                item.宗门人数上限)),
                        React.createElement("div", { className: "flex items-center gap-3" },
                            React.createElement("span", { className: "text-sky-300 w-20 shrink-0" },
                                ' ',
                                " \u5929\u8D4B\u52A0\u6210:"),
                            React.createElement("span", { className: "font-semibold text-green-300" },
                                item.天赋加成,
                                "%")),
                        React.createElement("div", { className: "flex items-center gap-3" },
                            React.createElement("span", { className: "text-sky-300 w-20 shrink-0" },
                                ' ',
                                " \u9547\u5B97\u795E\u517D:"),
                            React.createElement("span", { className: "font-semibold text-white" }, item.镇宗神兽)),
                        React.createElement("div", { className: "flex items-center gap-3" },
                            React.createElement("span", { className: "text-sky-300 w-20 shrink-0" },
                                ' ',
                                " \u5B97\u95E8\u9A7B\u5730:"),
                            React.createElement("span", { className: "font-semibold text-white" }, item.宗门驻地)),
                        React.createElement("div", { className: "flex items-center gap-3" },
                            React.createElement("span", { className: "text-sky-300 w-20 shrink-0" },
                                ' ',
                                " \u52A0\u5165\u95E8\u69DB:"),
                            React.createElement("span", { className: "font-semibold text-red-300" }, item.最低加入境界))),
                    React.createElement("footer", { className: "mt-auto p-3 bg-slate-950/50 rounded-b-xl border-t border-sky-500/20 flex items-center justify-between" },
                        React.createElement("span", { className: "text-xs text-sky-300/80" }, "\u5B97\u4E3B\u6CD5\u8C15"),
                        React.createElement("div", { className: "flex items-center gap-2" },
                            React.createElement("img", { src: `https://q1.qlogo.cn/g?b=qq&s=0&nk=${item.宗主}`, alt: "\u5B97\u4E3B\u5934\u50CF", className: "w-6 h-6 rounded-full border border-amber-300/50" }),
                            React.createElement("span", { className: "font-mono text-amber-200 text-sm" }, item.宗主))))))) : (React.createElement("p", { className: "col-span-full text-center text-sky-200/70 text-lg" }, "\u6DF7\u6C8C\u672A\u5F00\uFF0C\u6682\u65E0\u4ED9\u95E8")))))));
};

export { ZongMeng as default };
