const LIB_MAP = {
    npc列表: 'NPC',
    shop列表: 'Shop',
    丹药列表: 'Danyao',
    仙境列表: 'FairyRealm',
    仙宠列表: 'Xianchon',
    仙宠口粮列表: 'Xianchonkouliang',
    兑换列表: 'ExchangeItem',
    八品: 'Bapin',
    功法列表: 'Gongfa',
    商品列表: 'Commodity',
    地点列表: 'Didian',
    天地堂: 'Tianditang',
    宗门秘境: 'GuildSecrets',
    常驻仙宠: 'Changzhuxianchon',
    强化列表: 'Qianghua',
    怪物列表: 'Monster',
    技能列表: 'Jineng',
    技能列表1: 'Jineng1',
    技能列表2: 'Jineng2',
    星阁拍卖行列表: 'Xingge',
    洞天福地: 'Bless',
    灵根列表: 'Talent',
    炼丹师丹药: 'NewDanyao',
    神界列表: 'Shenjie',
    禁地列表: 'ForbiddenArea',
    积分商城: 'ScoreShop',
    草药列表: 'Caoyao',
    装备列表: 'Equipment',
    道具列表: 'Daoju',
    锻造宝物: 'Duanzhaobaowu',
    锻造护具: 'Duanzhaohuju',
    锻造杂类: 'Zalei',
    锻造材料: 'Duanzhaocailiao',
    锻造武器: 'Duanzhaowuqi',
    隐藏灵根: 'Yincang',
    魔界列表: 'Mojie'
};

export { LIB_MAP };
