import '../../../../model/api.js';
import '../../../../model/keys.js';
import '@alemonjs/db';
import { getDataList } from '../../../../model/DataList.js';
import 'jsxp';
import 'md5';
import 'react';
import '../../../../resources/img/state.jpg.js';
import '../../../../resources/styles/tw.scss.js';
import '../../../../resources/font/tttgbnumber.ttf.js';
import 'classnames';
import '../../../../resources/img/player.jpg.js';
import '../../../../resources/img/player_footer.png.js';
import '../../../../resources/img/user_state.png.js';
import '../../../../resources/img/fairyrealm.jpg.js';
import '../../../../resources/img/card.jpg.js';
import '../../../../resources/img/road.jpg.js';
import '../../../../resources/img/user_state2.png.js';
import '../../../../resources/html/help.js';
import '../../../../resources/img/najie.jpg.js';
import '../../../../resources/img/shituhelp.jpg.js';
import '../../../../resources/img/icon.png.js';
import '../../../../resources/styles/temp.scss.js';
import 'fs';
import 'dayjs';
import 'buffer';
import { useMessage, Text } from 'alemonjs';
import '../../../../model/settions.js';
import 'svg-captcha';
import 'sharp';
import 'lodash-es';
import { checkUserMonthCardStatus } from '../../../../model/currency.js';
import 'crypto';
import 'posthog-node';
import '../../../../model/message.js';
import mw, { selects } from '../../../mw-captcha.js';

const regular = /^(#|＃|\/)?仙缘商店$/;
const res = onResponse(selects, async (e) => {
    const [message] = useMessage(e);
    const monthMarketList = await getDataList('MonthMarket');
    const userStatus = await checkUserMonthCardStatus(e.UserId);
    const currency = userStatus?.currency ?? 0;
    const lines = [];
    lines.push('【仙缘商店】');
    lines.push(`仙缘币余额：${currency}`);
    monthMarketList.forEach((item) => {
        lines.push(`${item.name}，${item.price}仙缘币`);
    });
    void message.send(format(Text(lines.join('\n'))));
});
var res_default = onResponse(selects, [mw.current, res.current]);

export { res_default as default, regular };
